### ISSUE TITLE
Write NFT module for user names

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#104]
Builds on #103

The NFT has a unique human-readable username as an id, and a public key (or multiple, one per algorithm) as payload.

Any client look up a name to get a public key, which you can convert to a chain-specific address. This is how the universal wallet addresses will work.

Rather than the `namecoin` implementation, a user can later update the public keys associated with a name. Also, we can allow the transfer of name ownership (more like dns name than email address). This can be a bit dangerous to me in terms of identity theft, but seems to be an important feature from the business side.

TODO: link to the bns specification for this

**Comment by alpe** [comment]
With @Isabello we talked about exampel 
Some questions that popped up:
- What algorithms do we support? 
- What are our normalization + validation rules + constraints?
- Do we allow names without a key?

**Comment by ethanfrey** [comment]
From slack: 

Can we say `[a-z0-9\.,+\-_@]{4,64}` as allowable names? Maybe a few more "special characters" maybe uppercase as well?

**Comment by Isabello** [comment]
We dont need to worry about algo, just accept 
```
{
  ticker: <ticker>,
  address: <derived address> 
}
```

**Comment by Isabello** [comment]
As for names, we should always require a ticker + address in the registration

**Comment by ethanfrey** [comment]
From discussion with @Isabello 

We don't store public keys. We store `chainId` -> `address` mapping (as a sorted array).
A username is the "primary key".
We can have 0 or 1 address for any chainId.
Addresses are unvalidated []byte (as we cannot provide rules on the blockchain for everything). Min length of 12, max or say 50?

**Comment by Isabello** [comment]
Updated my comments to reflect chainId instead of ticker

**Comment by ethanfrey** [comment]
User story 1:

As a compnay/individual with significant cryptocurrency payments, I want a simple name I can place on my business cards and website to easily get paid. I am happy to pay a small amount to register a name, if it is easy for clients to use it for payments. I also wish to change the addresses from time to time as I move my primary accounts.

**Comment by antoineherzog** [comment]
@alpe @ethanfrey @Isabello @Fraicheur2vivre @ruseinov   I would like to be involved in this discussion. I believe this discussion is extremely important and we need to make sure we take the right decision. I asked Jerome to start to write a first document for the BNS (the same kind of document we have for the IOV wallet design intention) and ask him to take the feedback of everyone so we could get a first draft of the Blockchain Name Service intentions. Regarding the NFT of username, my personal preference is to not save any address or identity information inside the NFT of username. We should use the logic of the DNS pointer system.
Please have a look of this diagram.
I suggest Jerome get the feedback of everyone so we can agree on this document together.

**Comment by antoineherzog** [comment]
![bns datatype](https://user-images.githubusercontent.com/13095/45916157-37a92980-be59-11e8-9af0-5fae874d6aaf.png)

**Comment by ethanfrey** [comment]
@antoineherzog this is **very much** out of scope for this story. And meddling with requirements of a story in a running sprint, when you had a few days of heads up to contribute any ideas **before** sprint planning is meddling. I request you to respect the development process which has worked quite well.

Jerome is leading a process to collect all the ideas and requirements for product, and I look forward to some backlog grooming sessions (that I explained to you), where we can discuss these ideas between business and development and figure out feasibility and importance, so they can properly be added to the backlog. I am happy to see some good user stories and explanations of what you wish to achieve and we may build it in a future iteration.

@alpe and @ruseinov please continue on the agreed-upon direction from the sprint planning. As we discussed, this may be refined, but the current design is a good start.

**Comment by ethanfrey** [comment]
Been done a long time
