### ISSUE TITLE
Organize CHANGELOG for recent release

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#1043]
Weave 0.21.3 was released from master at https://github.com/iov-one/weave/commits/v0.21.3 (ea73c9ce47eed49f6eb03b353202dc34a010e481). So everything in the HEAD seaction of https://github.com/iov-one/weave/blob/v0.21.3/CHANGELOG.md should go into a 0.21.3 block, including the "Breaking changes".

The good thing about this is that IOV Core can start connecting message fee update transactions now.

**Comment by husio** [comment]
Was this addressed by https://github.com/iov-one/weave/pull/1044 ?

**Comment by orkunkl** [comment]
Yes, I forgot to close this. Thanks.
