### ISSUE TITLE
Work on clean client api

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#105]
Once we have a design and a first implementation, we should focus on the usability to make sure this works end-to-end before building many more NFTs. This task involved specifying the transaction types and query api, and working with iov-core team to implement bindings.

At the end, we should be able to create, use, transfer, and query the username NFTs in @iov/cli. When the functionality exposed client-side makes sense as useful for building apps, then we can close this story. This may inspire changing the info somewhat, adding secondary indexes, etc....

**Comment by ethanfrey** [comment]
See user stories on #104 Also....

User story 1:

As a user with a wallet on two devices (and same mneumonics), I would like a way to quickly find the usernames associated with any of my public keys stored in my Keyring/UserProfile, so the UI can show the current user names. I would also like the local mapping of public key -> on-chain bns username to be updated when I change the addresses on the bns.

**Comment by ethanfrey** [comment]
User story 2:

As a big username investor, I would like to quickly see a list of all usernames owned (controlled) by any of my private keys, so I can easily assign/reassign addresses to them.

**Comment by ethanfrey** [comment]
User story 3:

As a normal user, I would like to create a username and easily add new identities to it. This should be simple to do for many chains as once. I would also like a very clear view of my username and how it maps to my private keys. The information should be readily available from blockchain queries and the UI should make it intuitive, especially the case of using one "universal public key" on many chains, or using the standard "bip44 chain-specific path" from one mneumonic across many chains.

**Comment by alpe** [comment]
Story 1: 
>quickly find the usernames associated with any of my public keys stored in my Keyring/UserProfile
I am wondering if this is the weave.Address of the owner or the address stored with the chainID in the details? Owners weave.Address is indexed already.

Story 2:
> by any of my private keys
I assume that the client can create a weave.Address type from the private key but is this correct?

Story 3:
>... and easily add new identities to it. 
In context of iov-core an identity is a derived key, afaik. So would this mean we have multiple key addresses for a single username on the same blockchain? Or is it 1 identity per blockchain only but mulitple blockchains? The later one I have impl this morning.

> This should be simple to do for many chains as once
ha, just removed that for add addresses. but it is still possible for issuing a new name with multiple chains. Should I add it back again to `AddChainAddress`? If yes, how about removing an address? Do we want to support multiple at once? Adding mulitple is more complex than nust 1

**Comment by ethanfrey** [comment]
**Story 1:**

> > quickly find the usernames associated with any of my public keys stored in my Keyring/UserProfile

> I am wondering if this is the weave.Address of the owner or the address stored with the chainID in the details? Owners weave.Address is indexed already.

For starter, we just need the owner. That is most important. But this requests that I be able to find what name belongs to any key (from the chain, address). The solution could be to index them all. It could also be to grab all the registered username nfts that I own, combine all the (chainId, address) pairs and compare them with my local keyring. I don't specify how to do it, just that it should be doable without some extreme work on either client or server.

**Story 2:**

> > by any of my private keys

> I assume that the client can create a weave.Address type from the private key but is this correct?

Yes, this is more akin to your understanding of story 1, but focuses on the case when there are *many* usernames with few or no addresses (the other is few usernames with *many* addresses each). `Private key -> public key` is universal crypto and done in any client. `public key -> address` is actually a chain dependent mapping. Since all nfts are on one chain, this is simpler

**Story 3:**

> > ... and easily add new identities to it.

> In context of iov-core an identity is a derived key, afaik. So would this mean we have multiple key addresses for a single username on the same blockchain? Or is it 1 identity per blockchain only but mulitple blockchains? The later one I have impl this morning.

The term "identity" is a bit tricky and either Isabella keeps changing it, or I never really grasped it. I will stick with the works I understand better. Public key can then "automatically" be mapped client-side to a chain-specific address and added as a (chainId, address) pair. We don't want to do that mapping client-side, as that requires the registry to implement logic for any blockchain we add.

As I understand it know, one identity may be many public keys, derived with bip44/slip0010 from the same mneumonic key, and using the same address index, but the different coin type in the path for each chain. (https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Path_levels). This means we would take a mneumonic phrase for the fifth account:
 * generate secp256k1 public key with path `m/44'/0'/0'/0/5` and use bitcoin address encoding, and register it with bitcoin chainId
* generate secp256k1 public key with path `m/44'/60'/0'/0/5` and use ethereum address encoding, and register it with ethereum chainId
* generate ed25519 public key with path eg. `m/44'/4804438'/0'/0'/5'` (ed25519 only handles hardened paths) and use weave address encoding, and register it with bns chainId

The first version (same public key, multiple addresses), was my approach as it is easier to automate. The second version is my understanding of @Isabello design, as it is more secure and adheres to the existing standards (slip-0010).

> > This should be simple to do for many chains as once

> ha, just removed that for add addresses. but it is still possible for issuing a new name with multiple chains. Should I add it back again to AddChainAddress? If yes, how about removing an address? Do we want to support multiple at once? Adding mulitple is more complex than just 1

Yes, I think we will want to automate this client side. Like the user will select an index and then select a list of chains to register on. The app/library will derive all chain-specific public keys and convert them to addresses, returning a list of (chainId, address) pairs for that index. Ideally, this can be submitted as one transaction, but we may wish to have a limit of say 5-20 addresses that can be registered at once to avoid enormous transaction sizes.

**Comment by ethanfrey** [comment]
I can really only start doing this when there is a tagged release with stable nft api (at least for username) that I can start exposing in iov-core

**Comment by alpe** [comment]
@ethanfrey can we close this or port it another project? There is not much we can do other than to support the impl. This happens via slack or new issues.

**Comment by ethanfrey** [comment]
okay, #192 #193 #194 #195 are all basically concrete instances of this abstract issue. And there are sure to get a number more along the way. Now the ball is rolling, let's remove the placeholder.
