### ISSUE TITLE
Implement better secondary index

### ISSUE THREAD

**Issue by husio** [iov-one/weave#1059]
As a developer, I want to be able to define a secondary index that will support any size of data, so that I can index collections beyond 10k elements.

The current secondary index implementation must not be used for data sets bigger than ~100 elements. It is using a [single value in the database](https://github.com/iov-one/weave/blob/4f11e0457b1dd4aeac73a014e8e20c4959e9d2ef/orm/codec.proto#L7-L10) to keep track of the relation.

A performant implementation that allows to store any number of references in a single index without any performance penalty.

As [@webmaster128 explained, there are reason for the current implementation](https://internetofvalues.slack.com/archives/CB0U9AERL/p1574781372027400) and why index size should be kept small.

## Acceptance criteria

- [x] A new index implementation must be provided, that provides the same read and update performance for any set of data,
- [x] Access to the new index should be [implemented as an iterator](https://github.com/iov-one/weave/blob/master/store.go#L71-L80)
- [x] New index must be integrated with the `migration` extension,
- [x] [`ModelBucket.ByIndex`](https://github.com/iov-one/weave/blob/4f11e0457b1dd4aeac73a014e8e20c4959e9d2ef/orm/model_bucket.go#L48) must be able to use the new implementation through the right [`ModelBucketOption` configuration](https://github.com/iov-one/weave/blob/4f11e0457b1dd4aeac73a014e8e20c4959e9d2ef/orm/model_bucket.go#L97).

**Comment by orkunkl** [comment]
I want to implement a benchmark test for this. @husio waste of time or worth it?

**Comment by husio** [comment]
It would be helpful. You could measure what is the memory and CPU load in the current implementation, depending on the index size.
There is a chance that we are wrong and even such naive implementation has a very decent performance. 
Go ahead!

You can use [table tests](https://blog.golang.org/subtests) to benchmark various index sizes.

**Comment by orkunkl** [comment]
On it!
