### ISSUE TITLE
Reward module: minimal implementation

### ISSUE THREAD

**Issue by husio** [iov-one/weave#1061]
As a wallet owner I want to be able to deposit certain amount of funds in a term deposit  module, so that I can be rewarded for it.

[![91dcd0ff9554b25c317c1b77c72f4536](https://user-images.githubusercontent.com/1517/69878092-3167d600-12c4-11ea-9da4-07b0b2151313.png)](https://swimlanes.io/#dVJLj9QwDL73V/gGKzHVcp0Dl0UgTiC0D46bpu7UTGKX2N0HiP+O087OaFbi1Nb9/L0SI0u4hTtMUTKCCegj5RQYtSVpmuZGscBm8wGuhK2EaFv4iJMoGdz/uIcvX299aY+sTfOCgDP0VcFgCN9CMYo0BSNheBtDinOqP/qVTcobheKDCxdt23YLf4agG52IGcvfIyHg00QF9R08jhRHIHUGw5KJsYfuGTD4NJ6hV82+qika9HMh3oGNwU60sdp0WHvK/PT/zA2L4XFa2R3H6tD67p4K/sRo7kiJI578jEEPCfqm+SwPWDhUwHnD3zH0EFJaClEI7F9ZZjYYimS4Ru6XxHbwUfE1Ul05Sh2KVci0G80d/Zpd1p8rtqPdC6kMtZzQ+jWo5tw4vL+83AM6E1V9gyxqLVyPHo2qId8ZII6BeCEE4fQMMuHa9cLE6PH9QvUyd8krGDHuvXTyo+tmAy9TR5lTD54BulWZlR5wXVqgbfNpttldy2SU6fd6kmugbgGe1ANELFYdva4AiAcpebX2Dw==)

~Full specification https://iov.atlassian.net/wiki/spaces/PRODUCT/pages/6258726/Reward+Module+Generalized+PoS~

## Acceptance criteria

- [x] Create a new module `termdeposit` that will contain reward implementation included in `bnsd`,
- [x] Reward fund administrator address is set via `gconf` configuration (similar to other extensions)
- [x] Reward fund administrator can create a new `DepositContract` entity
  - [ ] `DepositContract` can be created via `gov` proposal
  - [ ] `DepositContract` must contain an expiration date that is in the future and an investment return rate
- [x] Any wallet owner can request to deposit any amount within an active reward contract and create a `Deposit` entity by sending a `CreateDepositMsg`.
  - [x] When created, `Deposit` locks declared funds similar to escrow. Locked funds cannot be accessed,
  - [x] sending more tokens to an address where `Deposit` holds the funds does not increase that `Deposit` value. Extra tokens will be released to the depository wallet,
  - [x] a single address can create a deposit for the same `DepositContract` many times, resulting in multiple `Deposit` instances
  - [x] `Deposit` expires when related `DepositContract` expires
  - [ ] :question:  `Deposit` can be deleted only when expired.
- [x] Once created, a `DepositContract` is valid until configured expiration time. A `DepositContract` cannot be modified or deleted.
- [x] It is possible to query all `Deposit` instances for a given `DespositContract`

**Comment by husio** [comment]
@davepuchyr Here is the model and message declaration that I wrote based on the requirements and the flow diagram. Is my data declaration correct? [codec.proto](https://github.com/iov-one/weave/files/3973347/codec.proto.txt)

**Comment by davepuchyr** [comment]
> @davepuchyr Here is the model and message declaration that I wrote based on the requirements and the flow diagram. Is my data declaration correct? [codec.proto](https://github.com/iov-one/weave/files/3973347/codec.proto.txt)
> There is no rate or interest information. No reward computation. This implementation would be similar to an escrow that can expire a lot of contracts at once.

[codec.proto](https://github.com/iov-one/weave/files/3973347/codec.proto.txt) does not put us on a path to the acceptance criteria on this ticket.  

I made an incorrect assumption when I asked you to change `DepositParticipant` to `Depositor` in the acceptance criteria.  Seeing what you've done with the codec makes it clear that I should have asked you to change `DepositParticipant` to  `Deposit`.  With that the acceptance criteria make more sense and your codec tweaked to [codec.dave.proto.txt](https://github.com/iov-one/weave/files/3975736/codec.dave.proto.txt) should be more clear, too. 

The creation date of the contract is irrelevant, only its rate and end date are relevant. 

A deposit's rate is calculated based on the date of the deposit, the contract rate and its end date.  The date of the deposit does not need to be persisted because it is implicit in the deposit's rate.

**Comment by husio** [comment]
Test cases:

- admin can create a contarct
- depositor signature is required in order to create a deposit
- enough funds are required to create deposit
- anyone with enough funds can create a deposit
- deposit cannot be created for a contract that is not yet active
- deposit cannot be created for an expired contract
- non expired deposit cannot be released
- deposit can be released only once
- anyone can release a deposit of an expired contract
- configuration owner can update configuration
- when a deposit is released all wallet funds are sent, not only originally allocated ones
- deposit duration between bonuses
- deposit duration below minimal bonus
- deposit duration above maximum bonus
