### ISSUE TITLE
Revert username owner change

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#1075]
The username module is going to be unused very soon.

In order to use the same message type `username.RegisterTokenMsg` in bnsd 0.22 and upcoming 0.24, we should revert the username part of https://github.com/iov-one/weave/pull/1066. This heavily simplifies reading historic transactions.

**Comment by husio** [comment]
Can you explain once more why we need to reverse this change? It is optional, so old client does not need to implement the new functionality. Why it is important to not allow for an optional owner specification?

**Comment by webmaster128** [comment]
This is relevant for reading transaction lists, not for writing new ones. If the client knows for sure that all register username transactions in the chain's history never had an `owner` field, then the client never needs to parse the optional value and we avoid a case distiction _if owner set, then `owner` is owner, otherwise first signature is owner_.

**Comment by husio** [comment]
I still don't understand. Why client has to support reading the signer field? Is there a UI that requires it or something? If yes, why not adding it? Is it that problematic? In the end, the extension will be removed next month, so does the client really have to support it?

**Comment by webmaster128** [comment]
> Why client has to support reading the signer field? Is there a UI that requires it or something?

IOV Core read the full transaction, no matter if all fields are displayed by our UI or not. As soon as we add an additional `owner` field to the transaction, we need to populate it for all [RegisterUsernameTx](https://github.com/iov-one/iov-core/blob/v1.2.0/packages/iov-bns/src/types.ts#L322-L326).

> If yes, why not adding it? Is it that problematic?

Not problematic but this is additinal code and logic we carry around for the rest of IOV's life if we take transaction history seriously.

> In the end, the extension will be removed next month, so does the client really has to support it?

If transactions with that field exist, yes. If we remove the new field we dont need as described in this ticket, we don't need to do pointless adaptions of both IOV Core, the block explorer and potentially other blockchain clients.
