### ISSUE TITLE
Preregistration: Push data to on-chain from CVS file

### ISSUE THREAD

**Issue by annatorok** [iov-one/weave#1098]
As a [technical expert that can preregister domains](https://github.com/iov-one/weave/blob/dbd1cf9df01d49880022c93ac26bf20c4bd27371/cmd/bnsd/app/datamigration.go#L73),
I want to preregister a set of domains from a given file,
so that all preregistered domains can be imported to `bnsd`.

Domain list is a plain text CSV file. Each line is a single domain name and the owner address, separated by a coma character (`,`). Address is bech32 encoded.
For example:

```sh
$ cat example_list.csv
mycompany,iov1xxxxxxxxxxxxx
yourcompany,iov1yyyyyyyyyyy
```

## Acceptance criteria
- [x] provide a shell script that given a list of domain names and addresses, submit for each entry as a message for [registering that domain in the preregistration extension](https://github.com/iov-one/weave/blob/dbd1cf9df01d49880022c93ac26bf20c4bd27371/cmd/bnsd/x/preregistration/codec.proto#L14-L18)
- [x] provided script must use the recent `bnscli` to create and submit each message

**Comment by husio** [comment]
Preregistration script:

```sh
#!/bin/sh

# Update the below variables.
fee="0.1 IOV"


if [ $# -ne 1 ]
then
        >&2 printf "Usage:\n\t%s <csv file>\n" "$0"
        exit 2
fi

set -e

# First go through all rows and generate the message to ensure all entries are
# correct.
while read -r line
do
        domain=$( echo "$line" | cut -d ',' -f1 )
        owner=$( echo "$line" | cut -d ',' -f2 )
        bnscli preregistration-register \
                        -domain "$domain" \
                        -owner "bech32:$owner" \
                > /dev/null
done < "$1"


while read -r line
do
        domain=$( echo "$line" | cut -d ',' -f1 )
        owner=$( echo "$line" | cut -d ',' -f2 )
        bnscli preregistration-register \
                        -domain "$domain" \
                        -owner "bech32:$owner" \
                | bnscli with-fee -amount "$fee" \
                | bnscli sign \
                | bnscli submit
        printf '.'
done < "$1"
```
