### ISSUE TITLE
Add domain related REST API endpoints

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/weave#1109]
As a domain superuser, I want to know all the domains that I own so that I can manage them.

As a domain superuser, I want to know all of the accounts associated with a domain so that I can manage them.

As IOV, I want to know all of the domains that exist so I can develop strategy for the IOV Name Service.

Pagination is required for all of these user stories because querying domain related data can yield huge amounts of results.

## Acceptance criteria

- [x] paginated queries for the domain implementation module (list of all domains, list of all accounts of a domain, list of all domains owned by someone )

- [x] Anyone can do a `GET /account/domains` request to get a paginated list of all `account.Domain` entities. For example:
  ```
  GET /domains

  {
     "objects": [
       {
         // all Domain attributes
       },
       // ... more
     }
  }
  ```
- [x] Anyone can do a `GET /account/domains?admin=<hex address>` request to get a paginated list of all `account.Domain` entities owned by a given address.
- [x] Anyone can do a `GET /account/accounts?domain=<domain>` request to get a paginated list of all `account.Account` entities assigned to a given domain.

**Comment by husio** [comment]
As discussed during the call, because Domain entity bucket does not have `admin` index, filter and pagination is implemented in the REST API application rather than relying on what otherwise `bnsd` would provide.
