### ISSUE TITLE
Add governance related REST API endpoints

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/weave#1114]
As someone interested in the governance of the IOV Name Service, I want to know about governance, governance proposals, and proposal results so that I can see details regarding the governance of the chain.

The `bnscli` query paths containing `/proposals` and/or `/votes` should suffice in fulfilling the goals of the user story.

## Acceptance criteria

- [x] a paginated query of all proposals is available via the REST API `GET /gov/proposals`
- [x] a paginated query of all proposals authored by a particular elector is available via the REST API `GET /gov/proposals?author=<hex address>`
- [x] a paginated query of all proposals governed by a particular electorate is available via the REST API `GET /gov/proposals?electorate=<number>`
- [x] a paginated query of all votes is available via the REST API `GET /gov/votes`
- [x] a paginated query of all votes by a particular elector is available via the REST API `GET /gov/votes?electorate=<number>`
- [x] a paginated query of all votes on a particular proposal is available via the REST API `GET /gov/votes?proposal=<number>`

**Comment by husio** [comment]
done
