### ISSUE TITLE
Migration of ChainIDs

### ISSUE THREAD

**Issue by annatorok** [iov-one/weave#1121]
The Chain ID specification was merged in:
https://github.com/ChainAgnostic/CAIPs/pull/9

In order for IOV to use the spec, all existing:
- [x] Ethereum targets need to be converted to [CAIP-3](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-3.md)
- [x] Lisk targets need to be converted to [CAIP-6](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-6.md)
- [x] IOV targets need to be converted to [CAIP-5](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-5.md)

List of networks on production right now:

- "alxchain"
- "ethereum-eip155-1"
- "iov-mainnet"
- "lisk-ed14889723"

According to Simon: This requires a data migration on chain, which could be done together with the new accounts module.

**Comment by husio** [comment]
Is the below conversion correct?

* `alxchain` -> `alxchain`
* `ethereum-eip155-1` -> `eip155:1`
* `iov-mainnet` -> `cosmos:iov-mainnet`
* `lisk-ed14889723` -> `lip9:9ee11e9df416b18b`
