### ISSUE TITLE
Ability to add mappings from IOV addresses to "base rates"

### ISSUE THREAD

**Issue by annatorok** [iov-one/weave#1122]
Goal:
In the term deposit configuration, we want to be able to add mappings from IOV addresses to "base rates" so that validators and brokers can be rewarded for their work.  

The new mappings will work exactly as the bonuses and periods: https://github.com/iov-one/weave/blob/master/cmd/bnscli/clitests/termdeposit_update_configuration.test.  

As a concrete example, for a given validator's IOV address, its base rate will be its q-score.  The base rates need to be mutable and it should be possible to delete an IOV address to base rate mapping. 

This effort is being driven by the desire to provide transparency to the reward distribution to validators, brokers, and depositors.

**Acceptance criteria:**
- [x] update bnscli
- [x] add another attribute to existing termdeposit configuration (we expect less than 100 addresses at any given time)
- [x] include in bnsapi

**Comment by husio** [comment]
done
