### ISSUE TITLE
List all the preregistered domain,owner pairs that exist on the chain

### ISSUE THREAD

**Issue by annatorok** [iov-one/weave#1144]
We need a query like: https://rpc-private-a-vip-mainnet.iov.one/abci_query?path=%22/%22&data=%22_c:cash%22

The query should be in a script that ultimately displays all the pairs in human readable format, not base64.  Pagination is not a concern.

**Comment by husio** [comment]
```sh
$ bnscli query -path "/preregistrationrecords" | jq -r '.[].Value | .domain + "\t" +  .owner'
```
