### ISSUE TITLE
Create endpoint for balances

### ISSUE THREAD

**Issue by annatorok** [iov-one/weave#1162]
We need to include an endpoint for balances.  We want an endpoint that responds with data like from `BNSCLI_TM_ADDR=http://167.172.104.185:31140 bnscli query -path '/wallets' -data C1721181E83376EF978AA4A9A38A5E27C08C7BB2`  eg.
  ```
{
    "Key": "636173683ac1721181e83376ef978aa4a9a38a5e27c08c7bb2",
    "Value": {
      "metadata": {
        "schema": 1
      },
      "coins": [
        {
          "whole": 9773,
          "fractional": 550000000,
          "ticker": "IOV"
        }
      ]
    }
  }
```
The endpoint should be `/cash/balances` and list all balances when no parameter is given and should list a single balance if given an owner parameter in either hex or bech32 format.

**Comment by orkunkl** [comment]
Moved to https://github.com/iov-one/bns/issues/14
