### ISSUE TITLE
Save third party token on register domain message

### ISSUE THREAD

**Issue by orkunkl** [iov-one/weave#1165]
## Expected Behavior

ThirdPartyToken needs to be saved to the domain instance.

## Actual Behavior

> Another comment: I see we can register a "ThirdPartyToken" at account/domain registration, this is nice but it seems it is not possible to retrieve this token yet because it is missing in proto of account and domain. Am I correct or I miss something?

**Comment by davepuchyr** [comment]
@orkunkl , if at all possible, rename the variable to `broker`, because `ThirdPartyToken`, while factually true, doesn't convey the meaning/usage of the variable.  The `broker` needs to be in `account`, too.
