### ISSUE TITLE
Clearing the targets in usernames on transfer

### ISSUE THREAD

**Issue by annatorok** [iov-one/weave#1172]
Problem:
Any associated blockchain addresses will be unlinked before the name is transferred is not working. Addresses was not unlinked after name transfer.

- [x] We need to make sure that we clear the targets in usernames on transfer.

**Comment by fdymylja** [comment]
@annatorok this change will not make it to mainnet since it would cause a consensus bug.

**Comment by orkunkl** [comment]
Closing the issue, you can reopen if necessary
