### ISSUE TITLE
Migrate new chain ids

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/weave#1173]
https://github.com/iov-one/weave/blob/master/cmd/bnsd/app/datamigration.go#L264 only migrates ETH, IOV, and Lisk chain ids.  We need to handle the additional chain ids detailed below.

Blockchain Name | Old Chain-ID | New Chain-ID
-- | -- | --
Binance Chain | cosmos-binance-chain-tigris | cosmos:Binance-Chain-Tigris
Bitcoin Mainnet | bip122-tmp-bitcoin | bip122:000000000019d6689c085ae165831e93
Bitcoin Cash Mainnet | bip122-tmp-bcash | bip122:000000000000000000651ef99cb9fcbe
Cosmos Hub Mainnet | cosmos-cosmoshub-3 | cosmos:cosmoshub-3
Ethereum Mainnet | ethereum-eip155-1 | eip155:1
IOV Mainnet | iov-mainnet | cosmos:iov-mainnet
IrisNet Mainnet | cosmos-irishub | cosmos:irishub
Kava Mainnet | cosmos-kava-2 | cosmos:kava-2
Lisk Mainnet | lisk-ed14889723 | lip9:9ee11e9df416b18b
Litecoin Mainnet | bip122-tmp-litecoin | bip122:12a765e31ffd4059bada1e25190f6e98
Terra Money Mainnet | cosmos-columbus-3 | cosmos:columbus-3
Tezos Mainnet | tezos-tmp-mainnet | tezos:NetXdQprcVkpaWU

Reference: https://internetofvalues.slack.com/archives/GPV56J5NK/p1581951905000500

Part of https://github.com/iov-one/mainnet/issues/75

**Comment by annatorok** [comment]
@fdymylja can we reopen this issue and add a new chain id? 

E-money: cosmos:emoney-1
