### ISSUE TITLE
Enable burn only after migration

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/weave#1175]
Tokens sent to `iov1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvnwh0u` and any balance in that wallet are burned, but the feature should only be enabled after a migration.  

The feature was added in commit https://github.com/iov-one/weave/commit/e311cb37403cb4781c43a0e670f5299ce5a4d1e2.

This issue is related to https://github.com/iov-one/mainnet/issues/78.

**Comment by fdymylja** [comment]
It was decided to revert the burn feature.
