### ISSUE TITLE
Review specification

### ISSUE THREAD

**Issue by annatorok** [iov-one/weave#1187]

**Comment by fdymylja** [comment]
This is the draft of the specification:
There needs to be a look at the new domain registration, especially account renew field which is not checked.
cc @davepuchyr @orkunkl 

# Account module
Prereqs is the set of constraints that each handler has to verify before processing the request. Each constraint is listed in order.

After is the set of actions performed after prereqs is satisfied.
## register domain
 prereqs:
 - `domain.Name` must not exist already.
 - if a domain has not superuser then the authenticator address (I guess signing address) must be the same as `configuration.Owner`
 - `domain.Name` must match the regexp stored in `configuration.ValidDomain`
 
 after:
  - the `Domain` is put inside the KVStore
  - `domain.ValidUntil` becomes `time(CurrentBlock)` + `configuration.DomainRenew` duration
  - `domain.AccountRenew` becomes `request.AccountRenew`, no check is performed on account renew, meaning that if it's empty it's possible to register `Account`s that are already expired.
  - An `Account` associated with the domain is registered with an empty `account.Name` equal to `""`, and `account.AccountRenew` is set as `domain.AccountRenew` duration (if this operation fails the store does not remove the domain)

## transfer domain
prereqs:
- `domain.Name` must exist in the kv store
- `domain.HasSuperuser` == **false** then it cannot be transferred
- signing address must be  `domain.Admin`
- if the domain has expired then it cannot be transferred `time(CurrentBlock)` >= `domain.ValidUntil`

after prereqs:
- change `domain.Admin` to `request.NewAdmin`
- store `Domain`, `domain.ValidUntil` is not updated
- iterate between `Domain` accounts
- reset `account.Certificates` & `account.Targets` for each account found.
- `account.Owner` becomes `request.NewAdmin`, `account.ValidUntil` is not updated.
 
 ## renew domain 
 prereqs:
  - `domain.Name` must exist inside KVStore

after prereqs:
 - `domain.ValidUntil` becomes `time(CurrentBlock)` + `configuration.DomainRenew` Duration
 - if new `domain.ValidUntil` > old `domain.ValidUntil`: `Domain` is updated (no error returned in case this condition is false)
 
## Delete domain
prereqs:
- `domain.Name` must exist
- `domain.HaSuperuser` must be **true**
- only `domain.Admin` can delete the domain

after prereqs:
- `Domain` is deleted
- `Account`s are loaded in batches of 100 elements each and deleted if their `account.Domain` == `domain.Name` to be deleted (if one of these delete ops fails, the op exits, the deleted accounts and domain are not restored)

## Register account
prereqs:
- provided `account.Targets` must be valid
- `domain.Name` must exist
- if `domain.HasSuperuser` == **true** then only the `domain.Admin` can register the `Account`
- else `request.Signer.Address` must be the same as the proposed new `account.Owner`
- `domain.ValidUntil` > `time(CurrentBlock)`
-  `account.Name` must not exist
- `account.Name` must match `configuration.ValidName` regexp

after prereqs:
- `account.ValidUntil` is set to `time(CurrentBlock)` + `domain.AccountRenew`
- a key ID to map `account` in the KVStore is generated using `account.Name`  + `domain.Name`

## transfer account
prereqs:
- `domain.Name` must exist
- `domain.ValidUntil` > `time(CurrentBlock)`
- `account.Name` must exist
- `account.ValidUntil` > `time(CurrentBlock)`
- if` domain.HasSuperUser` == **true** then only `domain.Admin` can transfer an account
- else if` domain.HasSuperUser` == **false** only `account.Owner` can transfer the account
- `account.Name` to transfer must be != to the empty account name `""`

after:
 - `account.Owner` address is replaced with `request.NewOwner`
 - `account.Certificates` are removed (but why not blockchain targets?)
 - `Account` is then updated in the store
 
 ## replace account targets
 prereqs:
  - validate `request.Targets` based on the` configuration.ValidBlockchainID`, `configuration.ValidBlockchainTargets` (considering we updated the new migration of bc addresses this we check if they are compliant with the configuration? although tests pass.)
- `domain.Name` must exist
- `domain.ValidUntil` > `time(CurrentBlock)`
- `account.Name` must exist
- `account.ValidUntil` > `time(CurrentBlock)`
 - `request.Signer.Address` == `account.Owner`
  
 after:
 - `account.Targets` become `request.NewTargets` 
 
 ## delete account
 prereqs:
- `domain.Name` must exist
- `account.Name` cannot be `""`
- `account.Name` must exist
-` account.Owner` can delete the account
- if `domain.HasSuperUser` == **true** then the `domain.Admin` can delete the account (err msg needs to be updated to reflect this spec)

after:
 - `account` is deleted
 
 ## flush domain
 prereqs:
- `domain.Name` must exist
 - only `domain.Admin` can perform this action (err msg needs to be updated)
 
 (inconsistency, `domain.ValidUntil` is not checked)
 
 after:
 - get accounts where `account.Domain` == `domain.Name`
 - all but `""` account are deleted (if one op fails other deleted accounts are not restored)
 
## add account certs
prereqs:
- `domain.Name` must exist
- `domain.ValidUntil` > `time(CurrentBlock)`
- `account.Name` must exist (err msg needs update)
- `account.ValidUntil` > `time(CurrentBlock)`
 - only `account.Owner` can perform this action (not `domain.Admin`)
 - `request.NewCertificate` must not exist in `account.Certificates`
 
 after:
 - `request.NewCertificate` is appended to `account.Certificates`
 
 ## renew account
 prereqs:
- `domain.Name` must exist
- `account.Name` must exist
 
 after:
 - `account.ValidUntil` becomes `time(CurrentBlock)` + `domain.AccountRenew` duration
 
 ## delete account certs
 prereqs:
- `account.Name` must exist
 - only `account.Owner` can perform this action (not `domain.Admin`)
 - `request.Certificate` must exist in `account.Certificates`
 
after:
- account certificate is deleted

**Comment by davepuchyr** [comment]
Closed via https://github.com/iov-one/weave/issues/1189, https://github.com/iov-one/weave/issues/1190, https://github.com/iov-one/weave/issues/1191, and https://github.com/iov-one/weave/issues/1188
