### ISSUE TITLE
Fix renew domain

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/weave#1191]
Domain renewal should be extended from `domain.ValidUntil`, not `now`.  This could lead to multiple extensions of a domain well into the future, which is a desired feature.

**Comment by fdymylja** [comment]
What should we do in case domain.ValidUntil + configuration.DomainRenew <= currentTime?
My idea, in this case, was to leave it as it is and let the domain admin do another  DomainRenew request.

What do you think?
cc @davepuchyr @orkunkl  @annatorok

**Comment by fdymylja** [comment]
Plus, I foresee a consensus bug most likely here, I will test but I'm 99% sure. If there were renewals already then it will not sync.

**Comment by orkunkl** [comment]
> What should we do in case domain.ValidUntil + configuration.DomainRenew <= currentTime?
> My idea, in this case, was to leave it as it is and let the domain admin do another DomainRenew request.
> 
> What do you think?
> cc @davepuchyr @orkunkl @annatorok
```go
return &weave.DeliverResult{Data: nil, Log: fmt.Sprintf("your domain renewal is in the past, renew again blah blah")}, nil
```

**Comment by fdymylja** [comment]
> > What should we do in case domain.ValidUntil + configuration.DomainRenew <= currentTime?
> > My idea, in this case, was to leave it as it is and let the domain admin do another DomainRenew request.
> > What do you think?
> > cc @davepuchyr @orkunkl @annatorok
> 
> ```go
> return &weave.DeliverResult{Data: nil, Log: fmt.Sprintf("your domain renewal is in the past, renew again blah blah")}, nil
> ```
> 
> ?

Actually the renewal time of the domain is not decided by the client who makes the request, it is a default value stored in the state of the blockchain (configuration module). 

So if the configuration is like 1 day. And his domain expired two days ago, if he does a renewal request the expiration time would be yesterday.

So in theory he would need to make a renewal request again to make expiration time today.

**Comment by fdymylja** [comment]
> > What should we do in case domain.ValidUntil + configuration.DomainRenew <= currentTime?
> > My idea, in this case, was to leave it as it is and let the domain admin do another DomainRenew request.
> > What do you think?
> > cc @davepuchyr @orkunkl @annatorok
> 
> ```go
> return &weave.DeliverResult{Data: nil, Log: fmt.Sprintf("your domain renewal is in the past, renew again blah blah")}, nil
> ```
> 
> ?

I'm good with showing this information and letting the user do as many renewals are required to make the domain not expired.

**Comment by fdymylja** [comment]
> Plus, I foresee a consensus bug most likely here, I will test but I'm 99% sure. If there were renewals already then it will not sync.

Synced up to last block, if old nodes will make requests to renew an account then that request will cause a consensus bug with the newest release.

**Comment by davepuchyr** [comment]
Accounts have not been initialized on `mainnet`, so we don't have to worry about consensus errors there.  We'll let our partners know that we're going to reboot `exchangenet` in order to test the latest changes.

**Comment by davepuchyr** [comment]
> What should we do in case domain.ValidUntil + configuration.DomainRenew <= currentTime?
> My idea, in this case, was to leave it as it is and let the domain admin do another DomainRenew request.
> 
> What do you think?
> cc @davepuchyr @orkunkl @annatorok

Let's keep it simple and just use `now` instead of `domain.ValidUntil` and not force repeated renewals until the domain is "current".
