### ISSUE TITLE
Add a grace period to account config

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/weave#1199]
Upon expiration, a domain owner needs to be given a grace period during which time they can be assured that they will not lose the domain.

Acceptance criteria:
- [x] grace period can be set by `bnscli update-account-configuration ...`
- [x] grace period has the same units as `account_renew`
- [x] `bnscli` default grace period is 30 days (2592000 seconds)
- [x] grace period is included in the response to the endpoint `/gconf/account`

**Comment by orkunkl** [comment]
Let's clear the process:
1. Some random guy on internet buys a domain and becomes domain owner.
2. Time passes and the domain expires.
3. Owner is given time to lease the domain again. During this period, domain registration is blocked for this domain
4. Owner tries to renews the domain. If `ValidUntil + GracePeriod` did not pass he will be able to and the new `domain.ValidUntil` = `now + domainRenewDuration`.

But this question came to me: why not just add up `grace_period` to ValidUntil duration and use it that way? What future functionalities are made possible with this implementation?

**Comment by davepuchyr** [comment]
Re 4, replace `register` with `renew` and make `domain.ValidUtil = domain.ValidUtil + domainRenewDuration`.  We don't want people abusing the grace period to effectively get 13 months of domain usage for the price of 12.  We offer the grace period as a courtesy to the owner during which time most operations, such as replace targets, will fail and signal to the owner that a renewal is required.

Re 5, once the grace period is passed then the domain can be deleted by anyone and subsequently registered, even the original owner.

**Comment by orkunkl** [comment]
>  We offer the grace period as a courtesy to the owner during which time most operations, such as replace targets, will fail and signal to the owner that a renewal is required.

So this means we need to implement grace check for every operation run on domain?

**Comment by davepuchyr** [comment]
No, `ValidUntil` is already checked for all the operations.  

The grace period is only relevant for the `deleteDomainHandler.validate` method.  If `now > domain.ValidUntil + conf.GracePeriod` then `h.auth.HasAddress` does not need to contain `domain.Admin` in order for the method to return a `nil` error.  (`now` is the blockchain's now.)
