### ISSUE TITLE
Allow anyone to delete a domain after its grace period has expired

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/weave#1200]
Upon expiration, the only operations allowed on a domain are renew and delete, and delete can only be performed by the domain admin.  Consequently, a domain could be abandoned by its owner never to be used again.  We need to allow anyone to be able to delete a domain after its grace period has expired so that it can be registered to a new owner.

Blocked by https://github.com/iov-one/weave/issues/1199.

**Comment by orkunkl** [comment]
What if there are existing accounts registered under the unleased domain?

**Comment by davepuchyr** [comment]
On delete, all accounts with their targets and certificates are deleted, which is the current behavior of the `deleteDomainHandler` https://github.com/iov-one/weave/blob/master/cmd/bnsd/x/account/handler.go#L427.
