### ISSUE TITLE
Empty account must be renewed upon domain renewal

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/weave#1204]
The empty account ("") is implicitly tied to its domain.  It should be renewed when the domain is renewed.

Acceptance criteria:
- [ ] the empty account's `ValidUntil` should equal the domain's `ValidUntil` on domain renewal

**Comment by orkunkl** [comment]
@davepuchyr I am almost done with implementation. Just a question. Should we refer **empty account** with some other name? Because it sounds confusing.

**Comment by davepuchyr** [comment]
Great that you're so quick!  

There have been so many discussions about terminology that I don't want to open up that can of worms once again.  If you really want to discuss it then let's use Slack.

**Comment by orkunkl** [comment]
>  the empty account's ValidUntil should equal the domain's ValidUntil on domain renewal

```go
	// Registering a domain enforce existence of an account with an empty
	// name.
	account := Account{
		Metadata:   &weave.Metadata{},
		Owner:      msg.Admin,
		Domain:     msg.Domain,
		Name:       "",
		ValidUntil: weave.AsUnixTime(now.Add(domain.AccountRenew.Duration())),
	}
```
As you can see for accounts `AccountRenew` duration is used. Double checking the acceptance criteria.

**Comment by davepuchyr** [comment]
The acceptance criterion is correct.
