### ISSUE TITLE
Bnsd dump state functionality

### ISSUE THREAD

**Issue by orkunkl** [iov-one/weave#1212]
We need to be able to dump existing data from the chain to a JSON file in genesis format.
Current Weave implementation does not support dumping data from a live chain since historical chain data is not served with version. Although dumping is possible via directly accessing kv database. I am thinking to implement a CLI tool that achieves this functionality. 

### Input: 
- bns.db location
- AppHash of the commit
### Output:
- Genesis file. [Reference](http://github.com/iov-one/weave/blob/1fe238372589da1e2ecea1f66da0a01ee7645b3f/cmd/bnsd/app/testdata/fixtures/app.go#L74-L191)
### Modules in the output genesis file:
- username or migrated account data
- wallets
- escrows
- contracts

**Comment by davepuchyr** [comment]
Don't try to produce a complete genesis file.  Just dump the 
- [ ] usernames with targets verbatim
- [ ] wallets
- [ ] escrows
- [ ] multisig contracts.  

We'll use node to do the transformation into a genesis file.  https://github.com/iov-one/weave/issues/1210 is where the list of transformations will accumulate.
