### ISSUE TITLE
Clarify how we add specific nfts

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#144]
Ideally, we can add more nft types without modifying the base nft code. Like, I can import weave, add a new extension and have it work in my app. Maybe using just my nft and not the bns nfts.

Most of the code is generic at this point, but the `RegisterHandlers` in `nft/base` as well as the `Type` in `nft/codec.proto` need to list all nfts that are present. This means, to add or change the nfts, one needs to fork weave.

We should brainstorm on a cleaner way to allow extensibility and make the changes.

This is very important to me, to keep this a clean library, but not urgent, as our focus is on delivering these nft types. This can be done after the base nft implementation is done if there is no simple solution. This issue serves to capture brainstorming right now.

**Comment by ruseinov** [comment]
@ethanfrey I added type as an enum and use it as one because right now in order to add a new nft you need to add a subpackage to weave, so you might as well add a new type.
Is there any other usage of nft planned, that would be "dynamic", sort of?

**Comment by ruseinov** [comment]
Same goes for base handler. If we want to handle "generic" nfts, this would probably mean we'd create a "generic" subpackage and add that "generic" type etc. 

I think it is important that we have a use-case for when we need to extend an approval(nft) type and/or handler without touching weave and how exactly we envision this going forward.

**Comment by ruseinov** [comment]
For the record: the current design is done with an assumption that every nft type is defined via weave/proto. Then adding it where it needs to be added is not an issue.

According to what I understood in our early NFT talks with @alpe @Isabello and @ethanfrey we were not planning any "smart" contracting, but instead were planning to define everything via proto and have a "written in stone" contract. In this case the approach we've taken will shine.

**Comment by ethanfrey** [comment]
The idea is that weave works like a library and you can mix-and-match parts as well as add your own extension to produce your own blockchain. We show a few example apps.

The idea is that say Isabella wants to make a card-trading chain. We will start a new repo and import weave. She can use the `cash`, `escrow`, `hashlock` and `multisig` plugins, to handle payments and maybe even swap cards for cash securely. Now she wants to add a custom nft type.

She writes a new extension module that captures the payload and rules of the `nft/card` type. Now she wants to wire up the handlers and connect it to the app. But, she doesn't even want the username or blockchain nfts.

How does she do this?

Remember, this is a different repo, *importing* weave as a dependency. It should be externally extensible.

**Comment by ruseinov** [comment]
@ethanfrey Now that's a good use-case! I somehow forgot about it as we got rid of bcp :)
Alright, I will see how I can make this work to be reused from another repo right away

**Comment by ethanfrey** [comment]
Only one nft now... bnsd/usernames
