### ISSUE TITLE
Discussion: ID constraints for NFTs

### ISSUE THREAD

**Issue by Isabello** [iov-one/weave#150]
Right now we set constraints on NFT `id`s  being unique. However, this may cause issues in the future given that things like `username` are user specifiable.

We should discussion and decide how to address this issue to allow the system to issue an `id` for a generated NFT. We can create a secondary index on fields like `username` or find a better way to affix a system `id` to NFTs.

**Comment by ethanfrey** [comment]
Obsolete until we revisit nfts
