### ISSUE TITLE
Cache signature verification

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#16]
Before implementing the signature verification cache, please [provide a benchmark that test the current performance](https://github.com/iov-one/weave/pull/942#issue-305482569). Once we know how much time the current solution takes, we will decide if we want to optimize it. (Update: [we have the benchmarks](https://github.com/iov-one/weave/pull/942#issue-305482569)).

---

Most tx will show up in CheckTx and then in DeliverTx.
Since the verification is relatively expensive operation, we can cache the result to avoid doing the work twice.

Idea: 
* cache for height h-1
* cache for height h
* on validate, check if in cache, add result to cache(h)
* on commit, move cache(h) to cache(h-1) and set cache(h) to empty

Simple implementation of LRU

Other approaches are fine, but they:
* should have bounded memory usage (maximum is proportional to max block size)
* in typical cases allow us to avoid verifying the same tx signatures multiple times. This is also important in the case when the tx doesn't fit in block (high load) and is rechecked before proposing to next block. These re-checks shouldn't have to re-verify and thus be very quick.
* doesn't add excess complexity for edge cases. easier to reverify a few transactions than introduce bugs or inefficiencies in the normal flow.

Please run benchmarks before and after this PR to demonstrate differences.

**Comment by husio** [comment]
@kmw101 we have the benchmark results https://github.com/iov-one/weave/pull/942#issue-305482569

**Comment by kmw101** [comment]
The benchmark tests do not conclusively require optimisation. Closing this issue.
