### ISSUE TITLE
Revisit NFT token ids

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#161]
Right now we are still using human-readable ids for tokens.
I'm still not sure what we will go with, but that definitely needs to be decided sooner rather than later.

@Isabello @ethanfrey @alpe

**Comment by ethanfrey** [comment]
I like it. If there is an immutable natural key use it...

TokenTicker as id for TokenNFT
Username for UsernameNFT
etc.

For eg. BootstrapNodes I think there is no natural key and using a random uuid is a good idea

**Comment by ethanfrey** [comment]
obsolete until we revisit nfts
