### ISSUE TITLE
Implement unidirectional payment channel: channel creation

### ISSUE THREAD

**Issue by husio** [iov-one/weave#164]
_This task was initially described in https://github.com/iov-one/bcp-demo/issues/22_

Complete scenario: [Alice wants to pay Bob for tweets where both sides have low risk of loosing money](https://medium.com/@matthewdif/ethereum-payment-channel-in-50-lines-of-code-a94fad2704bc).

This issues describes unidirectional payment channel creation. All other operations are implemented as separate issues (see [transfer](https://github.com/iov-one/weave/issues/165) and [closing](https://github.com/iov-one/weave/issues/166)).

Payment channel creation message:

```protobuf
message CreatePaymentChannelMsg { 
    bytes sender = 1;
    bytes recipient = 2;
    // Maximum amount that can be transferred via this channel.
    x.Coin total = 3;
    // Absolute block height value. If reached, channel can be closed by
    // anyone.
    int64 timeout = 4;
    // Max length 128 character.
    string memo = 5;
}

```

Payment channel can be created only between two parties (single sender and single recipient).

Creation message does not define an arbiter. It is irrelevant for both `sender` and `recipient` who the arbiter is. It can be decided by the system to use any trusted account. 

`sender` can be empty and defaults to the main signer.

`timeout` is the stack height. If reached, anyone is allowed to close the payment channel. Timeout is protection from deadlock when Bob does not want to claim value represented by the channel. To make the implementation easier, there is no action triggered when timeout is reached. Instead anyone is allowed to close timed out channel.

When a creation message is accepted, state change is applied

```protobuf
message PaymentChannel {
    bytes sender = 1;
    bytes recipient = 2;
    x.Coin total = 3;
    // Absolute block height value. If reached, channel can be closed by
    // anyone.
    int64 timeout = 4;
    // Max length 128 character.
    string memo = 5;
    x.Coin transferred = 6;
}  
```

`transferred` is used to keep track of payment channel value. It must not exceed `total`. When `transferred` reach `total` value, channel can be closed (all allocated money was transferred to `recipient`).

**Comment by alpe** [comment]
q: Is ` x.Coin amount = 4;` in `PaymentChannel ` the remaining amount?

**Comment by husio** [comment]
@alpe 

> q: Is x.Coin amount = 4; in PaymentChannel the remaining amount?

No. `amount` is the total value that can be transferred via payment channel. `transferred` is tracking what has been moved so far. Remaining value is `amount - transfrerred`.

**Comment by ethanfrey** [comment]
Nice write-up. And thanks for this initiative.

Some minor feedback:

>     // Sender, Recipient are all weave.Permission.
Actually, they should be weave.Address. We try to avoid exposing weave.Permission in the messages unless we really need to display the type to the client (eg. escrow arbiter). Client side, it is much easier to handler the Address for an account than the Permission.

> message PaymentChannel {
>    bytes arbiter = 2;

I think we need no arbiter here, we replace that part of escrow with the logic that evaluates the submitted messages. I guess we could try to reuse escrow identically and consider payment channels a smart contract arbiter, but that is a level of complexity we don't current support in weave and may not want to.

>     x.Count transferred = 7;

You mean `x.Coin`, right?

**Comment by ethanfrey** [comment]
> We need a trusted account to hold the founds allocated for the payment channel. Address of such account can be determined by the system. I can remove arbiter field and instead use the channel ID to create a unique address that will be used to safe-keep the coins.

Yes, as in escrow, the arbiter never has access to the funds. They are transferred to an address that belongs to that particular escrow instance. The same can be done here.

I made an address for the "Condition" of the escrowId:
https://github.com/iov-one/weave/blob/master/x/escrow/controller.go#L43

Condition is a simple construct of module name, type (anything here), and the channel_id. Module name and channel id is enough to guarantee no one else can generate the same address:
https://github.com/iov-one/weave/blob/master/x/escrow/model.go#L84-L88

**Comment by ethanfrey** [comment]
Please try this, and then if you feel there is some error in the design, let me know.
