### ISSUE TITLE
 Implement unidirectional payment channel: transfer

### ISSUE THREAD

**Issue by husio** [iov-one/weave#165]
_This task was initially described in https://github.com/iov-one/bcp-demo/issues/22_

Complete scenario: [Alice wants to pay Bob for tweets where both sides have low risk of loosing money](https://medium.com/@matthewdif/ethereum-payment-channel-in-50-lines-of-code-a94fad2704bc).

This issues describes transferring value send through an unidirectional payment channel. All other operations are implemented as separate issues (see [creation](https://github.com/iov-one/weave/issues/164) and [closing](https://github.com/iov-one/weave/issues/166)).

Message to transfer the value send by the channel:
```protobuf
message TransferPaymentChannelMsg {
    bytes channel_id = 1;
    x.Coin amount = 2;
    // Max length 128 character.
    string memo = 3;
}
```

Creator of the payment channel (Alice) creates `TransferPaymentChannelMsg`, signs it and sends to the `recipient` (Bob). `recipient` can redeem represented amount at any time by sending the message to the system.

`TrasnferPaymentChannelMsg.amount` must not be greater than payment channels `total` value.

Redeeming distributes coins by writing a transaction to the blockchain. Redeeming a transfer does not close a channel. 
Redeeming a value that is not higher than the last redeemed payment result in an error.

Redeeming a value that is equal to `total` value represented by a payment channel is a good trigger for closing a channel. No other operation can be executed on it.
```
State: total: 10, transferred: 0  -> Redeem 2 : OK
State: total: 10, transferred: 2  -> Redeem 3 : OK
State: total: 10, transferred: 3  -> Redeem 1 : Error
State: total: 10, transferred: 3  -> Redeem 10: OK, close channel.
```

**Comment by alpe** [comment]
We need to prevent sending the message twice. Either the increment amount is always reflecting the total amount spent: value would be 6BTC when sending 2BTC and coming from 4BTC. 
Or we add a sequence number that must be incremented. Other ideas?

Both scenarios require some additional state stored in `PaymentChannel`.  
With incrementing amounts we need to track what we have spent already for the delta and that a resubmission can be rejected when: amount <= used amount

Storing a sequence number is a more complex scenario as we need to prevent the sender to submit a new TX where he bumps the version with a low amount and locks out previous Tx.

**Comment by alpe** [comment]
sorry, missed the `    x.Count transferred = 7;` in `PaymentChannel`. That is option A and makes sense.
pp: we could have a `memo` field here too, to let the sender submit some details with this operation.

**Comment by ethanfrey** [comment]
Yes, the use of transferred is very useful, and I like how this keeps track. Nice design.

One issue is what exactly is signed. Normally we have

`sign (tx(msg, fees, etc) || chainId || nonce, privateKey)` and that is what is evaluated by the middleware.

If I, Alice, sign such a full transaction and give it to you, even with a valid nonce, I can just send a different tx to someone else and invalidate the tx, rendering the payment channel insecure.

what we need is an "inner message" and a "signed message". The signed message should be unforgeable but also unexpireable.

`TransferPaymentChannelMsg` is basically the inner message, but we might want to add the chainId as a string field to add a bit more security against cross-chain replays.

`SignedTransferPaymentChannelMsg` is what needs to be included in the transaction, and is the one that needs to implement the `Msg` interface and be registered in the `tx codec`. Something like:

```
message SignedTransferPaymentChannelMsg {
    TransferPaymentChannelMsg payment = 1;
    crypto.PublicKey pubkey = 2;
    crypto.Signature signature = 3;
}
```

Where signature is a valid signature of the serialized `payment` field with the corresponding private key.

Note that pubkey will be the same in every message and must match the specified in the creation. Maybe it makes sense just to specify the pubkey there, which allows us to use temporary key pairs to release the payment channel, not the keypair that controls all of the account. Making it easier to give an app use of a payment channel, without granting your entire account.

**Comment by husio** [comment]
https://github.com/iov-one/weave/pull/167
