### ISSUE TITLE
 Implement unidirectional payment channel: close

### ISSUE THREAD

**Issue by husio** [iov-one/weave#166]
_This task was initially described in https://github.com/iov-one/bcp-demo/issues/22_

Complete scenario: [Alice wants to pay Bob for tweets where both sides have low risk of loosing money](https://medium.com/@matthewdif/ethereum-payment-channel-in-50-lines-of-code-a94fad2704bc).

This issues describes closing a payment channel. All other operations are implemented as separate issues (see [creation](https://github.com/iov-one/weave/issues/164) and [transfer](https://github.com/iov-one/weave/issues/165)).

Message to close a payment channel:

```protobuf
message ClosePaymentChannelMsg {
    bytes channel_id = 1;
    // Max length 128 character.
    string memo = 2;
}
```

Payment channels `recipient` can close a channel at any time.

If payment channels `timeout` value was reached, `sender` can close the channel.

When payment channel is closed, remaining allocated value (`total` - `transferred`) is being send back to the `sender`.

Closed payment channel is deleted and no other operation can be performed.

**Comment by alpe** [comment]
pp: we could have a memo field here too, to let the recipient submit some details with this operation.

**Comment by ethanfrey** [comment]
Looks good to me.

**Comment by husio** [comment]
https://github.com/iov-one/weave/pull/167
