### ISSUE TITLE
duplicated sequence prefix

### ISSUE THREAD

**Issue by husio** [iov-one/weave#168]
`Sequence` is generating keys with duplicated prefix.

When [creating a new sequence](https://github.com/iov-one/weave/blob/3b7376feba386a20c4c4e9411dee4fdfa2becc7f/orm/sequence.go#L24), sequence ID is prefixed with `seqPrefix`. When building a key for [reading a sequence state](https://github.com/iov-one/weave/blob/3b7376feba386a20c4c4e9411dee4fdfa2becc7f/orm/sequence.go#L41), sequence ID is additionally prefixed with `seqPrefix`.

Expected sequence state key is in format ` _s.<bucket>:<name>`. Current implementation is using `
 _s._s.<bucket>:<name>`

**Comment by ethanfrey** [comment]
Good call. I think I moved the append to the constructor to save some allocs later on, but forgot to change it.

In `curVal`, you can just use `key := s.id` (or just replace it with `s.id`) and avoid the append call.
https://github.com/iov-one/weave/blob/3b7376feba386a20c4c4e9411dee4fdfa2becc7f/orm/sequence.go#L41
