### ISSUE TITLE
Use bech32 for address encoding format

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#180]
While addresses are handled as 20 byte binary objects internally, we currently use a hex-encoding for them to display to users and parse input.
https://github.com/iov-one/weave/blob/master/conditions.go#L87-L107

We have updated the client side library in iov-core to use bech32 encoding, with `{iov,tiov}` prefix.

This make a bit of issues when feeding addresses from clients to the genesis file, and similar issues. And it would be nicer to standardize.

Since we need to declare an output prefix for serialization (and ensure it in parsing), we will likely need a global (module-wide) variable to hold this, set up in app initialization. So `iov, tiov, or other`. This should be configurable from genesis, ideally building on #202

cosmos-sdk uses this bech32 lib https://github.com/btcsuite/btcutil/tree/master/bech32
we can use it, extract it, or find another one

**Comment by webmaster128** [comment]
I'd prefer to improve our tooling for hex <-> bech32 conversion. There are make cases, especiall in the low level code where the overall context (what chain we are on) is not available. Using hex has the advantage that we encode exactly the data we need instead of throwing away unused prefixes or adding dummy prefixes.

**Comment by ethanfrey** [comment]
@webmaster128 can you make a clear proposal for this?

A cli script as part of iov-core?
A golang script?
Other idea?

**Comment by webmaster128** [comment]
A static website that works like https://www.unixtimestamp.com/ but with two way data binding instead of buttons. Decoded and encode happen for every change to the hex address input field or bech32 address input field.

**Comment by husio** [comment]
I was trying to implement it using https://github.com/btcsuite/btcutil/tree/master/bech32 but it seems like this library produce invalid encoding.

I have also tried their encode/decode example using https://github.com/nym-zone/bech32 tool and outputs are different.

https://github.com/iov-one/weave/commit/2f780e512c5c632e91da4af4188ef5ba5eb74000

**Comment by husio** [comment]
@webmaster128 I am not using ltcutil. That makes at least 2 out of those 3 serializes broken.

I think if we want to proceed with this story, we must first find reliable implementation that we could use as a reference.

**Comment by webmaster128** [comment]
@husio no? But you linked a commit that imports "github.com/ltcsuite/ltcutil/bech32"

**Comment by husio** [comment]
Great catch! I was indenting to use https://github.com/btcsuite/btcutil/ and goimport must have rewrote it.

**Comment by ethanfrey** [comment]
Okay, this is not urgent, and if there are no good golang libraries, I am happy to put this one hold.

**Comment by ethanfrey** [comment]
Closing in favor of https://github.com/iov-one/iov-core/issues/602
