### ISSUE TITLE
Fix Blockchain regexp

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#181]
Escape dot in regexp to allow dots in the name not every character:
https://github.com/iov-one/weave/blob/master/x/nft/blockchain/msg.go#L19

**Comment by ethanfrey** [comment]
Actually it is worse... this is an invalid expression, not sure where it came from.

We have been using `^[a-zA-Z0-9_\-]{6,20}$` for all the other tests in the system : https://github.com/iov-one/weave/blob/master/context.go#L49 

It is essential that we support `-` for the tendermint generated chain ids. You can also add `\.` if you wish and adjust allowed length. But please make sure they are compatible (eg. all valid weave chainIds are also valid chainIds for NFTs).

**Comment by webmaster128** [comment]
Inside a character class (between `[` and `]`) `.` is treated as a literal dot. Only outside it means any character. Confirm the pattern `^[a-z.]+$` vs. `^[a-z]+.+$`  for "hello123" via https://regex-golang.appspot.com/assets/html/index.html.

So the initial bug report is invalid. Still the expression has issues.

Additional request: allow up to 64 characters [to allow Lisk/RISE nethashs to work as chain ID](https://github.com/iov-one/iov-core/blob/v0.8.1/packages/iov-rise/src/riseconnection.spec.ts#L11).
