### ISSUE TITLE
Fix CI tests for go tip

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#186]
Follow-up from #185

They are temporarily disabled. We need to fix the tests so they work, then can re-enable. But no need to block all development on this, as we use go1.10 for all production, and that is working.

**Comment by alpe** [comment]
Go tip vesion on travisCI is 
`go version devel +0a72e8eefb Wed Nov 14 14:45:03 2018 +0000 linux/amd64`

**Comment by ethanfrey** [comment]
It's been fixed for a while... also v1.12
