### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#189]
We need to step up our documentation game as we're missing a lot of docs for some of the new extensions, like nft and others.

Need to revisit this, come up with a todo list and knock this out as this is crucial for adoption of the framework

@alpe @ethanfrey @husio @lehajam FYI

**Comment by alpe** [comment]
Can we refine this into actionable tasks?
For example we added functionality for payment channels and the base NFT type to weave. We also have a number of custom NFT types like username, blockchain, etc in early stage.
We can always improve docs and should probably include this into our main stories in the future.

**Comment by ruseinov** [comment]
@alpe we have to refine this yes, but for that one needs to sit down what we do and don't have.
This is a placeholder ticket after a conversation with @ethanfrey who raised a fair point that it's almost impossible to figure anything out in our new undocumented modules without diving deep, especially if you are trying to integrate frontend and not a go dev

**Comment by ethanfrey** [comment]
One clear actionable item is #187 for generating the various messages.

If comments in protobuf files (which also turn into go comment) could lead to docs, that would be very nice.

**Comment by ethanfrey** [comment]
Vague issue. I am tackling this piece by piece. 

Always happy for help
