### ISSUE TITLE
Change pair separator from * to something else

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#196]
When trying to implement the (chain, address) query from https://github.com/iov-one/weave/blob/v0.9.2/x/nft/username/handler_test.go#L209, I got very confused by the * notation to separate the two values. This is because we use * a separator in human randable names and I tried hard to find the connection between the examples I saw and human readable names.

It tuned out this is not human readable at all and one example data would be

```
6076671634347365051L*da3ed6a45429278bac2666961289ca17ad86595d33b31037615d4b8e8f158bba
```

for address 6076671634347365051L on Lisk testnet.

To indicate this is nothing more than a pair separator, we should use something technical that does not look like BNS names.

Requirements:
* Should be in the [printable ASCII range](https://en.wikipedia.org/wiki/ASCII#Character_set)
* Should not be part of chainIDs (https://github.com/iov-one/weave/pull/194/files#diff-9c0bbffd2a96031ea51bc2a9b831d52dR19)
* Should not be part of address shemes

Excluded by the above requirements: `a-zA-Z0-9_-.`
Possible separators e.g. `,;:|/^#SP`
Suggested separator: `;`

**Comment by ruseinov** [comment]
cc @Isabello as I think we also had this specified in bns-spec as `*`

**Comment by Isabello** [comment]
This is something @ethanfrey and I discussed quite a bit. This is up for change if its causing issues.

**Comment by Isabello** [comment]
One thing to note is that we should probably move to use the `name` found in the blockchainNFT

```
blockchainNft: {
  chain: {
    chainId: "da3ed6a45429278bac2666961289ca17ad86595d33b31037615d4b8e8f158bba",
    networkId: null,
    name: "Lisk-Testnet",
    enabled: true,
    production: false,
    mainTickerId: "LSK",
  }
  iov: {...}
}
```

**Comment by webmaster128** [comment]
Are those (chain, address) pairs supposed to be displayed anywhere?
