### ISSUE TITLE
Introduce a way to initialise extension configuration params from genesis

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#202]
We have a bunch of extensions that define configuration params as constants, for example:
MaxBatchSize for batch transactions
updateApprovalCost for nft approvals

We need to be able to define these params in genesis, falling back to defaults when not defined.

Similar functionality to that of `weave.Initializer`, but this needs to happen before the app is initialised, so that we can access params within any extension through app.go.

There are a couple ways to introduce this that I can think of now:
1. Introduce a helper that would parse genesis files and allow to pass these params within `app.go` to appropriate extensions components
2. Introduce a global registry which every extension could use, sort of a singleton, similar to `nft.BucketDispatcher`, then we could have something like `getRegistry(extensionName).getIntOrElse(defaultConst)` or similar to work with it. The important bit here is to make sure this is being initialised before any extensions. 

**Update** Please read all comments to understand this story
We **can** use Initializer pattern
> I would propose a pattern (and helper code), so we can read values in from the genesis file and store them as some sort of singletons, much like the option #2 you propose. (This must be in the kvstore, as on restart, we never see the genesis file again). Design of this should be discussed before starting code.
> It could be one global singleton accessed by each module. Or each module could have it's own singleton dictionary that is backed by the kvstore and cached for frequent reads.

**Comment by ethanfrey** [comment]
> Similar functionality to that of weave.Initializer, but this needs to happen before the app is initialised, so that we can access params within any extension through app.go.

I don't see why this needs to happen before initialization. We don't execute any code until properly initialized.

I would propose a pattern (and helper code), so we can read values in from the genesis file and store them as some sort of singletons, much like the option #2 you propose. (This must be in the kvstore, as on restart, we never see the genesis file again). Design of this should be discussed before starting code.

Also, it would be interesting to consider organizing them in a way, such that one could later add a transaction that would modify such configuration (eg. allowing a governance vote to modify the max batch size, without changing batch logic at all).

**Comment by ruseinov** [comment]
@ethanfrey so the first approach dictates that we have access to variables within app.go when initialising things in router etc, hence the requirement.

For sure we have to go with number 2 option, a thread-safe singleton which could be updated and backend by kvstore.

**Comment by ruseinov** [comment]
I do have a solution in mind for this, should be fairly straightforward and then we can avoid passing these params from `app.go`, but instead access from extensions directly.

**Comment by ethanfrey** [comment]
> I do have a solution in mind for this, should be fairly straightforward and then we can avoid passing these params from app.go, but instead access from extensions directly.

Yeah, if we init in genesis, we don't need to pass in from `app.go`, and can just read it there

**Comment by ethanfrey** [comment]
> For sure we have to go with number 2 option, a thread-safe singleton which could be updated and backed by kvstore.

I think thread-safe is not so required as every access is serialized already by the blockchain. But yes, in general I agree with this idea.

It could be one global singleton accessed by each module. Or each module could have it's own singleton dictionary that is backed by the kvstore and cached for frequent reads.

**Comment by husio** [comment]
If I understand correctly, requirements are:
- An API that will allow to read a configuration value and provide a default value if configuration does not exist. For example, `x/payment` handler needs `createPaymentChannelCost`. Instead of using a constant, code could look like this: `cost, err := Configuration("create_payment_channel_cost", 300)`
- Configuration must be stored on the blockchain, so that it is consistent between transactions. This makes default values harder to implement
- It must be possible to update configuration

My naive solution would be to create a key-value store (`string => []byte`) that will represent all configuration entries. Almost exactly what `Bucket` is today. State is synchronized with the database. Each modification must be done via a transaction submission. 
Interface used in each module to interact with such store would be a `io.Reader` interface.

I would document the convention of how names are created and what values should be stored. For example
> - create names using snake case and follow the pattern `<extension>.<name>`
> - values should be serialized to JSON
> - do not store values larger than 0.1MB

Default values are a bit problematic, because each value must be committed first. Consider previous example code `cost, err := Configuration("create_payment_channel_cost", 300)`. If `create_payment_channel_cost` does not exist, value 300 must be first submitted as a transaction and returned only when accepted. I believe this is not possible, because we cannot submit a transaction while processing another one. Any suggestions how to solve this issue?

**Comment by ethanfrey** [comment]
> An API that will allow to read a configuration value and provide a default value if configuration does not exist. For example, x/payment handler needs createPaymentChannelCost. Instead of using a constant, code could look like this: cost, err := Configuration("create_payment_channel_cost", 300)

Roughly, yes. I might say `cost, err := Configuration.GetInt(store, "create_payment_channel_cost")` but yeah, let's work to refine this design.

>  Interface used in each module to interact with such store would be a io.Reader interface. ???

I think the `Bucket` or `KVStore` interfaces would be more appropriate. Why propose
```go
type Reader interface {
        Read(p []byte) (n int, err error)
}
```

> Default values are a bit problematic, because each value must be committed first. 

Actually, this should all be handled by the Initializer, which can write to the db.
Defaults are provided when reading from genesis, not from the code (only from db state).

If you add a new value to configuration after genesis, this is a good question, not sure best behavior then. You can write to any bucket in the db in any transaction.

**Comment by husio** [comment]
After writing an example code (see below), I have realized that implementing `io.Reader` does not help much. Instead, a different but also a simple interface is more useful:

```go
// Naming is hard XD                                                           
type Propertor struct {                                                        
        Property(name string) ([]byte, error)                                  
}                                                                                                                                                    
                                                                               
// Int returns integer value of given property. Default value is returned if   
// configuration does not exist or cannot be deserialized.                     
func Int(confStore Propertor, propName string, default int) int {              
    raw, err := confStore.Property(propName)                                   
    if err != nil {                                                            
        log.Printf("configuration for %q cannot be fetched: %s", propName, err)
        return default                                                         
    }                                                                          
    var value int                                                              
    if err := json.Unmarshal(confStore.Property(propName), &value); err != nil {
        log.Printf("configuration for %q cannot be deserialized: %s", propName, err)
        return default                                                         
    }                                                                          
    return value                                                               
}                                                                              
                                                                               
// Str returns string value of given property. Default value is returned if    
// configuration does not exist or cannot be deserialized.                     
func Str(confStore Propertor, propName string, default string) string {        
    raw, err := confStore.Property(propName)                                   
    if err != nil {                                                            
        log.Printf("configuration for %q cannot be fetched: %s", propName, err)
        return default                                                         
    }                                                                          
    var value string                                                           
    if err := json.Unmarshal(confStore.Property(propName), &value); err != nil {
        log.Printf("configuration for %q cannot be deserialized: %s", propName, err)
        return default                                                         
    }                                                                          
    return value                                                               
}                                                                              
```
I am not sure about the error handing, so take the above as a possible solution, not something I suggest doing.
I am not convinced that allowing defaults is the right thing to do as well. It would be much easier if the configuration was always present.

**Comment by ruseinov** [comment]
I don’t see the reason why methods checking type should be receiving all the store params and repeating code. Instead you can have a generic get and then something like package.Int(valueYouGot) . Take a look at some libraries implementing redis protocol, for example.

**Comment by ruseinov** [comment]
@husio allowing defaults is essential for minimal configuration to work and introduction of new features without breaking backward-compatibility with older configs.

**Comment by ruseinov** [comment]
also arguably Getter.Get is a bit weird, I would propose a Value interface instead, Value.Get seems more appropriate.

**Comment by ethanfrey** [comment]
> @husio allowing defaults is essential for minimal configuration to work and introduction of new features without breaking backward-compatibility with older configs.

@alpe had a good point that when all defaults/config is in the database, then it is easier to upgrade.

If we don't set a value, then v1.7 of the software adds a config option with default 30. Later, in v2.5, we change the default to 100. Now, when I replay all blocks (sync a new node) with v2.5, it will produce different state than if I synced with v1.7. 

I think the handling of defaults needs to be thought through very well.

**Comment by ethanfrey** [comment]
> also arguably Getter.Get is a bit weird, I would propose a Value interface instead, Value.Get seems more appropriate.

I thought that was standard naming of golang interfaces. But yes, I would not name the variable Getter. Naming here doesn't seem bad. 

(Maybe you prefer value not confStore for the variable name? I have no opinion on that point)

```golang
func Str(confStore Getter, propName string, fallback string) string {
    raw := confStore.Get([]byte(propName))
```

**Comment by ethanfrey** [comment]
Also, I think the API looks nice as it is...
If avoiding duplicate code is the goal, it could be an internal helper:

```
func Int(confStore Getter, propName string, fallback int) int {
    raw := confStore.Get([]byte(propName))
    value := fallback
    parseInto(raw, &value)
    return value;
}

func parseInto(raw []byte, value interface{}) {
    if raw == nil {
        log.Printf("configuration for %q cannot be fetched: %s", propName, err)
    } else if err := json.Unmarshal(raw, value); err != nil {
        log.Printf("configuration for %q cannot be deserialized: %s", propName, err)
    } 
}
```

**Comment by husio** [comment]
>  @alpe had a good point that when all defaults/config is in the database, then it is easier to upgrade.

If presence of a configuration in the database (aka. defaults) can be enforced, than in my opinion this is the best solution. That would remove any default/fallback value from the code.

**Comment by ruseinov** [comment]
@ethanfrey I was talking about interface name, but this is a matter of personal preference. 

Does not change my opinion on func like Int(), String() etc. I think it does make sense to have a generic function that gets the value and receives underlying store param and we can use something like this https://godoc.org/github.com/gomodule/redigo/redis#hdr-Reply_Helpers to deal with replies. 

Up to you guys, it's just how I would implement this. 

About defaults being in the db - it's also a matter of preference, since we have the ability to override these defaults via config - why bother having them in the db? To me a constant for default value is fine. And you can always override via db as this is where the values from config are going to be stored, in case you need to "upgrade".
