### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by husio** [iov-one/weave#203]
Current error handling is build around providing a stack trace. Each package   
declares upfront a set of functions that cover all error situations and call   
them upon error occurrence.                                                    
                                                                               
To introduce an error (i.e. insufficient funds), several lines of code must be 
written:                                                                       
                                                                               
- claim and declare a unique, numeric code                                     
  https://github.com/iov-one/weave/blob/master/x/cash/errors.go#L15            
- declare a string error value that will be the core of an error               
  https://github.com/iov-one/weave/blob/master/x/cash/errors.go#L23            
- declare a function to create an error instance. This wraps a global (root)   
  string error with a stack trace information                                  
  https://github.com/iov-one/weave/blob/master/x/cash/errors.go#L37-L39        
  Sometimes, additional string _label_ is added (i.e.                          
  https://github.com/iov-one/weave/blob/master/x/cash/errors.go#L52)           
- declare a comparison function, so that error kind can be tested              
  https://github.com/iov-one/weave/blob/master/x/cash/errors.go#L40-L42        
                                                                               
It seems that no one is testing errors for their kind.                         
```bash                                                                        
$ find . -name '*.go' | grep -v '_test.go' | grep -v 'tendermint' | xargs grep 'Is.*Err(' -Hn | grep -v 'func '
 ./cmd/bnsd/client/client.go:164:        if resp.IsErr() {                     
 ./cmd/bnsd/client/client.go:204:        if b.Response.CheckTx.IsErr() {       
 ./cmd/bnsd/client/client.go:208:        if b.Response.DeliverTx.IsErr() {     
 ./x/escrow/errors.go:64:        return errors.IsUnrecognizedConditionErr(err) 
$ find . -name '*.go' | grep -v 'tendermint' | xargs grep 'Is.*Err(' -Hn | grep -v 'func ' | wc -l
24                                                                             
```                                                                            
                                                                               
I would like to propose creation of a custom errors package, similar in spirit 
to what was [created in the `upspin`                                           
project](https://commandcenter.blogspot.com/2017/12/error-handling-in-upspin.html).
I believe that we could benefit from this change in several ways:              
- no need to declare errors upfront,                                           
- we no longer do naked error returns. We always handle an error, even if it   
  means we wrap it with more context before returning,                         
- we no longer have to rely on stack traces. Instead of execution trace we have
  helpful code path description,                                               
- we can continue comparing errors (if only for tests),                        
- we can update functionality as we see repeating patterns in the project,     
                                                                               
If accepted, I can prepare a code example that will show better direction of   
changes that I have in mind.             

---

:calendar:  [Meeting scheduled in the calendar](https://calendar.google.com/calendar/r/eventedit/MHRzMXBnY3BiZnF1c200b2Y2MzBqbTBjdnMgb25kemEuY29tX21kNWU1MGlrYzRycml0dGRvdXN2NjNkbTlrQGc)

**Comment by ruseinov** [comment]
@husio these abci (integer) codes are needed for communication to the client, they are passed through tendermint, so you can't see the checks in weave code, but they are actually used on the client-side.

There is a reason each extension reserves a number of codes and returns them.

**Comment by husio** [comment]
Number codes are a good idea and they could be easily preserved. Upspin project describes the same way of distinguishing errors and mapping it between interfaces.

**Comment by ruseinov** [comment]
Please take a look at `type TMError interface`, how it is used, and why.
Then you can come up with a concrete proposal with some example code that shows the benefits of the approach.

I would be glad to see our clunky error definitions go, but since we will still need the error messages, error codes and mapping between them  and also the conversion of that to tmError - I'm not sure the code is going to end up looking much nicer.
The current approach takes time to implement, but it's very verbose which is a good thing.

So what I'm saying is: if we can significantly gain implementation-wise and lose no readability - fine. If there are no significant gains - I'd leave it be instead of refactoring the whole framework.

**Comment by husio** [comment]
Here is an example implementation of the core idea: https://github.com/iov-one/weave/commit/d14e6516286f74dad1df62ec81d8ba3dd667ffe2 :construction: 

 Please keep in mind that this is nor a working example, neither a clean code. This is a big change and implementing it fully will require a good planning and a lot of code changes.

I have borrowed many ideas from the upspin project. Although I am convinced this is a great implementation, to be able to truly evaluate it, I would have to use it. Some highlights:
- there's only one [ function - `E` for creating an error](https://github.com/iov-one/weave/commit/d14e6516286f74dad1df62ec81d8ba3dd667ffe2#diff-67bcaf0cce945ce4f52191db72018763R17). It rely on arguments types to build error with the right attributes,
- [`TMError` interface](https://github.com/iov-one/weave/commit/d14e6516286f74dad1df62ec81d8ba3dd667ffe2#diff-67bcaf0cce945ce4f52191db72018763R63) is implemented by `errors.Error`,
- [module errors declarations are gone](https://github.com/iov-one/weave/blob/d14e6516286f74dad1df62ec81d8ba3dd667ffe2/x/paychan/errors.go) and only error codes remain. I think that maybe the way that error codes are defined might be done better,

**Comment by alpe** [comment]
I like the idea. With this approach we can reduce the overhead of creating new error types a lot (just define a new ID) but also communicate finer grained details via labels model.
With our current approach we have the type guarantee that we won't return a different error text for the same error code. We would loose this guarantee in favour of flexibility. This benefits us on the server side. But I don't know how the clients/ consumers of these errors would like it. Let's find out first.

**Comment by ruseinov** [comment]
@alpe I think the above guarantee point can be easily overcome by a factory method and defining a list of objects like `[{errCode, errMessage}]`

**Comment by ruseinov** [comment]
One more thing - that "only one function" has to go for sure, I definitely don't like the idea of using a vararg with interface{} receiver and a type switch inside.

If we want to use some helpers - fine, but I think we should define a function each for that or use something like `E(specialErrStruct{code, message})` or something. I think the idea of losing type-safety over convenience is a bad one, as this basically makes a simple case of error handling unreliable.

**Comment by ruseinov** [comment]
So I'd say the way it should look is:
const (
err codes
)

map[code]string = {code1: "errString"}

then we'll need to register these maps for each module to have our error handling code automatically take care of texts.

and then we can use a helper, something like ```E(code, vararg of whatever)```

**Comment by ethanfrey** [comment]
Current example from `errors/common.go`:

```
const (
	CodeUnknownRequest             = 4
	CodeUnrecognizedAddress        = 5
)

var (
	errUnknownTxType         = stderrors.New("Tx type unknown")
	errUnrecognizedAddress   = stderrors.New("Unrecognized Address")
)

func ErrUnknownTxType(tx interface{}) error {
	msg := fmt.Sprintf("%T", tx)
	return WithLog(msg, errUnknownTxType, CodeUnknownRequest)
}
func ErrUnrecognizedAddress(addr []byte) error {
	msg := "(nil)"
	if len(addr) > 0 {
		msg = fmt.Sprintf("%X", addr)
	}
	return WithLog(msg, errUnrecognizedAddress, CodeUnrecognizedAddress)
}

func IsUnknownTxTypeErr(err error) bool {
	return IsSameError(errUnknownTxType, err)
}
func IsUnrecognizedAddressErr(err error) bool {
	return IsSameError(errUnrecognizedAddress, err)
}
```


```

**Comment by ethanfrey** [comment]
If we remove `CodeXYZ` and static `err...` and the `Is...Err` functions, we don't really use, we could simplify this...

 ```golang
func ErrUnknownTxType(tx interface{}) error {
	msg := fmt.Sprintf("Tx type unknown: %T", tx)
	return New(msg, 4)
}
func ErrUnrecognizedAddress(addr []byte) error {
	msg := "Unrecognized Address: (nil)"
	if len(addr) > 0 {
		msg = fmt.Sprintf("Unrecognized Address: %X", addr)
	}
	return New(msg, 5)
}
```

The top function could be collapsed into one line, and just called in-place when the error is reported.

**Comment by ruseinov** [comment]
something to look at https://godoc.org/go.uber.org/zap

**Comment by ruseinov** [comment]
@ethanfrey oops, indeed I forgot that I used zap for logging. In any case the cool thing about it is that you can do something like `logger.Log("something went wrong", log.Error(err), log.Int64(id))` etc.

@husio @alpe  I think it's important that we understand whether we want that kind of functionality for errors too. That would, for example, allow us to create a custom serialiser later and send these variables as json/protobuf/whatever along with abci error code for client-side processing. 

I know we want to go the "easy way", but I do encourage us to at least consider building an interface which could later be reused for more complex scenarios, as refactoring error handling several times is probably a waste of time. 

https://github.com/uber-go/zap/blob/master/logger.go#L185 would be an example of such api, but in error context. 
Note, that we can use varargs to receive stuff, but just as long as it's not interface{}. 

So something like `errs.Error("test", errs.ABCICode(code), errs.Int64(id))` etc.

I would seriously encourage us to not use the `Errorf("wrong id %s", id)` because that's not extendable and error prone. Instead we could use basic text and labels/fields to go with it. This way we don't have to cater for errors in text format and even expecting the text to contain something like `%s or %d`
