### ISSUE TITLE
Remove field sig_figs from namecoin.Token

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#207]
The interface [namecoin.Token](https://github.com/iov-one/weave/blob/v0.9.3/x/namecoin/codec.proto#L14) has a field `sig_figs`. However, all tokens on the weave chain [are fixed to 9](https://github.com/iov-one/weave/blob/v0.9.3/x/codec.proto#L17-L19) fractional digits. Thus the field is probably unused and misleading.

**Comment by ethanfrey** [comment]
This now refers to the following file

https://github.com/iov-one/weave/blob/master/x/currency/codec.proto

I agree that this field is unused, both in client and server, and can be removed
