### ISSUE TITLE
Set up distinct tokens in distinct testnets

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#215]
Currently, we have `IOV, CASH, ALX, and PAJA` in both devnets (https://bov.xerusnet.iov.one/genesis and https://bov.yaknet.iov.one/genesis) as well as the friendnet.

To demonstrate a cross-chain wallet, it is nice to have different tokens on different chains. Also faucets that release different tokens.

All new devnets should have a unique set of tokens, and the new public testnet as well. Let us decide on what they are.

For **hugnet**, I suggest:

On `bnsd`: just `IOV` token (main token we issue)
On `bcpd`: `DEMO` and `ALT` (to show use case of multiple tokens on one chain, both available via faucet)

---

I have changed _apollonet_ to _yaknet_ -- @husio 

I changed it to hugnet... it was meant to be the next public testnet (for wallet demo) - @ethanfrey

**Comment by husio** [comment]
It is better to first do https://github.com/iov-one/weave/issues/198 because currently, genesis file is loaded using `x/namecoin` init. Removing `namecoin` package requires change in the genesis as well.

**Comment by ethanfrey** [comment]
Cash has an init function that should be a subset of that of namecoin, allowing all functionality except for name: https://github.com/iov-one/weave/blob/master/x/cash/init.go

I think it will just silently ignore the name as well... but sure, better to clean up the init code before updating genesis

**Comment by husio** [comment]
[`Set`](https://github.com/iov-one/weave/blob/master/x/cash/codec.proto#L9-L11) is in reality a `Wallet`, so for this issue to complete, it is enough to create a genesis file that will create some `Set` instances. Is that correct?

**Comment by ethanfrey** [comment]
> cash.Set is in reality a Wallet, so for this issue to complete, it is enough to create a genesis file that will create some cash.Set instances. Is that correct?

Yes, set the different tokens in some genesis wallets, as well as define them in `currencies`

**Comment by ethanfrey** [comment]
So, for yaknet, we stick with 0.9.3 (same genesis file format).
Need to update genesis file in k8 config and restart network (delete all state).

For hugnet, we can build a new weave/bnsd release (0.10.0?) with the namecoin and other changes and release this with the new genesis file format.

**Comment by husio** [comment]
This time it's ready for real. `yaknet` was restarted. Please review. :muscle:

**Comment by ethanfrey** [comment]
Looking at current deployed state, this is properly done on yaknet.

:+1:

I couldn't find hugnet genesis... 
Https://bns.hugnet.iov.one/genesis gave me a 404

But the config is done, just need final hugnet deployment (other issue)
