### ISSUE TITLE
Build generic orm object migrations

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#216]
With our current approach to store objects via serialized protobuf in levelDB we have no way to do migrations. For example adding a new field would require setting default values for the already stored entities. In RDBS this would be done by running some migration scripts on the dataset. With document based storage system like levelDB we need some way of "Upgrading" entities when loaded.

This is an example how this could be done in a consistent way. https://github.com/alpe/messaging_spike/blob/master/message_versioning_scenario.go#L50

**Comment by ethanfrey** [comment]
This has been built.
Take a look at https://github.com/iov-one/weave/tree/v0.15.0/migration
