### ISSUE TITLE
Skip test when tendermint binary is not available

### ISSUE THREAD

**Issue by husio** [iov-one/weave#220]
Certain tests [require tendermint binary to be present](https://github.com/iov-one/weave/blob/master/cmd/bcpd/commands/start_test.go#L100). Update them to test if the `tendermint` binary is available and skip otherwise.

Right now, this helper function is [assuming that tendermint binary is in `GOBIN`](https://github.com/iov-one/weave/blob/master/cmd/bcpd/commands/start_test.go#L101), which does not have to be true. It should rely on `PATH` instead.

**Comment by ethanfrey** [comment]
Yes, this came up a few times before.

I can add it to the top of the backlog,after what we set up for this sprint. 

The answer should handle tendermint as Docker as well....

**Comment by ruseinov** [comment]
Add a flag to make sure we always run this on CI regardless of the presence of tm binary
