### ISSUE TITLE
Unify protobuf naming

### ISSUE THREAD

**Issue by husio** [iov-one/weave#227]
Currently, we are using more than one style when creating protobuf messages:
- [snake case](https://github.com/iov-one/weave/blob/master/x/namecoin/codec.proto#L16)
- [camel case](https://github.com/iov-one/weave/blob/master/x/nft/ticker/codec.proto#L15)
- [lowercase?](https://github.com/iov-one/weave/blob/master/x/nft/username/codec.proto#L26)

Use snake_case and update all incompatible declarations.

Notify frontend when the change is made - they have to update their code as well.

Unify how attributes of protobuf messages are created. Pick one of:
- [x] `snake_case`, for example `user_id` - results in `UserId` in Go, which is not Go-like
- [ ] ~`camelCase` with abbreviations uppercase, for example `userID` (**not** `userId`), results in `UserID` in Go, but is still not perfect~
- [ ] ~Go naming convention, for example `UserID`~

~Some attribute names like `id` require to be all upper case. We would like it to be translated to `ID` in Go. In order to achieve that, it should be declared as `ID` or `iD` :see_no_evil: .~

~If we don't care about compiling those messages to any other language, I would propose using Go notation for naming attributes (3rd option), for example: `ID`, `SigFigs` or `UserID`~

**Comment by ruseinov** [comment]
afaik we are using this on the client. but for sure needs to be discussed

**Comment by ethanfrey** [comment]
> If we don't care about compiling those messages to any other language, I would propose using Go notation for naming attributes (3rd option), for example: ID, SigFigs or UserID

The primary choice of using protobuf over amino/go-wire was the full support in many languages. The files must compile flawlessly to javascript, and ideally other possible client libraries, such as swift/java/kotlin if we go the mobile route. Maybe python for those who like to script....

**Comment by ethanfrey** [comment]
`snake_case` is the defacto standard for protobuf files. Eg. https://developers.google.com/protocol-buffers/docs/proto3#simple

We should standardize on this. If we don't like how the names are translated into go, we should make an issue on the go protobuf compiler (https://github.com/gogo/protobuf) or use some custom flags there, as long as the raw `*.proto` files can be properly compiled in any language

**Comment by ethanfrey** [comment]
There are some commands in `iov-core/packages/iov-bns` that builds typescript helpers from the protobuf definitions in weave. Ensure those scripts still work with the changes. If you enable go-specific extensions that are ignored by the protobuf.js compiler (but don't error), that is fine. Otherwise, avoid those extensions
