### ISSUE TITLE
govet errors

### ISSUE THREAD

**Issue by husio** [iov-one/weave#229]
Fix all `go vet` errors. 

Once all go vet errors are fixed, please add `go vet -composites=false github.com/iov-one/weave/...` call to Makefile and travis test phase.

We want to [disable composite literal uses unkeyed fields check (flag `-composites=false`)](https://github.com/iov-one/weave/issues/229#issuecomment-445829012).

```
$ go vet -composites=false github.com/iov-one/weave/...
# github.com/iov-one/weave/x/namecoin
x/namecoin/init.go:24: struct field tag `json: "ticker"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
```

---

_I have updated the story to disable unkeyed fields check_ -- @husio

**Comment by ruseinov** [comment]
I think we might want to consider setting up gometalinter with a bunch of extensions in our ci as well. That would help
with cyclomatic complexity, code style, err checks etc.

If you want to add a ticket for that - I can elaborate on the setup later on and possibly set it up as well. Otherwise I will add it later today.

**Comment by husio** [comment]
Let's keep this one limited to go vet only. Other tools can be added independently.

**Comment by ruseinov** [comment]
this one - sure. But if you look at gometalinter you will see that it basically knows how to combine all the tools available and allow to configure them in centealised fashion. I will create a ticket shortly.

**Comment by ethanfrey** [comment]
I like the idea, but I notice they are almost all `composite literal uses unkeyed fields`, and for structs with 1-2 fields and/or laying out table tests, I see good exceptions to this rule.

I would suggest disabling that one rule, and then enforcing it.

I see one very useful message in that noise: 
```
x/namecoin/init.go:24: struct field tag `json: "ticker"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
```

**Comment by ethanfrey** [comment]
@husio Are you okay with my proposal of limiting the scope of go vet?

I would propose `go vet -composites=false ./...`, which only has one failure and will prevent many regressions. With that change, I am happy to approve this.
