### ISSUE TITLE
Look into adding gometalinter for all our go repos.

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#230]
`golangci-lint` allows to have all the linting done by one tool.

We need to:
- [x] Enable this on some root packages with important errors that need to be fixed, like store
- [x] Enable in the ci
- [x] Dockerize
- [ ] Enable more packages and linters

**Comment by ruseinov** [comment]
@iov-one/blockchain-team FYI.
This helps a lot as it automatically checks complexity, imports, fmt and a lot more could be added. 
saves a lot of back and forth and the code is cleaner then

**Comment by ethanfrey** [comment]
Do you want to take this on @ruseinov ?

**Comment by ruseinov** [comment]
@ethanfrey Yep, would love to.

**Comment by ruseinov** [comment]
assigned to myself for now as I have experience using it.

Once we have time for this - I will open up a PR and we will decide as a team which things to enable. 
There's plenty of good stuff, just need to make sure we don't overdo it. Also, enabling certain linter features would require cleaning up the code, which is a good thing.

**Comment by ethanfrey** [comment]
Yup, good to enable those that work, or we can clean up within an hour or two - to maintain current code quality.

We can add more flags one at a time (as future PRs) as we clean up existing code.

**Comment by ethanfrey** [comment]
Closing this and replacing with #845 and #846
