### ISSUE TITLE
Define BNS username-namespace API

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#231]
This story involves defining the API for namespaces. Implementation is in follow-up stories.

Namespaces are defined [in this document](https://github.com/iov-one/bns-spec/blob/master/docs/basics/PersonalizedAddresses.rst).

We currently only hardcode the `*iov` namespace in the client and just use an un-namespaced address on the server. Namespaces are now considered quite important for launch, so we can sell custom name spaces and let other organizations manage the distribution of names.

We need to:
* Link every username to a namespace
* Provide default namespace(s) in the genesis file (`*iov`)
* Allow open namespace registration. (both creating spaces as well as registering names inside of them)
* Handle various closed/permissioned models of namespaces

This does not include the fee collection or subscription ideas

We need to enhance queries for username, so we query on (username, namespace) pair.
We also need to have a solution when looking up the user by (chain, address) to get both username and namespace name. (This may be two queries on abci, but should be clearly defined).
Information and error messages based on needed permissions should be well-defined.

---

:calendar:  [Meeting scheduled in the calendar](https://calendar.google.com/calendar/r/eventedit/MGZ1dThndHJpaTVzdjBxZ2IwMTMzbDN0MjEgb25kemEuY29tX21kNWU1MGlrYzRycml0dGRvdXN2NjNkbTlrQGc).

**Comment by webmaster128** [comment]
A few preparing questions:

1. Are namesspaces going to have multiple levels (like DNS)? [1]
2. What happens to linked usernames when the namespace is destroyed?

cc @Isabello 

[1] In my experience the term "namespace" implies multiple levels. At least this is what you have in DNS and programming languages like [C++](https://en.cppreference.com/w/cpp/language/namespace), so even if we don't support it, we should document it as non-nestable.

**Comment by ethanfrey** [comment]
Question 2 is my biggest question.

Also when the namespace expires and then is purchased by someone else... or transfers in general

**Comment by ethanfrey** [comment]
I think we have a proper design document for namespaces. That should be broken down into a series of issues. @kmw101
