### ISSUE TITLE
Revisit order of decorators in terms of batch, it's very important to make sure savePoint and batch play nice together.

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#237]

**Comment by ethanfrey** [comment]
The outcome should be:

1. a test of handling a batch where one tx succeeds and a second fails (first tx changes should not be committed)
2. a better explanation of how to use savepoint properly, ideally as a comment in savepoint as well as in the docs

**Comment by ethanfrey** [comment]
Please link the given tests, I will review them and update the issue

**Comment by ruseinov** [comment]
https://github.com/iov-one/weave/blob/master/cmd/bcpd/app/app_test.go#L46
https://github.com/iov-one/weave/blob/master/cmd/bcpd/app/app_test.go#L77

They might need some extra checks though to support your theory
