### ISSUE TITLE
Provide a tool to display an address for the mutisig contract

### ISSUE THREAD

**Issue by husio** [iov-one/weave#251]
In order to make #205 usable, we should have a tool that can display the addresses that would be generated for the multisig contracts, so we can use those values in the other items of genesis (as a static analysis tool to help build a genesis file).

**Comment by ethanfrey** [comment]
More or less...
I would probably prefer something like

1:  ABC...
.. 
20: DEAF...

Maybe a blank line between each for readability. But yeah, functionality is what is desired, just about tuning printf format

**Comment by husio** [comment]
I have extended it as requested and added the code as part of another pull request https://github.com/iov-one/weave/pull/254/commits/c555cdfb47f364c25c29237588ad0117db4a6503

**Comment by ethanfrey** [comment]
Great.
You can close this when that pr is merged. 

I added a comment there https://github.com/iov-one/weave/commit/c555cdfb47f364c25c29237588ad0117db4a6503#r31829457

Please validate addresses manually one time. Or let me know you did already

**Comment by ethanfrey** [comment]
:+1:
