### ISSUE TITLE
Move custom nft types under cmd/bnsd/x package

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#255]

**Comment by ruseinov** [comment]
this might be blocked by https://github.com/iov-one/weave/pull/261

**Comment by husio** [comment]
@alpe We have discussed this yesterday very briefly, so to make sure I understand this correctly, let me summarize.

This story is about moving all submodule of `x/nft`, except `x/nft/base`, from weave into `cmd/bnsd/x/nft`. Once this is done, recompile protobuf files, fix import paths and ensure tests are passing. Is this correct?

If above is true, can I pick it up?
