### ISSUE TITLE
Write cli tool to update validator set

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#269]
## Use cases
* As "partner manager"? I want to add a new validator to the active set of validators in order to create a more resilient network.
* As "partner manager"? I want to remove a validator from the active set of validators in order to punish malicious behaviour and curate the network.

## What to do
- [x] Build a CLI tool (in weave) that can be used in hugnet to **add** a new validator.

Steps internally are: 
* query current validator set
* read private key from stdIn or ENV (base64 encoded) (a file would require encryption/ decryption)
* build, sign and send a [SetValidatorsMsg](https://github.com/iov-one/weave/blob/master/x/validators/codec.proto#L21) to the cluster

- [x] Analogue to this we want to **remove** an validator.
* Remove is be done by setting the validator `Power` to `0`

- [x] Extend the CLI tool to support **multisig** contracts
* This includes exporting the generated message into a file instead of sending it to the cluster
* Importing a message file to add a signature and storing it
* Sending a stored message to the cluster

## Technical background
* The [ABCI spec](https://tendermint.com/docs/app-dev/abci-spec.html#request-response-messages) provides a response field to curate the active validator set.
* The initial validator set is defined in the [genesis file](https://tendermint.com/docs/tendermint-core/using-tendermint.html#initialize)
* Roman had created a [`x/validators`(https://github.com/iov-one/weave/tree/master/x/validators) package with an `initializer` to read and persist them
* An [update handler](https://github.com/iov-one/weave/blob/master/x/validators/handler.go#L40) and [query handler](https://github.com/iov-one/weave/blob/master/x/validators/handler.go#L27) exist
* The query handler should return the accounts that are allowed to sign an update message
* The current validator set can be queried from tendermint via plain http `/validators`

## Not in Scope
* There is some potential risk for a concurrent modification as we are not protecting the data via version number, timestamp, etc. We could also split the update into separate add/ remove operations to prevent overwrites. If we want to address this, any solution should be done in a separate story and after this one.

**Comment by ethanfrey** [comment]
Also validate there is only one address set in genesis file that can update the validator set.
That master key should be set in genesis to some dev key (ideally multisig later on)

**Comment by alpe** [comment]
Reopened it as multisig is not supported, yet. @husio if you want to do this in a new Issue, please add one and link it.
