### ISSUE TITLE
Update docker descriptions for bcpd and bnsd

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#278]
We currently have a [single file](https://github.com/iov-one/weave/blob/master/README_DOCKER.md
) which is outdated already. It is used for the description at [docker hub](https://hub.docker.com/r/iov1/bov) and pasted there manually.

This task is about:
- [x] Split README_DOCKER.md into 2 for bns and bcp and move the file under app `cmd/<app>` level
- [x] Update the files
- [x] Update the descriptions at docker hub

**Comment by husio** [comment]
`bnsd` application was updated in https://github.com/iov-one/weave/pull/292

`bcpd` must be updated.

**Comment by ethanfrey** [comment]
So, I just reviewed this one... The README files in `cmd/*` looks fine (with the possible exception that TM_VERSION should be bumped to 0.29.1).

It seems the only task is to update the description on docker hub.
Do you need special rights to do that? Is that something to add to the CI when publishing??

Can someone make a clear TODO for this issue?

**Comment by ethanfrey** [comment]
Acceptance criteria:

https://hub.docker.com/r/iov1/bnsd/
https://hub.docker.com/r/iov1/bcpd

**Comment by husio** [comment]
I was searching for an explanation of how this should be done, because dockerhub does not seem to be pulling it automatically. Old files are replaced with new ones and no change was applied. Does anyone know what has to be done in order to refresh this information? Who can trigger the update?

**Comment by ruseinov** [comment]
you update that by hand on github, it does support markdown

**Comment by ruseinov** [comment]
@husio oops, sorry, dockerhub

**Comment by husio** [comment]
I have updated both pages. It requires an admin account - credentials can be found in the usual place.

**Comment by ethanfrey** [comment]
Looks good. Thanks!
