### ISSUE TITLE
Allow nft/username to be used alone

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#282]
Right now, it enforces a contraint that all registered (ChainId, Address) pairs contain a ChainId that refers to a Blockchain NFT that is already registered.

As part of the launch requirements, we will only launch with Username management, and not Blockchain management, as there are some security/design issues that need much deeper thinking before we can start on them.

Therefore, we need to make sure that `nft/username` (which will be used on launch) can work without any other nfts being present. 

I do understand that this will allow arbitrary chainIds into the database, and we will never be able to enforce the relation for "legacy" data. Please bring up concerns on that issue here as well

**Comment by ethanfrey** [comment]
Open discussion with @alpe 

* What is chainId? network id? blockchain id?
* how do we enforce whitelist?

**Comment by husio** [comment]
Is this story about changing current `cmd/bnsd/x/nft/username` or creating a new implementation from scratch?
I both cases, I believe we should remove everything else from `cmd/bnsd/x/nft`. Thanks to Git, it can be revived later if needed.

**Comment by ethanfrey** [comment]
It is about modifying current `x/nft/username` (I believe it is not under `cmd/bnsd`)

I think it just removes an import and a constraint.
Existing version is in git history when/if we want to implement whitelisting again

**Comment by husio** [comment]
All nft implementations (except for the nft itself) were moved to bnsd https://github.com/iov-one/weave/tree/master/cmd/bnsd/x/nft/username

**Comment by ethanfrey** [comment]
I guess I have an old version of weave checked out...
I'll do a `git pull`

**Comment by ethanfrey** [comment]
Ahh.... I was looking at 2 week old code, didn't realize you moved it Friday
