### ISSUE TITLE
Only use nft/username in bnsd

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#283]
Depends on #282

For launch preparation, we will only have this one nft exposed. This is a breaking change, so we will need to bump the major version with this one (eg. 0.11.x -> 0.12.0)

**Comment by husio** [comment]
@ethanfrey Most of `nft` packages were [moved to `bnsd`](https://github.com/iov-one/weave/tree/master/cmd/bnsd/x/nft). Is this story about removing unused `nft` packages from `bnsd` (those are `ticker`, `blockchain` and `bootstrap_node`)?

**Comment by ethanfrey** [comment]
Yes, @husio that is correct.
And #282 is about making that possible

We will add more nft packages when they are clear in the product, but let us only ship code we are sure of (from the business logic/product side)
