### ISSUE TITLE
Remove testing flags from CLI tools.

### ISSUE THREAD

**Issue by husio** [iov-one/weave#297]
Figure out, why our command line tools [contain testing flags](https://github.com/iov-one/weave/pull/286#issuecomment-459440065) and remove them.

---

A workaround might be to [use a  local `FlagSet`](https://github.com/iov-one/weave/pull/305#discussion_r255042288) instead of global `flag` package state.

**Comment by ethanfrey** [comment]
I think it has to do with the fact that we import tendermint.
And they do lots of funky things.

I would leave it as "WishList" until there is a clear cause
