### ISSUE TITLE
Standardize new error handling

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#309]
Now that we have agreed on a proper error handling format, extend the error handling from paychan module from #203 #275 #308 to be used in all packages in weave.

This task is to go through all modules and ensure they use the proper "new" API and proper error codes. And that all usages are done well... with simplifications when possible.

Please make one PR for package (or maybe two if they are tied together). Best to get a few small PRs pushed and reviewed for style before sending days laboring without visibility:

- [x] orm
- [ ] examples/tutorial/x/blog/
- [x] x
- [x] x/cash
- [ ] x/currency
- [ ] x/escrow
- [ ] x/multisig
- [ ] x/namecoin
- [ ] x/nft
- [ ] x/sigs
- [x] x/validators

**Comment by husio** [comment]
While writing a proposal for error handling I have made a mistake of naming error instances incorrectly. [Proper error naming pattern](https://github.com/golang/go/wiki/Errors) is `ErrXxx` and not `XxxErr`. This means that for example instead of [`InternalErr`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L14) we  should have `ErrInternal`.
:bug: :bug: :bug:

Should I create a separate issue for this or add another checkbox to this issue list?

**Comment by ruseinov** [comment]
@husio actually I like it more currently, because it helps to differentiate between old and new errors and somehow it feels better.
Let's leave it for now, we can always refactor later.

**Comment by ruseinov** [comment]
Also because when I need an internal error and have autocomplete, starting with Err will give me like 200 errors, and starting with Int gives me 3 :)

**Comment by ethanfrey** [comment]
I agree with @husio 

We chose the naming in the old package as proper.
We also make sure to keep the same package name (errors, not perrors or werrors or whatever). Saying it is a bit more work for you during the refactor is not a good reason to not keep the naming we agreed upon

**Comment by ethanfrey** [comment]
The whole `ErrXxx` and `IsXxxErr` nomenclature comes from one of the earliest code reviews @alpe did on weave and I like it. Especially as it sticks to go standards.

**Comment by ruseinov** [comment]
@ethanfrey fair enough, I don't care about more work, I just happened to like it more this way.
Thankfully we no longer need to use IsXXXerrr as we have ErrXxxx.Is defined.
Helper methods like this are a huge pain to maintain
