### ISSUE TITLE
Refactor x/nft/base

### ISSUE THREAD

**Issue by husio** [iov-one/weave#320]
While [simplifying nft/username implementation and removing not needed anymore implementations](https://github.com/iov-one/weave/pull/312), `nft/base` was left behind.

This is a proposal of refactoring parts of the `nft/base` package. If they are too big for a single issue, please split them.

- [ ] merge `x/nft/base` into `x/nft`. In my opinion (@husio) there is no gain in keeping `base` package separate. `base` package provides less than 150 lines of code for generic NFT handlers.
- [ ] remove [the dependency on `bnsd` package in tests](https://github.com/iov-one/weave/blob/nft_standalone_username_issue_282/x/nft/base/handler_test.go#L8). This import is possible only because we keep our applications in the same repository. In my opinion imports in `weave` should never be done to an application. This also makes the `base` package tests dependant on an external implementation :no_good_man: 

Bonus points for following up on [testing issue](https://github.com/iov-one/weave/issues/249) :1st_place_medal:

**Comment by ethanfrey** [comment]
@husio deleted it all. No more need to cleanup
