### ISSUE TITLE
Issuer ignored in x.Coin Add/ Substract/ ??? functions - REMOVE IT

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#321]
## Expected Behavior
```
	// Issuer is optional string, maybe chain_id? maybe custodian name?
	// can be empty. tokens are only fungible if CurrencyCode and
	// Issuer both match.
```
https://github.com/iov-one/weave/blob/master/x/codec.proto#L26
For example a `Coin{ticker:"ALX", issuer="foo"}` should not be equal or combined with a Coin{ticker:"ALX", issuer="bar"}`

## Actual Behavior
Issuer is ignored

##
Revisit coin methods and all creations of Coins (NewCoin, &x.Coin{}) that the issuer is properly set.

**Note from ethan** Please remove Issuer field from protobuf and all references to it. We will invent something better when the concrete need arises.

**Comment by ethanfrey** [comment]
Good eye. This is a very valid bug. But I think this needs a deeper thinking before doing anything.

`Issuer` was a placeholder from me from me early days of design, when IBC was around the corner, BNS was just a twinkle in someones eye, etc.... I think it may need to be removed/rewritten, so let us consider the utility before fixing a broken but unnecessary feature.

I think the concept of `namespaces` is a superset of what I consider `Issuer` here.
I think we can also consider how tokens are identifier both in one chain and globally.

I would like to have a bigger conversation of what this field really means, and if we want to keep it. And after that, either remove it, or fix it and make proper use of it

**Comment by ethanfrey** [comment]
Ah.... I looked again, the `Issuer` is propogated properly, it just is not used in the Equality tests.

I guess we can fix this issue as a bug, but I would really like to collect feedback on whether the field has meaning or what we want to do with it.

**Comment by ethanfrey** [comment]
Ahh... and it is **not** propogated in `Divide`
