### ISSUE TITLE
Make x.Coins resilient to improper usage

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#327]
**Is your feature request related to a problem? Please describe.**

During development of https://github.com/iov-one/weave/pull/316 there was some confusion, as all code that deals with `x.Coins` assumes a normalized, sorted form, but nothing prevents you from just casting poorly defined Coins.

We should avoid people hitting confusion and bugs with this. 

**Describe the solution you'd like**

Usage of Coins should be clear.

One solution is a clear `Normalize` method or constructor (more obvious than `CombineCoins`, which does the job).

Another solution is to check if the coins are normalized at the top of all functions, and then normalize if needed.

Another solution is to change `x.Coins` to

```golang
type Coins struct {
  coins []*Coins
}
```
and have a constructor that normalizes some input `Coin` before storing them in this `Coins`. Then all methods can be very secure in the knowledge of what they deal with.

The first solution (document better) has zero run-time overhead, but is more fragile.

**Describe alternatives you've considered**

Writing all code assuming Coins are in an unsorted order... this is too complex... let's just normalize once, and then the rest of the code is easier.

**Comment by alpe** [comment]
Solution 1 with the `Normalize` function and solution 2 can go hand in hand with little impact on the existing code base.

**Comment by ethanfrey** [comment]
Okay, then the current proposal, based on @alpe 's feedback:

1. Add a very clear `func NewCoins(coins []*x.Coin) x.Coins` that returns `x.Coins` in a normalized form and is well-documented in godoc and the code.

2. Add a `func (cs x.Coins)isNormalized() bool` that does a quick check if they are in normal form (we can check sort order and no dups with one simple pass, ensuring each is greater than the last), checking overflow/signs of the Whole/Fractional field should be doable cheaply. Let's make this function very cheap to run, assuming 95% of the data will be normalized already.

3. export `func (cs x.Coins)normalize()  (x.Coins, error)` as `Normalize`

4. On the top of any function that requires normalized coins, add a simple
```golang
if !cs.isNormalized() {
  cs = cs.Normalize()
}
```

This should add minimal overhead to code with correct sorting. Add a simple and obvious pass to correct usage. And allow all functions to return the correct output (even if rather slower) when fed de-normalized data.

This should be clear enough to be actionable, if accepted

**Comment by ruseinov** [comment]
Sounds like exactly what I would do, I like that

**Comment by ethanfrey** [comment]
Was this resolved in the end to everyone's satisfactions?

@husio I think this was your concern largely

I would like to close or make a clear actionable item to follow up on.
