### ISSUE TITLE
Only allow updating validators when fees and block rewards have just been distributed.

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#329]
Think about this.
Came up as a concern from devs to provide a check on governance. What can we do? What do we want to do?

**Comment by ruseinov** [comment]
I suppose we could introduce some new kind of tx, so that when we send a validator update message it would save it in the bucket and wait for an event to happen to propagate these changes.

It does seem a bit complicated though.

**Comment by kmw101** [comment]
This is also a requirement for MvP and something that came up when discussing the roles of Governing Board and Validators.

The flow should be Validator set amended by Governing board members proposing and voting (this creates a draft or pending set), the Validator set is not updated until the rewards are distributed.

**Comment by ethanfrey** [comment]
Right now, we have it that updating validators will automatically trigger distributing all collected fees to all existing validators before making the change. (using the distribution contract)

However, the block reward distribution (to feed the fee contract) is not triggered with this. And in fact, as it is implemented, it is easy to avoid any checks (let us give a block reward of 0.1 IOV for last month, update validator set, then give a block reward of 100000 IOV for the next hour, ...). This only makes sense once the block rewards are distributed in some algorithmic manner, and then ensure this is auto-triggered when the update/distribution happens

**Comment by ethanfrey** [comment]
Obsolete as we have different design for bnsd
