### ISSUE TITLE
Update key derivation path

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#346]
We use key derivation from seed in a number of examples and tools. This should be compatible with our frontend wallet, and we changed the path recently to be standard across chains.

The new path should be:

m/44'/234'/a'

Where a is 0 or 1 for most uses

https://github.com/iov-one/iov-core/blob/master/packages/iov-keycontrol/src/hdpaths.ts

TODOs:
- [x] Update key addresses in wiki
- [x] Update key derivation path in weave scenarios
- [ ] Replace key addresses in zebranet genesis for bcp + bns

**Comment by alpe** [comment]
It is used in https://github.com/iov-one/weave/blob/master/cmd/bnsd/scenarios/main_test.go#L39 only AFAIK. I agree we should update the default but this should be reflected by new testnet genesis accounts as well as a wiki update

**Comment by ethanfrey** [comment]
I agree. This is mostly used for the ops setup and documentation, but to make sure we update all reference to the old path

**Comment by ethanfrey** [comment]
We need to generate new public keys for the genesis for alice, bert, etc... using new derivation path

**Comment by ethanfrey** [comment]
Was this finished @alpe ?

**Comment by ethanfrey** [comment]
@alpe @ruseinov 

Can you take this into consideration for antnet (or post-antnet) testnets? At least for the 0.17.0 public facing one.

Just like to close it after all

**Comment by ruseinov** [comment]
@ruseinov I'll take a look at the genesis tmrw to see what we have.
