### ISSUE TITLE
More friendly references for genesis file

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#347]
Currently all references in the genesis file are hex-encoded addresses. Eg. When selecting the account to place tokens in cash, or participants in multisig, or even the fee collector.

Due to this, we had to build the `lsc` (renamed to [`lsaddr`](https://github.com/iov-one/weave/tree/master/cmd/lsaddr)) tool to pregenerate the addresses associated with eg. The first 20 multisig contracts. And now we will have to add that for escrows to make them usable in the genesis file.
https://github.com/iov-one/weave/issues/310#issuecomment-465291165
We also need a tool to hexify Bech32 addresses from the wallet before inserting them in the genesis. This doesn't just add overhead in genesis creation, it makes it less transparent and harder to check. 

The simplest solution that came up in the discussion is to extend weave.Address.UnmarshalJSON(). It will look for some special (non-hex) prefixes and use custom parse logic if it finds them, otherwise, it will default to interpreting the string as hex. It will *always* `MarshalJSON()` into hex. The point is not for interchange formats, but rather to allow easier creation of json configuration by humans.

Base format (hex): 
* If no prefix detected, works like now

Condition support: prefix `cond:`
* This will assume the suffix is a [stringified Condition](https://github.com/iov-one/weave/blob/master/conditions.go#L61-L67), which looks something like `cond:multisig/usage/00000002` (last section of multisig is hex-encode binary)
* It will parse this data properly into a Condition (no existing code), then call `Condition.Address()` 
* We can assert some equality, like `cond.Address() == Address.UnmarshalJSON("cond:" + cond.String())` (rough pseudocode)

Bech32 support: prefix `bech32` (future issue - here for illustration)
* We can take input like `bech32:tiov12345...`, which will be the address as exposed on the wallet.
* Weave accepts any prefix and just parses out the bytes and validates the checksum
* This allows us to create an account in the wallet, and easily import it in genesis

Note, upon completion, the `lsaddr` tool can be considered deprecated. We may use it occasionally, but I would freeze active development on it unless there is a good need, as I believe this would provide a better user experience.

-----------

**Obsolete but basis for discussion below**

Rather than continue down this road, I would suggest creating a new struct called GenesisRef, which could contain a hex address, a condition, or a Bech32 encoded address. This GenesisRef could have a function ToAddress() which always returns the weave.Address associated with that reference. 

Since we already use different structs for the json parsing and process them before inserting in buckets during initialization, there should be no big barrier to doing this. 

Example
Change type of GenesisAccount.Address
https://github.com/iov-one/weave/blob/master/x/cash/init.go

And contract.Sigs
https://github.com/iov-one/weave/blob/master/x/multisig/init.go

And all other init references. 

A proposed format could be:

```
type GenesisRef struct {
  Hex weave.Address `json:"hex" `
  Condition weave.Condition `json:"condition" `
} 
```

Assuming we add a UnmarshalJSON() method to Condition that is the inverse of String () output.

We could then add Bech32 parsing support in a future pr, but it would be a non-breaking change.

**Comment by husio** [comment]
Could you explain a bit more what the reference is?

I do not think I undestand you correctly. But if I do, if `GenesisRef` is like a union field than I think this could be done using a prefix for the value and a custom `UnmarshalJSON()` method instead. For example

```go
type GenesisRef string

func (gr *GenesisRef) UnmarshalJSON(b []byte) error {
    switch string(bytes.SplitN(b, []byte(":"), 1)[0]) {
    case "hex":
        // unmarshal as hex
    case "bech32":
        // unmarhsal as bech32
    default:
        return errors.Wrap(errors.ErrInvalid, "unknown reference format")
    }
}
```

**Comment by ethanfrey** [comment]
Ref should be a union field.
I figured a struct with one of many optional fields was simplest, but sure, open to other designs.

To use something like:

```json
"coins": [{
  "tokens": [{"ticker": "IOV", "whole": 123}],
  "address": {"hex": "01234..."}
}],
"multisig": [{
  "min_weight": 3,
  "signers": [
    {"condition": "multisig/contract/2"}
    {"hex": "deadbeef00cafe00..."}
    {"bech32 "tiov12345..."}
  ]
}]
```

In you approach, this would be something like:

```json
"coins": [{
  "tokens": [{"ticker": "IOV", "whole": 123}],
  "address": "hex:01234..."
}],
```

?

**Comment by ethanfrey** [comment]
I think the syntax is more readable in your approach...
And since the only purpose is for making writing/reading genesis files easier, human usability of the JSON format is important

**Comment by husio** [comment]
Maybe instead of adding an additional type, [`weave.Address.UnmarhshalJSON`](https://github.com/iov-one/weave/blob/master/conditions.go#L97) can be updated to support more formats. That would provide a smooth transition and enable this functionality for all existing codebase without any effort.

**Comment by ethanfrey** [comment]
But this would break parsing all existing formats, right?

Or I guess it assumes hex, unless there is a prefix.

Like
* `00cafe0012345`...
* `bech32:tiov12345...`
* `cond:multisig/usage/00000002` (last section of multisig is hex-encode binary, first two as strings)

**Comment by husio** [comment]
> Or I guess it assumes hex, unless there is a prefix.
Correct. Keep it working as it is right now and extend by allowing the prefix to change the format. The prefix should be delimited by some non hex character.

**Comment by ethanfrey** [comment]
Okay, please accept my last proposal above, or make a different proposal of how to display them.

Then I can update the description with that new change to `Address.UnmarshalJSON()` and this issue has straight-forward acceptance criteria

**Comment by husio** [comment]
> * This will assume the suffix is a stringified Condition, which looks something like `cond:multisig/usage/00000002` (last section of multisig is hex-encode binary)

This looks good!

I wonder if being less specific in the condition would be a better approach. For example when referencing an escrow model I undestand that with the current proposal a reference would look like this `cond:escrow/seq/000000002`. 
Escrow condition creation is [an implementation detail](https://github.com/iov-one/weave/blob/master/x/escrow/model.go#L85-L87) so it feels weird to know it outside of the package. How about instead allow for a declaration like this `cond:escrow.Condition(2)`. 
This will call the `Condition` function of the `escrow` package with an argument 2. It looks like programming and it is more complex to implement. I think this notation is also easier to undestand and use.

**Comment by ethanfrey** [comment]
I understand your goal, but I would add that as a future extension to this Marshaller, as it puts more work on every module creator. Right now, we can just define all conditions without any changes to new modules, but requiring a bit of work by the user.

Maybe we can have a `fn:escrow.Condition(2)` call as another issue... Please feel free to document and add it. I will add one for bech32 support.

> Having the above resolving `cond:escrow.Condition(2)` condition is easy!

This is not so easy, as we need to parse arbitrary `[]byte` (or `string`) into the args needed for the Condition function. Sometimes this is int, other times, assumed hex-encoded binary (like sigs), other times it could be a string, like username nfts.

So, this parsing needs a wrapper around the real `escrow.Condition`, and may return an error as well. I agree with the global registry idea, but I would implement this as-is to easily get a basic support, and consider this as a latter addition
