### ISSUE TITLE
gconf package cache

### ISSUE THREAD

**Issue by husio** [iov-one/weave#361]
When using a `gconf` module [each call is using database and unmarshal the result](https://github.com/iov-one/weave/blob/master/gconf/gconf.go#L70). This might be an expensive operation depending on the database and JSON unmarshaling.

The current implementation does not allow to change the `gconf` configuration during the runtime. That means that each value can be cached "forever".

We do not want each extension to cache `gconf` results on its own. Instead, we want `gconf` to provide the best performance possible.

Add cache to all gconf loading functions to perform well.

Related issue: https://github.com/iov-one/weave/issues/360
Related discussion: https://github.com/iov-one/weave/pull/359#discussion_r260680595

**Comment by ethanfrey** [comment]
@husio made some [nice benchmarks](https://github.com/iov-one/weave/commit/258d039378fbcb582a28ca5243cd87f4d04c09f5) as part of https://github.com/iov-one/weave/issues/360#issuecomment-472930451

My takeaway is a rough estimate of 5 microsecond per tx as maximum savings here.
Until we have other performance optimization and benchmarks indicating tx processing times < 100 microseconds, I would not dig in deeper.
