### ISSUE TITLE
Add support for bech32 in genesis file

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#362]
Builds on #347

Also allow the `bech32:` prefix to be parsed:

We can use [tendermint bech32 implementation](https://github.com/tendermint/tendermint/blob/master/libs/bech32/bech32.go) as an example and use the implementation from https://github.com/btcsuite/btcutil/tree/master/bech32

We should also verify the library matches the values we have with iov-core (use some standard encode/decode test vectors)

**Comment by husio** [comment]
When importing a `bech32` implementation I think we should test it ourselves as well to ensure the quality. We can probably copy tests from iov-core. 
We have used https://github.com/ltcsuite/ltcutil in the past and the implementation was wrong. I have wasted time trying to find an issue in my code assuming that the bech32 implementation was correct. 

@webmaster128 created a bug report for the `tlcutil` repository but I can see that they have solved the problem by disabling the issues :joy:

**Comment by webmaster128** [comment]
@husio I think they don't care much about code they inherit from https://github.com/btcsuite/btcutil and don't use. Maybe it is worth fixing the btcsuite/btcutil implementation and use it.

**Comment by husio** [comment]
Blocked by https://github.com/btcsuite/btcutil/issues/137 unless we will use different bech32 decoder implementation.

**Comment by ethanfrey** [comment]
Looks like that library is a no-go for now. I was digging in to see if the bech32 c utility was reliable (or maybe that one had errors). Seems this uses code pulled from the reference implementation.

Digging for test vectors to validate one over the other, I found a [list of reference implementations](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#reference-implementations) in many languages, [including go](https://github.com/sipa/bech32/tree/master/ref/go). And this version includes a [complete test suite with test vectors](https://github.com/sipa/bech32/blob/master/ref/go/src/bech32/bech32_test.go).

Digging in, I found no license file, but as one github user [pointed out](https://github.com/sipa/bech32/issues/42), there is a [BSD license in the source itself](https://github.com/sipa/bech32/blob/master/ref/go/src/bech32/bech32.go#L1-L21).

Given this code has not changed in around 2 years and is a reference implementation, I would suggest copying these files (including the original copyright notice) into our repo and using that.

**Comment by husio** [comment]
Copy https://github.com/sipa/bech32/tree/master/ref/go/src/bech32 as is into `weave/crypto` as `weave/crypto/bech32`.

**Comment by matheusd** [comment]
`Decode()` returns a slice where each element has 5 bits of the payload data. You need to further call `ConvertBits` to get the original data:

```go
	// ...
	payloadDec, err := bech32.ConvertBits(payload, 5, 8, false)
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(want, payloadDec) {
	// ...
```

**Comment by ethanfrey** [comment]
Thanks @matheusd 

I was really wondering how this implementation could differ from the standard. I guess we have two approaches that work now.
