### ISSUE TITLE
Require ticker for min fee - no wildcard

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#369]
**Is your feature request related to a problem? Please describe.**
I can see the additional complexity that comes with it in the [code](https://github.com/iov-one/weave/pull/364#discussion_r261698654) and also the the uncertainty for a an end user in terms of actual tx costs.

**Describe the solution you'd like**
Fail fast in init phase when fee is set without a ticker.

**Describe alternatives you've considered**
As I don't know the history why we have the wildcard I must assume we may want to support a list of options like gaiad: Minimum gas prices to accept for transactions; Any fee in a tx must meet this minimum (e.g.` 0.01photino;0.0001stake`). the `;` is the **OR** but a `,` would be **AND**.

**Comment by ethanfrey** [comment]
This is a very good cleanup related to #364 

We can consider multiple fee tokens at a later date, but for the foreseeable future, the only known production user of weave is iov, and they will only allow iov tokens for fees. When there is a clear usecase and need, we can revisit the multiple fee-token alternative described above.

**Comment by ethanfrey** [comment]
This still needs to be done for the (static) `FeeDecorator`. `DynamicFeeDecorator` was already fixed
