### ISSUE TITLE
Create a package for testing tools

### ISSUE THREAD

**Issue by husio** [iov-one/weave#372]
This is the result of https://github.com/iov-one/weave/pull/364#discussion_r discussion 

Create a package that will contain functions and types helpful during tests. 

This is a migration/cleanup for the [`x/helpers.go`](https://github.com/iov-one/weave/blob/master/x/helpers.go) file. Instead of using the [`TestHelpers`](https://github.com/iov-one/weave/blob/master/x/helpers.go#L15) as a namespace we want to use a package.  Code will be moved gradually.

## Acceptance criteria

- [ ] pick a good name (as opposed to [bad names](https://blog.golang.org/package-names#TOC_5.)) for the package,
- [ ] As a first step move handlers implementations only from the `x/helpers.go` to the new package. 
- [ ] Replace the use of [a custom handler mock in `x/cash` tests](https://github.com/iov-one/weave/blob/master/x/cash/dynamicfee_test.go#L287) with the one from the new package

**Comment by ethanfrey** [comment]
I would actually move all code from x/helpers.go over there in one fell swoop. So there is one canonical point to use it.

Adding the custom handler mock from `x/cash/dynamicfees_test.go` can be done as a generic handler that accepts 4 arguments `(checkRes, checkErr, deliverRes, deliverErr)` for maximum flexibility. As we already have one that just returns errors, it may also be nice for a helper version that just takes `(checkRes, deliverRes)` and then fills in the nils to make it easier to read.

I would make two PRs. One for moving the mock handler into the test helpers. Another for moving TestHelpers into a new package. Can be done in either order.

**Comment by husio** [comment]
> Adding the custom handler mock from x/cash/dynamicfees_test.go can be done as a generic handler that accepts 4 arguments (checkRes, checkErr, deliverRes, deliverErr) for maximum flexibility. 

I believe that what is in `x/cash` is what you have in mind. [`handlerMock`](https://github.com/iov-one/weave/blob/master/x/cash/dynamicfee_test.go#L287) can be used like this (notice how [zero value is useful :star:](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=6m25s)). Do you think that a constructor is still needed? This is similar to how for example the [`sync](https://golang.org/pkg/sync/) package is written - there is no constrictor for `Mutex` or `Pool` 

```go
// an "empty" handler is useful 
successHandler := &HandlerMock{}

// customization is a easy
successHandlerWithACustomResult = &HandlerMock{
   CheckRes: weave.CheckResult{Log: "foo"},
}

// allow to configure for an error result
failingHandler := &HandlerMock{
    DeliverErr: errors.ErrInternal,
}
```

What do you think?

**Comment by ethanfrey** [comment]
Please propose a good name before starting the issue. That means now.
