### ISSUE TITLE
Add unique client package

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#375]
**Update** There have been lots of questions on this one. I know what I want to do. I think easiest is that I implement this issue as a number of smaller PRs getting feedback on each approach step by step. Code speaks louder than words.

**Update 2**

1. Add helper functions to `./client` to allow us to pull out code duplication (common patterns) from bnscli. Only add features needed by bnscli

2. Update bnscli to use this library

3. Investigate if we can make this work without using tendermint/rpc but rather our own rpc helpers.

4. Long term `cmd/bnsd/client` will be either refactored to use this, or removed if we wish to use bnscli for acceptance tests

**Is your feature request related to a problem? Please describe.**

We have `cms/bnsd/client` directory with useful functionality, but this is not reusable, or heavily tested. I would like a solid, reusable golang client, both for our internal tests, as well as writing cli tools, or server applications that need to talk to the backend.

Clarification: This should be used for AT and loadtesting, both against bnsd and bcpd. Pulling out as much powerful functionality into an app-independent package for best reuse. This should allow writing more complex ATs and loadtest scenarios with less code. As part of this or a follow-up, we can demo some basic benchmarking over tendermint rpc for example.

Please note that you can test against an in-process tendermint rpc node for unit tests (TODO: link code, some main_test.go files)

**Describe the solution you'd like**

I'd like an easy way to make transactions, query, and subscribe.

Ideally, we could expose the ReadOnlyKVStore interface over abci using the orm queries, and then we can use Buckets with `Get` and `GetByIndex` to reuse the same parsing logic. A deeper code look is needed to ensure this is sensible.

Generic key-handling and tx-/signing/posting actions could be provided here, while the actual tx building must be app-specific. And we can expose a few different ways of posting (with different async performance)

We should expose and easy way to check height and `WaitForHeight` (using header subscriptions).

We should also expose tx search and subscriptions (by tags), and some way to "watch" a key using the tx subscription and the buckets and the known mapping between the two. Much of this needs to be configured in a app-specific way, but the logic can be generic, and we can just pass in a Bucket and a prefix to wrap a tendermint client connection with all this info.

**Describe alternatives you've considered**

I copied `cmd/bnsd/client` into another project and did some refactoring and bug fixes on it, separating it into a [weave-generic component](https://github.com/confio/credible-chain/tree/master/weaveclient) and a [app-specific component](https://github.com/confio/credible-chain/tree/master/client). This is not a perfect solution, but a rough example of what I think could be useful... with `weaveclient` ported to a top-level module in `weave`, and the other in the `cmd` dir

**Acceptance Criteria**

(Feel free to make a few different PRs to tackle these parts... it should be a new top-level package, `client`)

I want:
- [x] Expose ReadOnlyKvStore over tendermint rpc (abci_query) so we can re-use Buckets in client to handle all parse and query logic (refer to `app/helpers.go:ABCIStore`)
- [x] Solid logic to handle writing in a concurrent setting (I would refer to https://github.com/confio/credible-chain/blob/master/weaveclient/client.go#L243-L290 as an example for the async version - blocks on Check to guarantee ordering - we can also make a simple wrapper that blocks as well)
- [ ] Nice helpers to work with Nonces/Broadcast for eg. loadtest settings with many concurrent writes
- [x] Query/Subscriptions to headers
- [x] WaitForHeight() and WaitForNextBlock() functions based on subscriptions
- [ ] Generate transaction tags (for search) from Object key (we map key to tag in the Decorator)
- [ ] Query/Subscribe to all transactions that touch a key/Object (and parse them), eg. watchAccount

I think that is all....

Oh, and this should be 90% generic code that is not in the `cmd/*` directories. The actual transaction building will need some `cmd/*/app` level code. The queries/parsing should be largely handled by the various `x/*` modules (thus "free" to reuse for any app)

Bonus:
- [ ] Nice helpers to build a transaction from a message (some proposals are above)

This should make writing acceptance tests and load tests much easier and cleaner.

**Comment by husio** [comment]
I think this is a good idea. It is not an easy task but it would allow us to write acceptance tests much easier.

Should such client be a weave client or bnsd client? I think there is only a slight difference between them (for example supported extensions).

**Comment by ethanfrey** [comment]
Hmmm... So not even showing the transaction itself... And Auto calculate fee as well?

Interesting. It would be good to have full control for multisig or hash lock, but you are right that 90% of cases just need a message and a private key. And should do the rest automatically

**Comment by ethanfrey** [comment]
I would like a generic weave-based library that would provide 90% of the code. It could be imported and wrapped to make a Bnsd specific client, a bcpd specific client, or a client for any other weave based blockchain

**Comment by husio** [comment]
I did not think about the fees. I think using [functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) would allow it to mix options and introduce/remove plugins without breaking existing. 
If my example was to support fees, I would update it to
```go
cli.Submit(&cash.SendMsg{...}, 
    bnsdclient.Sign(alice),
    bnsdclient.Fee(1, 0, "IOV"))
```

If tomorrow we need to support simething else, `bnsdclient.SomethingElse` function is added to fullfill the requirement.

**Comment by ethanfrey** [comment]
Very nice design

**Comment by ruseinov** [comment]
Or this could be done in a similar, but chained manner, like
```bnsdclient.New(&cash.SendMsg{})
    .Sign(alice)
    .Fee(1, 0, "IOV).Submit()```
which would be something very familiar to people coming from all sorts of languages, as this is a common approach, where each method returns an instance of `this`, which in this case is a client instance with a bunch of state set by previous calls.

**Comment by ethanfrey** [comment]
I would like to wait until #412 is done and a bit more cleanup with the abci level tests, then I will define this clearly.

I want:
- Expose ReadOnlyKvStore over tendermint rpc (abci_query) so we can re-use Buckets in client to handle all parse and query logic
- Nice helpers to build a transaction from a message (some proposals are above)
- Solid logic to handle writing in a concurrent setting (I would refer to https://github.com/confio/credible-chain/blob/master/weaveclient/client.go#L243-L290 as an example for the async version - blocks on Check to guarantee ordering - we can also make a simple wrapper that blocks as well)
- Nice helpers to work with Nonces/Broadcast for eg. loadtest settings with many concurrent writes
- Query/Subscriptions to headers
- Wait for height() function based on subscriptions
- Auto-generate transaction tags from Object (we map key to tag in the Decorator)
- Query/Subscribe to all transactions that touch a key/Object

I think that is all....

**Comment by ruseinov** [comment]
> Expose ReadOnlyKvStore over tendermint rpc (abci_query) so we can re-use Buckets in client to handle all parse and query logic (refer to app/helpers.go:ABCIStore)

The idea is as follows:
- We need to implement a similar helper that queries stuff from tendermint rpc
- As far as I understood it the query path is always `/`, because the key is getting prefixed automagically with bucket name
- Write some tests
- Extract common parts for these two
- Possibly move both to the new client package as ABCIStore does not seem to be used anywhere (@ethanfrey does this make sense?)
- Then we'll be able to pass this store to bucket operations

**Comment by husio** [comment]
I have started to write a summary just to realize I describe a tendermint client, not a weave client. Maybe someone will find it interesting, because it took me 1h to write it (sic!).

[issue_375.txt](https://github.com/iov-one/weave/files/3068552/issue_375.txt)

**Comment by ethanfrey** [comment]
Thank you for that great write-up @husio 

I did find it useful. But I differ with your opinion by making it concurrent just by adding `go`.

For example, with broadcasting tx, we want to ensure that `CheckTx` is called in the order the functions are called (takes maybe 20 ms), but not block on the commit (takes maybe 2s).  So I can send 10 tx and wait until they all make it in the same block. But also know that they will be in order, so I can use multiple nonces from the same account.

I like the channel with subscriptions, but I also feel it is nice to block on the original request (subscribe succeeded or failed), then fill in the channel in a go-routine (forever). But have a quick synchronous response to handle network errors. This is like `Promise<Stream<Result>>` type we use a number of places in iov-core. As just returning a stream (channel) that sends an error as a first result is not the easiest to use. (Even more, when the channel only returns success and just closes on error).

I will take this comment of over-complicated to reflect on, and I would love to discuss some API designs that combine power and usability

**Comment by husio** [comment]
![](https://i.imgflip.com/35h2q7.jpg)
