### ISSUE TITLE
Document config file for zebranet

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#377]
The config file for zebranet should be made to model the general setup we see for mainnet. We should produce a configuration file structure that we document, even if we change the actual public keys referred to.

Along with the genesis file should be a short document explaining it, so we can get feedback to business as to which elements they can easily tune in their discussions and what require code changes.

eg:
* creating the governance multisigs
* creating the validator distribution
* creating the block reward contract
* wiring them all together
* setting product fees
* gconf settings they can tweak (eg. anti-spam fee)
* and anything else similar that makes sense

**Acceptance Criteria**

- [x] `genesis.json` (with placeholder addresses, AAA... BBB... etc) created with realistic values for mvp usecase (in `cmd/bnsd/client/testdata/genesis.json`)
- [x] embed comments in `genesis.json` explaining the purpose and what can be tweaked.
- [ ] Use same format for the genesis fixtures (`cmd/bnsd/app/testdata/fixtures/app.go`)
- [x] Update AT to cover a simple usecase... product fee paid, block reward released, fees distributed to validators

**Comment by alpe** [comment]
While working on the genesis the question popped up how many multisig contracts we want for security/ process concerns. Three workflows should be covered in a realistic scenario
* Add/ remove validator as on boarding manager
* Release new tokens as "escrow" arbiter
* Split collected rewards as "distribution" admin

For simplicity I have started with 1 multisig that can authorize all processes.  WDYT?

**Comment by alpe** [comment]
> genesis.json (with placeholder addresses, AAA... BBB... etc) created with realistic values for mvp usecase (in cmd/bnsd/client/testdata/genesis.json)

`cmd/bnsd/client/testdata/genesis.json` is used by the client/wallet_test only and is not validating the genesis proper. I will copy it there for documentation.


>  embed comments in genesis.json explaining the purpose and what can be tweaked.

The recommendation in slack was to create a txt file that will be processed to become the final genesis JSON file by removing the comments. That unfortunately does not work with current toolset in devnets. So I will do this with Go in weave.

>  Use same format for the genesis fixtures (cmd/bnsd/app/testdata/fixtures/app.go)

The fixture uses a Go map instead now. Should I convert it and add it there although the scenario tests have a very similar setup already? See https://github.com/iov-one/weave/pull/401

>  Update AT to cover a simple usecase... product fee paid, block reward released, fees distributed to validators

As discussed on slack we have covered all steps separately in the ATs. Can we remove this from the list?

**Comment by ethanfrey** [comment]
Yeah, above sounds fine.
It is mainly do what make sense and the points above were guidelines from discussions... that all the fixtures were updated.
I know we use maps... they should also be updated with the same contents (still go map, not json string, as that seems easier for you), to ensure all tests hit the full setup and find bugs like the condition error you reported

**Comment by ethanfrey** [comment]
I think this is done in current master, but I couldn't tell you whcih pr did it (#401 ?)

If you agree @alpe feel free to close this
