### ISSUE TITLE
Cleanup coins package errors

### ISSUE THREAD

**Issue by husio** [iov-one/weave#378]
Cleanup `coin` package errors.

- [x] remove [`ErrInvalidWallet`](https://github.com/iov-one/weave/blob/master/coin/errors.go#L11)
- [x] replace [`ErrHuman` with a better error](https://github.com/iov-one/weave/blob/master/coin/coin.go#L55)
- [x] remove [`ErrInvalidCoin` with a better error](https://github.com/iov-one/weave/blob/master/coin/coin.go#L239-L288) - `ErrOverflow` might be a better choice in all cases.

**Comment by ethanfrey** [comment]
Yes, I agree, they can all be simplified to ErrOverflow.
