### ISSUE TITLE
New bump sequence Tx

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#388]
**Is your feature request related to a problem? Please describe.**
> A typical use for this is to allow invalidating large ranges of transactions that were pre-shared with others when implementing complex multi-party transactions that form workflows.

**Describe the solution you'd like**
Add a new Tx type that does only increment an accounts sequence number.

**Describe alternatives you've considered**
Any existing Tx that increments the sequence number can be used as workaround.

**Comment by ethanfrey** [comment]
I thought about this.
Simplest approach is sending 1 token to yourself. It is a noop. And just costs the anti-spam fee.

However, if there is a need to bump eg. 10 or 20 numbers at once (atomic) then this TX type would be useful. Can you produce a clear use case for that? Something that needs more than a self-send?

**Comment by alpe** [comment]
This feature request is inspired by the Stellar bump_sequence command which was introduced for payment channels. The scenario would be the same for us. The command makes sense with a number argument so that it can be >1 indeed.

**Comment by ethanfrey** [comment]
Okay, then there is a transaction as part of x/sigs called `BumpSequence`, that takes an argument. The nonce in the signature must match the current nonce, and this will add the given number in the tx (must be > 0) to the stored nonce.
