### ISSUE TITLE
Don't enforce Protobuf protoc version in `/usr/local/bin/`

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#396]
**Is your feature request related to a problem? Please describe.**
Our `makefile prototools` step downloads and copies the protoc binary into `/usr/local/bin/` folder as well as the definitions into `/usr/local/include/`. While it is ok for us in the team to agree on the version and approach it has the problem that any external contributor has to overwrite his local version, too.

**Describe the solution you'd like**
As @ruseinov pointed out a local protoc in the project with a gitignored bin folder could solve this.

**Comment by ethanfrey** [comment]
This was closed when we dockerized all protobuf tooling for v0.16.0 release
