### ISSUE TITLE
Rethink our sprint planning and boards columns 🧙

### ISSUE THREAD

**Issue by husio** [iov-one/weave#405]
We are terrible with planning enough work for the week :tada: :laughing:  We don't seem to be able to improve on that. Maybe instead of trying any further, we should rethink our process? I like scrum but I think that weekly planning is simply not working for us.

How about removing `Current sprint` column? Instead of `To do`, `Refined Backlog` and `Current split` column I propose only two:
1. `Backlog` - an unordered list of issues. Any new issue is put here. We can drag an issue to a next column only during the refinement when everyone agree that the story is ready for development.
2. `Ready` contains an **ordered** list of ready to work on issues - on top are the most important/urgent.

`Current sprint` column does not exist. To work on a story, drag the very top one from `Ready` column into `In Progress`.

A variation of the above would be to have only one ordered (on top) column that contains both backlog and ready issues. Ready issues are always on top and any new issues are added to the very bottom.

This I believe is a step in the direction of kanban :man_shrugging: and I think this is very close to what we are doing. Slight columns adjustment might make the process clearer.

We can still have a sprint planning call. There will be just no need to drag issues to another board.

It would be nice to summarize our workflow in [How dow we work](https://github.com/iov-one/ops/wiki/How-do-we-work) document.

**Comment by ruseinov** [comment]
I mean, having next sprint column and prioritized/ordered refined backlog column kinda does it. But I agree, extra column is unnecessary.

**Comment by ethanfrey** [comment]
I like this idea. It requires a bit more organization discipline, but cleaner.

Let's discuss this in backlog grooming

**Comment by ethanfrey** [comment]
We agreed and updated the columns, removed labels.

Please update How we work, and we can close this.

**Comment by husio** [comment]
I have added [Blockchain Dev Board](https://github.com/iov-one/ops/wiki/How-do-we-work#blockchain-dev-board) section. Please check.

**Comment by ethanfrey** [comment]
Nice. I added a line for "Backlog":

"Note only product owner should add/reorder items here"

Otherwise, nice write-up
