### ISSUE TITLE
GitHub labels 🏷

### ISSUE THREAD

**Issue by husio** [iov-one/weave#406]
I think the amount and variety of labels we have in `weave` project make it hard to use and understand. My proposal is to delete most of them and declare only a few with a clear description of what they are for.

I believe there are a few sets of related labels. Below is my explanation of why we do not need them.

1. labels `ready` and `validated` are represented by column `Refined backlog`. Often times we are working on issues that do not have `ready` or `validated` label anyway. This is related to https://github.com/iov-one/weave/issues/405
2. `WIP` label is not needed as there is now a pull request draft on GitHub
3. `S`, `M`, `L` and `Split` labels are not used

Right now my opinion that only `blocked` and `bug` labels are truly needed. It might be beneficial to create a few more with a precise description and a clear use case in mind.

It would be nice to summarize how to use labels in [How dow we work](https://github.com/iov-one/ops/wiki/How-do-we-work) document.

**Comment by kmw101** [comment]
I have removed the S,M,L and Split labels. The idea was to do some task estimation but that has not been enthusiastically adopted and so are not needed.

If we move to Kanban then I would like to see some Feature or Epic labels so I can have an overview of what is being done and it will help me prioritise the board.

**Comment by ethanfrey** [comment]
We have done some cleanup.
Please do through current labels and give a concrete proposal of what is left to remove.

I think we considered some topics such as orm, performance etc as useful for the auto-generated release logs. Some other "process" ones may still need cleaning

**Comment by husio** [comment]
My proposal is to remove almost all tags and add new one only when needed with a clear description for the label.
I propose that tags are using for mostly visual labeling of important topics, not for categorizing. Categorizing is not wrong, we just dont need it.


## Keep

I would keep only two labels. They mark an issue and provide a good visual alert for important topics.
- blocked - someone cannot continue work, this is important
- bug - something is broken and we want it fixed soon, this is important

## Remove

I woud remove all other labels. Almost all of them categories issues according to what area they about, which should be the content of the issue, not the tag.

- design - we have a column for this now
- docs - redundant as this information can be provided by the title of an issue being for example `write documentaion for X`
- orm - redundant, similar to docs tag
- performance - redundant, similar to docs tag
- invalid - not helpful. If an issue is invalid we remove it from the board
- question - redundant. Finish your sentence with `?` instead 
- cleanup - I am not that sure about this one. I think [it does not spark joy](https://duckduckgo.com/?q=does+it+spark+joy&t=canonical&ia=web)

**Comment by ethanfrey** [comment]
I agree with invalid and cleanup.

In the first "unsorted ideas" column there are various topics that I have not looked at, some I look at, refine and drag into the backlog, and others I need more feedback before continuing. I like the "question" or "discussion" or "design" (**one** of the three) to signal that I need feedback from devs before moving on it (to attract your attention). This label should never make it out of the "unsorted ideas" column

The others that remain categories: `docs`, `orm`, `performance`
I use them to categorize, but it is not really needed. However, I think the release note builder depends on them. I would like feedback from @alpe here on the utility

**Comment by husio** [comment]
If you find `orm`, `docs`, `design` etc useful than maybe we should keep them and give them the same, pastel color. This way they can be used without visually attracting attention.
I will test this idea now.
