### ISSUE TITLE
Improve high-level benchmarks, sending coins with fees at abci level

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#408]
Followup story https://github.com/iov-one/weave/issues/284

**Comment by husio** [comment]
Initial work is in https://github.com/iov-one/weave/tree/benchmarks_on_real_bnsd branch. It appears to be harder to write than initially expected.
For now, waiting for the development of https://github.com/iov-one/weave/issues/375 I think that having a `bnsd` client would make this task much easier.

**Comment by ethanfrey** [comment]
Please take the time to refactor the abci level benchmarks well. Especially to consider the api you want. I think we made huge progress on adding clarity this morning.

Writing over tendermint is harder than directly on the app, but we would like to expose a similar interface. And would need to add more features as well. 

 Once we get clarity on apis from this refactoring, we will be much clearer on what we want from a client

**Comment by ethanfrey** [comment]
:tada:

**Comment by husio** [comment]
Slowly getting "there" with the tests :wink:
