### ISSUE TITLE
Allow app.ChainDecorators to accept nil

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#414]
**Is your feature request related to a problem? Please describe.**

If we want to optionally enable a decorator, we have to create a slice with all other decorators, and in an if statement, splice this in if needed.

**Describe the solution you'd like**

Simpler would be to use the if statement to return either the decorator or nil, and just pass that into ChainDecorators. Decorators.Handle() would just silently skip any nil Decorators as if they were not passed in. Makes a more convenient API with no run-time overhead.

**Comment by ruseinov** [comment]
I'd go for returning (decorator, err) and have a predefined err like ErrDisabled or something similar to check on.

Could be somewhat cleaner than just nil check and more idiomatic.
