### ISSUE TITLE
Add Elections Extension

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#419]
TODO: define this.

We can do all on-chain voting instead of multisig for MvP, as this moves the burden of work from frontend into backend. As it seems backend is moving faster now.

Let us look at some examples (eg. cosmos, aragon, dfinity) for voting systems. 

`MakeProposal`: defines what is to be voted on, time limit of election... maybe multiple transactions needed here to define different proposal interactions. Somehow we auto-determine who is eligible to vote on this (cannot come from user). This will be quite hard to define well from a technical side, and maybe push for changes inside the weave framework. In any case it should return a proposal id.

`CastVote`: Takes a proposal id and boolean (for/against) or enum (for/against/abstain) Casting a vote is quite easy, and then can trigger an action when enough have been cast. Or do we wait for the end of the election period, even after hitting the threshold?

Let's think about this more....

Also, please read up [the (wip) governance voting app spec](https://docs.google.com/document/d/189078Dja8oCRAP7P8SANuk5-1-UfTTVq6tm2aDyg0Fo/edit?usp=sharing) to see this from the end-user perspective

**Comment by ethanfrey** [comment]
Here is the simple (text only) implementation for cosmos-sdk

3 messages in their handlers (propose, deposit, and vote): https://github.com/cosmos/cosmos-sdk/blob/develop/x/gov/handler.go

(one thing I do like there, is a type-switch over all expected message types in one place. Maybe we can consider that for #432 - one handler per package it gets message, validates it, then type-switch dispatches it for different message types. would unify the first filter in one place).

Handlers look simple, but here is all the logic really: https://github.com/cosmos/cosmos-sdk/blob/develop/x/gov/keeper.go (also they don't do much filtering on check nor do they estimate gas cost)

They also have this lovely logic to be called at the end of every block to check to see if any inactive proposals times out, or active proposals ended the election period (and do tally). https://github.com/cosmos/cosmos-sdk/blob/develop/x/gov/endblocker.go

We don't want to copy them, but I do think it is worth reading this to get some insights (and maybe open up new issues to improve weave design)

**Comment by alpe** [comment]
I have wrote a couple of questions and options inspired by the cosmos-sdk into this google [doc](https://docs.google.com/document/d/1d15D7pfP9NSIQ2fUOQRd-9RueymZaILqmatv3qzL5YY/edit?usp=sharing).

**Comment by ethanfrey** [comment]
We should do a proper product overview on this. If I don't write up something by Monday, please remind me

**Comment by ethanfrey** [comment]
This has been done. Great job all!
