### ISSUE TITLE
Cleanup escrow tests

### ISSUE THREAD

**Issue by husio** [iov-one/weave#420]
The current implementation of `x/escrow` tests for handlers is a nontrivial piece of code. Where possible, simplify it.

[The current tests](https://github.com/iov-one/weave/blob/master/x/escrow/handler_test.go#L47-L57) simulate a working application that is processing given transactions. After processing all transactions the buckets are inspected to ensure expected state. 

Simplified version of this approach [can be found in `x/paychan`](https://github.com/iov-one/weave/blob/master/x/paychan/handler_test.go#L39-L40) and [`x/distribution`](https://github.com/iov-one/weave/blob/master/x/distribution/handler_test.go#L369-L375) extensions as well.

- [ ] update table tests to use `map[string]struct{...}` as a register
- [ ] update structure declarations to use `Key: value` to declare a value instead or anonymous values 
- [ ] extract [`action`](https://github.com/iov-one/weave/blob/master/x/escrow/handler_test.go#L835) to `weavetest` and make it useful to any extension (ie `x/paychan`). This functionality should simplify writing tests where we want to process transactions and introspect the state
- [ ] the above might require extraction [`query`](https://github.com/iov-one/weave/blob/master/x/escrow/handler_test.go#L859) as well

**Comment by ethanfrey** [comment]
Too lazy to fix more....

N'ah escrow looks better, good enough for me
