### ISSUE TITLE
Distriubtion condition must match regexp for validation

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#425]
## Expected Behavior
Condition in: https://github.com/iov-one/weave/blob/master/x/distribution/model.go#L120  must match https://github.com/iov-one/weave/blob/master/conditions.go#L23

## Actual Behavior
It fails as the prefix `distribution` is >8 chars as defined in the regexp

**Comment by ethanfrey** [comment]
Yes, let's call it distrib.

I was trying to keep it all short strings. 

Or we can make the limit higher.
