### ISSUE TITLE
Introduce a new decorator to call message syntax validation

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#432]
**Is your feature request related to a problem? Please describe.**
There is a common pattern in handlers where the incoming data is validated before processing them (usually). For example
```
	rmsg, err := tx.GetMsg()
	if err != nil {
		return res, err
	}
	msg, ok := rmsg.(*SendMsg)
	if !ok {
		return res, errors.WithType(errors.ErrInvalidMsg, rmsg)
	}

	err = msg.Validate()
	if err != nil {
		return res, err
	}
```
https://github.com/iov-one/weave/blob/master/x/cash/handler.go#L76-L88

**Describe the solution you'd like**
It would be nice to have an interface that defines the `Validate()` method for syntax validation and sanity checks and have this implemented on all message types. It can be called from a decorator then so that handlers work on valid data only. This would remove code duplication and assures a clear process where input validation comes before auth checks (located in the handler).

**Comment by ethanfrey** [comment]
I am happy to extend the `Msg interface` in weave/tx.go as needed. This definition is almost a year old.
So yeah, adding `Validate() error` to that interface makes sense.

As to the decorator, you would suggest an actual Decorator somewhere in the stack that gets and validates the message? Or wrapping each Handler.

The issue with moving the validation into the stack is that it may not be included in one app. (Sure, we could put it in the Router, then). Also, all unit tests on a Handler must be careful to only include valid data (and we only test validation rules in AT).

If you mean decorator in the sense of `func ValidatingHandler(h Handler) Handler`, then I am in full agreement. Any handler can wrap itself in `New` and then just have this magic power :)

Or maybe a more go-like way of embedding this.

I like the idea, and I would really like to abstract out the type-cast as well, but that is impossible in golang afaik.

**Comment by alpe** [comment]
> Also, all unit tests on a Handler must be careful to only include valid data (and we only test validation rules in AT

👍 A decorator that implements the `weave.Handler` interface and wraps the handler in `New` would do the job as well and supports existing tests.

**Comment by husio** [comment]
Are you having something like this in mind?

```go
func validateTransaction(tx weave.Tx) error {
        msg, err := tx.GetMsg()
        if err != nil {
                return errors.Wrap(err, "cannot get message")
        }
        if v, ok := msg.(validator); ok {
                return v.Validate()
        }
        return nil
}

type validator interface {
        Validate() error
}
```

**Comment by ethanfrey** [comment]
@husio Yes, I think something like that, but if we make `Validate` required on the `Msg` interface, we always check that. And I think it is safer to require it.

**Comment by ruseinov** [comment]
That sounds reasonable, as it does remove the boilerplate of casting/validating from Check and Deliver.
We'll still have to validate some other things though like this (example from cash SendHandler):
```
	if !h.auth.HasAddress(ctx, msg.Src) {
		return res, errors.ErrUnauthorized.New("Account owner signature missing")
	}
```
and I keep wondering if we could have a common method in each Handler that includes these as well (and maybe a helper for validateTransaction).  In that case we won't need an extra handler to register that does only this validation, which makes it a bit more straightforward and less magic.

**Comment by ethanfrey** [comment]
@alpe I was thinking a bit more on this... We can make bigger changes as well....

If I try to model logic from eg. webapps, I usually run validate on the beginning. That would be where we parse. eg.  `cmd/bnsd/app/app.go` takes a TxDecoder when constructing the application: 
`func Application(name string, h weave.Handler, tx weave.TxDecoder, dbPath string, debug bool) (app.BaseApp, error)`, this is set in `GenerateApp` to be `cmd/bnsd/app.tx.go:TxDecoder`.

```go
func TxDecoder(bz []byte) (weave.Tx, error) {
	tx := new(Tx)
	err := tx.Unmarshal(bz)
	if err != nil {
		return nil, err
	}
	return tx, nil
}
```

What if we run the above validateTransaction logic there?
Change `weave.TxDecoder` to `func(txBytes []byte) (Tx, Msg, error)` returning a validated message as well.
Then the handlers don't even deal with the tx, but only with a validated message:

```golang
type Handler interface {
	Check(ctx Context, store KVStore, validMsg Msg) (CheckResult, error)
	Deliver(ctx Context, store KVStore, validMsg Msg) (DeliverResult, error)
}
```

Handlers never use the Tx except to get the message, while the Decorators are the ones that need to process the Tx envelope (and generally/always don't touch message).

We could then also update Decorator to 

```golang
type Decorator interface {
	Check(ctx Context, store KVStore, tx Tx, validMsg msg, next Checker) (CheckResult, error)
	Deliver(ctx Context, store KVStore, tx Tx, validMsg msg, next Deliverer) (DeliverResult, error)
}
```

Hmmm... I'm starting to feel this is getting too big, but yeah, wanted to throw on the table we can change interfaces if it increases usability

**Comment by ethanfrey** [comment]
@ruseinov The issue with checking permissions is that it is quite dependent on the handler. For example the escrow handler needs to read the escrow item and then determine which addresses are valid. And multisig as well.

**Comment by ethanfrey** [comment]
Wait... more brainstorming...

Why don't we just define `tx.GetMsg() (Msg, error)` to include `validateTransaction`, and also return validation errors (not just parse errors). This will work without any new decorators or code changes. We just have the type casting to deal with

**Comment by ruseinov** [comment]
> Why don't we just define tx.GetMsg() (Msg, error) to include validateTransaction, and also return validation errors (not just parse errors). This will work without any new decorators or code changes. We just have the type casting to deal with

This sounds good, then we have a more explicit way of calling this and deal with the rest of common code on a per Handler basis.

**Comment by alpe** [comment]
Good points from everybody! Very valuable ideas 💐 
I think having some code in the framework rather than to build it into each handler constructor feels more efficient. I liked the idea to not touch the tests in the beginning but if we really want to aim for simplicity, then the new `Handler` interface that @ethanfrey proposed makes much more sense to me. Handlers should just work with messages and context data.
About the `Decorator` interface, I would keep the existing one for now. Only `batch` and `msgfee` would benefit from the additional parameter. For the others it would just be noise. `tx.GetMsg()`  and msg param could be confusing, too.

@ruseinov I kept authz out of this issue by intention. It feels like a small change but when it comes to contracts it is not so simple anymore as data needs to be loaded and individual rules applied. That would be possible, too with some redesign as the general workflow is like:  msg validate, load contract, apply contract based authz. But let's have another design issue after this one is implemented

**Comment by ruseinov** [comment]
@alpe I figured as much, I mentioned it to emphasise that we still need a common place in most handlers to do these repetitive operations on auth, so instead of introducing a decorator we could incorporate a nice helper and call it explicitly within our handlers via embedded object or just static helper method.

**Comment by ruseinov** [comment]
Although I agree, that not calling this at all would be beneficial, but could be prone to errors due to not adding it to a certain app :)

**Comment by ethanfrey** [comment]
I think the authz check already has a helper. I mean how much shorter can you get than

```
if !h.auth.HasAddress(ctx, msg.Src) {
    return res, errors.ErrUnauthorized.New("Account owner signature missing")
}
```

The majority of the text is setting the error message

**Comment by ruseinov** [comment]
Yeah, what I'm saying is should be conform to a pattern in our handlers, where both Check and Deliver utilise a function like checkAllStuff which would include whatever authz and validation helper call.

It's just an impl detail, just something I thought as an alternative to handler/packing it into GetMsg

**Comment by ethanfrey** [comment]
Yeah, `checkAllStuff` is a `validate` function on each handler.
All the common checks are those listed above by Alex, which we want to reduce or eliminate (by hiding them in the framework).
All other checks are unique per handler, and I see no benefit (either in code quality, readability or programming speed) to try to abstract them. Unless you can show me the same logic in 5+ handlers.

**Comment by ruseinov** [comment]
I was not really talking about abstracting authz logic, I was talking about following the same pattern of having a checkAllStuff method in each handler to abstract it's own logic out for both Check and Deliver, nothing more. Like a pattern, that could also be enforced by an interace.

**Comment by ethanfrey** [comment]
We use a private `validate` method in (almost) all handlers that does what you asked. Validating the message and checking type, loading any related model, and checking auth.

But maybe I don't understand you. Can you provide a concrete example of what you think is better as a gist or draft pr, so I can review?

**Comment by ethanfrey** [comment]
We solved this with the `LoadMsg()` method now used in all Handlers. I think this resolved all actionable points for this issue.
