### ISSUE TITLE
Move `Memo` and `ChainID` to top level Tx codec

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#435]
**Is your feature request related to a problem? Please describe.**
* `Memo` - is a free text field that can be used to submit extra information by the sender
* `ChainID` - is the name of the blockchain and used to prevent replay attacks
We should be on the safe side with replay attacks on all our messages. We should also enable custom metadata with every message to allow use cases that we have not planned for.

**Describe the solution you'd like**
By moving both fields to the top level Tx of [bns](https://github.com/iov-one/weave/blob/master/cmd/bnsd/app/codec.proto#L25) and [bcp](https://github.com/iov-one/weave/blob/master/cmd/bcpd/app/codec.proto#L22) we can achieve this with very small changes. The field validation should not be hard to integrate into the new [validation logic](https://github.com/iov-one/weave/issues/434).

**Describe alternatives you've considered**
Validation can also be done in a decorator to exit fast.

**Comment by ethanfrey** [comment]
Right now many of the messages have a memo field. Moving to top level makes sense in a sort of DRY logic, however, if we have batches, that means we can only have one memo per batch, not one per message. Having memo both places is quite confusing for the client side.

ChainId is included in the signature calculation and never serialized. This is the design from both ethereum and cosmos-sdk. The only purpose is to prevent cross-chain replay attacks. Currently this is handled in [BuildSignBytes](https://github.com/iov-one/weave/blob/a921d894f58cb615d5dd22da0fa143d15f94f2e4/x/sigs/controller.go#L94-L124)

Explicitly including this information in every transaction would increase all transactions by something like 10-20 bytes (around a 10% increase) without providing additional security, only ease of debugging when sending transactions to multiple weave chains. (Current error message in this case is simply `Invalid Signature`). I don't think it is worth it.

Re: memo, if you want to develop your thoughts on that more, I would like to hear, I think we can do better than current design, although I have some reservations with Batch

**Comment by alpe** [comment]
Good points! I did not see the ChainID in the Tx but it makes sense now.
About batch: it does not play nicely with memo indeed. To define it twice at Tx and message level feels wrong, too. So I will close this now until I have some better use cases other than removing duplicate code.
