### ISSUE TITLE
Keytagger must not tag fee collector address

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#445]
**Is your feature request related to a problem? Please describe.**
With an anti spam fee >0 set, every Tx submitted to the system will be marked by the [keytagger](https://github.com/iov-one/weave/blob/master/x/utils/key_tagger.go) [decorator](https://github.com/iov-one/weave/blob/master/cmd/bnsd/app/app.go#L49) with the collector's address. The keytagger sets the tag(s) for tendermint indexes so that they can be used for queries. 
A tag that is set on **every Tx** is not useful for queries and only consumes unnecessary resources in the index system.

**Describe the solution you'd like**
The keytagger should not tag the fee collector address. To achieve this it could be started with a reference to the `gconf` store so that it can use the the current collector address to exclude it from the tag list.

**Comment by ethanfrey** [comment]
I agree with the sentiment.
I would argue that this decorator shouldn't understand all the details of gconf.

Rather, it should accept a list of addresses to skip in its constuctor.
More likely a function `func (store ReadonlyKVStore) []Address` which it calls the first time it is executed and gets that list. In eg. `bnsd/app` we can define a function that loads any addresses for gconf or other bucket.

**Comment by alpe** [comment]
My assumption about the fee collector address was that it is not fix and can be updated via the gconf store in the future. Although we do not support this now.

**Comment by ethanfrey** [comment]
Then, it can run the query for blacklist addresses to tag once a block if you prefer. Same as you suggest, just more flexible. I don't like hardcoding this one configuration value in the KeyTagger code. Unless you are sure this will never happen with any other key.

Or just query every time and add gconf caching to avoid unnecessary reads from disk

**Comment by alpe** [comment]
Of course I can not give a guarantee that we will never add new addresses to the blacklist. We will adapt the logic as we learn about the use cases. My main concern was how to keep that blacklisted address list up to date. My idea was query gconf from the decorator and let gconf take care of caching and updating logic. Same as you pointed out.

**Comment by ethanfrey** [comment]
The more I think about this, the less I like this idea.
Maybe I don't want to mark the tag every time I collect fee. But I would like to tag when money *leaves* the fee collection address.

How about adding some extra option on the `Bucket.save()` interface, like "don't tag" that can control the keytagger actions for that action, not for the address
