### ISSUE TITLE
Move timeout point to expired state (for atomic swaps)

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#446]
As discussed, the `timeout` should be the first point in time at which the atomic swap is invalid/expired. I.e. _claim_ is allowed in the range [start, timeout) and abort/refund is allowed in [timeout, ∞).

In https://github.com/iov-one/weave/commit/65f32d7d72b4fe15c3814b50d26784433853d156 the timeout point changed to the non-expired case.

- [x] Document what timeout means (e.g. _The first point in time at which the offer is expired._)
- [x] Build failing test case with the current implementation
- [x] Adapt `isExpired` implementation

**Comment by ruseinov** [comment]
Guess this is blocked by https://github.com/iov-one/weave/pull/490, so I'll get back on it once it is done.
