### ISSUE TITLE
Reduce timeout resolution in client/backend interface

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#447]
Can we reduce the resolution of atomic swap timeouts? Weave now uses google.protobuf.Timestamp, which has nanosecond resolution. However, this cannot easily represented in other environments like JavaScript. The best we get out of JavaScript is millisecond resolution. This leads to the issue that we cannot parse the value from the blockchain without losing information.

I’d prefer to use simple UNIX timestamp integers in seconds instead of complex Date types in the client/backend interface.

**Comment by webmaster128** [comment]
The main issue I am seeing here is that we lose information when decoding the blockchain transaction to simple JavaScript. I.e. `encode(decode(tx)) != tx`, which should never happen. If we really need nanosecond support, we have to create an `{ seconds: number, nanos: number }` object in JS instead of just Date, string or number. But I think we should have a simper type that works out of the box with JS (like uint64 UNIX timestamp seconds).

The potential issue with fractional seconds is that, dependent on the implementation of the system clock, time is not guaranteed to be monotonic, i.e. an escrow can jump from non-expired to expired to non-expired to expired in case of leap seconds (see https://en.wikipedia.org/wiki/Unix_time#Non-synchronous_Network_Time_Protocol-based_variant). This can be avoided entirely if the time resolution is seconds.

**Comment by ethanfrey** [comment]
We should either use the unix timestamp as suggested above.
Or at minimum round off all stored data to only consider the whole seconds

**Comment by husio** [comment]
I understand @webmaster128 concerns and I think this is fair. At the same time, I think it is very important to use proper types where possible in our Go code.

Maybe we should provide a type that will represent a UNIX time and be a type that means something in Go. For example:

```go
type UnixTime int64

func (t UnixTime) Time() time.Time {
    return time.Unix(t, 0)
}
```

[Our protobuf definition](https://github.com/iov-one/weave/blob/9840938a8ba63ef3d86a2bd268d34789b26ea43c/x/escrow/codec.proto#L41) would be changed to
```protobuf
message CreateEscrowMsg {
  // ...

  // Timeout represents wall clock UNIX time value.
  int64 timeout = 5 [(gogoproto.casttype) = "github.com/iov-one/weave.UnixTime"];
}
```

**Comment by ethanfrey** [comment]
Yes, the above reason about proper types is why I liked timestamp.
The issue with nanoseconds compatibility is valid.

I think the solution by @husio of the UnixTime type is quite nice. With the addition of `func ToUnixTime(t time.Time) UnixTIme` helper for the other translation
