### ISSUE TITLE
QA End to End test scenarios : Governance

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#451]
The end-to-end tests need creating around functioning Governance.

Requirements from the business:
------------------------------------
--- we need to be able to test governance multi-sig functionalities:
--- set up/registration of the governance public keys
--- adding/removing validators address to the validators address list.
--- updating chain parameters

Add a new Governing member:
-----------------------------------
1) Add a Governing member with a valid key
2) Add a Governing member with an invalid key
3) Add a Governing member with a duplicate key

Add a new Validator
-----------------------
1) Governing board create a proposal to add a Validator
2) Governing board (non-Validator) vote to accept the new Validator
3) Governing board (non-Validator) vote to reject the new Validator
4) Test to see if a Governing board member who is a validator can vote.
5) Governing board create a proposal to add a Validator who is already a Validator (can I add a duplicate?)

Remove a Validator
---------------------
1) Governing board create a proposal to remove a Validator
2) Governing board (non-Validator) vote to remove the Validator
3) Governing board (non-Validator) vote to reject the removal of the Validator
4) Test to see if a Governing board member who is a validator can vote.

Set the fee distribution proportion to Validators
-----------------------------------------------------
1) Governing Board member proposes the fee distribution - distribution adds up to 100%
2) Governing Board member proposes the fee distribution  - distribution adds up to 120%
3) Governing Board member proposes the fee distribution  - distribution adds up to 95%
4) Governing Board vote to accept the fee distribution
5) Governing Board vote to reject the fee distribution
6) Fee distribution accepted, fee distribution is made to the validators
7) Validator set is updated, if applicable.

**Comment by ethanfrey** [comment]
Nice set of test cases.
We should cover all these with unit tests while completing #419 
As the governance system is moving to proper elections, we will need new formal unit and integration tests for that

**Comment by kmw101** [comment]
business requirements change, test cases outdated.
