### ISSUE TITLE
QA End-to-End testing : Economics

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#452]
Following discussions with Business the following scenarios need testing:

Economics
-------------
-- As I understand it, the MPV economic design works as follows:
a) user get credited X token from faucet
b) user do a transaction with fee (send token, register name, edit address for name, etc)
c) fees are collected into a contract
Then
d) governance submit a multi-sig transaction distributing these fees to: the addresses in the validators address list, with a % (or weight) associated with each validator address.
e) the fees are split and received on the validators addresses
f) the validators are users, go back to b).

Set up a number of users
----------------------------
1) Write a test script to generate 300 users `iov_qa_test_0` to `iov_qa_test_299`
2) Run the user generator script
3) Check the balance of the fee distribution that 300 * `min_fee` has been credited

Generate send transactions
------------------------------
1) Write a script that sends 500 tokens of random quantities between 1.0 and 0.00001 to the users created.
2) Run the script to send the tokens.
3) Check the balance of the fee distribution that 500 * `min_fee` has been credited
4) re-run steps 1-3 several times.

Fee distribution
--  See Governance tests

**Comment by ethanfrey** [comment]
Okay, these are covered with unit tests and acceptance tests.
We only run through the high-level scenario (talking to tendermint on a running chain) with one or two user accounts, but is there a need to run the same code 500 times?
The only benefit I see there is benchmarking, but that was not in this request.

**Comment by kmw101** [comment]
The thinking behind the 500 tests was to thoroughly test the calcs and ensure the running balances work. I have been caught in the past where a simple test worked but volume caused issues.

If this is covered in benchmarking then feel free to close the issue.

**Comment by ethanfrey** [comment]
We can add checks in benchmarking, I think.
Don't close yet. No benchmarks exist to test this explicitly

**Comment by kmw101** [comment]
Benchmarking scenarios is still open, the rest of the discussion is covered by existing tests. closing
