### ISSUE TITLE
Weave documentation : References to IOV-CORE examples need removing

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#464]
There are references to the IOV-CORE examples, these are outdated or incomplete and need removing from the documentation:

References:
- [x] [Install client cli](https://weave.readthedocs.io/en/latest/mycoind/installation.html#install-client-cli)
- [x] [Run some Client examples](https://weave.readthedocs.io/en/latest/mycoind/installation.html#run-some-client-examples)
- [x] [Using Iov-Core](https://weave.readthedocs.io/en/latest/mycoind/iovcore.html#using-iov-core) - Is the TODO needed ? Or can this be removed ?

**Comment by ruseinov** [comment]
Docs are important
