### ISSUE TITLE
Standarize commit messages

### ISSUE THREAD

**Issue by husio** [iov-one/weave#465]
Because I do not want such a small thing to become an issue, I would like to discuss our commit message format. Do we need one? If yes, what should it be?

I know that @alpe [likes upper case letter start letters for PR titles, commits and error logs](https://github.com/iov-one/weave/pull/461#pullrequestreview-221025451).

I do not think there is a rule or a reason why to choose certain rule over another (ie first line must or must not be a sentence), so we are free to decide on whatever. I guess there is no wrong choice here.

If you care, please write below your opinion. If you do not care, write "I do not care".

## Acceptance criteria
- [ ] if we come to a conclusion, add a sentence of documentation to https://github.com/iov-one/ops/wiki/How-do-we-work

Note: from @ethanfrey : We can do this with the Dangerfile. Maybe also update how the checks are run (outside of TravisCI)

**Comment by ruseinov** [comment]
I think it is nice to avoid having really short commits like "fmt", "fix" etc, and generally nice to start them with a capital letter, which is what I do now. However, I also think that focusing on commit format and enforcing some serious rules there is a waste of precious focus and time.

Just in general I think keeping things clean is nice, but micromanagement is not necessary and could even be disruptive/frustrating.

I do remember working on projects when some formats were enforced both in code and commits, and the problem is that a certain format comes to some people naturally, but others could struggle. So in the end you have to put yourself into someone else's shoes to do your work in a certain format.

I will give you an example:
I have deployed a tendermint image to test chatbot deployments, but forgot to add "v" prefix to image version and things broke. Why? Because for me a version is a number separated by dots which does not need "v", because it's redundant. For some people it's the other way around. So the more we enforce certain processes according to someone's taste - the more we could potentially slow down the other people involved.

**Comment by alpe** [comment]
I think we all work on a very professional level with our code. The git history on the other hand looks not as good as it could be. See other IOV project like iov-core or demo-wallet for better examples.

Starting a commit or PR with an upper case letter may not feel like a big achievement but to me it shows if a team cares about their meta data, too.
I did a quick 2 min search and could not find a major project with mixed cases. It is just that we do it different.

> Because for me a version is a number separated by dots which does not need "v", because it's redundant.

I don't want to make this the topic but this is the common case in Go world, too. Just check Gopkg.lock

**Comment by ethanfrey** [comment]
> I will give you an example:
>  have deployed a tendermint image to test chatbot deployments, but forgot to add "v" prefix to image version and things broke. Why? Because for me a version is a number separated by dots which does not need "v", because it's redundant. For some people it's the other way around. So the more we enforce certain processes according to someone's taste - the more we could potentially slow down the other people involved.

Tendermint has been publishing their images without the v (non-standard for a long time). They added the v on the 0.31.2 (yes, patch) release. The non-standardization here is what causes troubles, exactly the opposite of your argument (you were not sure whether it needed it or not).

**Comment by ethanfrey** [comment]
I like the idea of clean messages, that look like sentence.
Let's just include reviewing commit messages in the PR review process :smile: 
Seems like a simple first step. We can add more criteria later, if we like to.

**Comment by husio** [comment]
I agree that we can improve our git commit messages. If capitalizing the first line makes it better than let us do this. At the same time I agree with Roman that what for one can be better, for the other can be worse. Third person may not see a difference.

For me format of commit messages is not as important as the content. But if the format is important to others and it can make our project better then lets do this! 


> I did a quick 2 min search and could not find a major project with mixed cases. It is just that we do it different.

Those projects are all not starting their commit messages with capitalize letter or at least contain mixed format messages
- git https://github.com/git/git/commits/master
- linux kernel https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/
- Go https://go.googlesource.com/go/+log


My point is that I do not think there is right or wrong. We are free to choose whatever convention we feel like without any reason given. That is fine.

**Comment by ruseinov** [comment]
I must say that I see no benefit in caring about first capital letters at all, as ultimately it does not increase readability or bring any other benefit, except for subjective one. 

I do think that meaningful messages are good to have in general, maybe also mentioning the component, like `batch: optimize duplicates` similar to repos @husio mentioned

**Comment by husio** [comment]
During the refinement, we did not pull this issue into the ready column because we are missing a proposal. Please propose changes so that we can discuss them next time.

---

I think that having a manually maintained changelog file solves the original issue.

Maybe it would be an improvement if we start our commit message with the package that the change is made for ([example](https://github.com/iov-one/weave/commit/76e088192a325c58016f44b763c10651e9e41afa)).

**Comment by ethanfrey** [comment]
@alpe 

I think we are doing better with the commit messages. And this issue is lying around for a while.

Can you either confirm this is better and mark it as done, or make a very clear change request/PR that can be actioned on?
