### ISSUE TITLE
Maintain a CHANGELOG file

### ISSUE THREAD

**Issue by husio** [iov-one/weave#466]
> [Don’t let your friends dump git logs into changelogs.](https://keepachangelog.com/en/1.0.0/)

While picking up https://github.com/iov-one/weave/issues/437 I have realized that this will be a breaking change. This must be included in the README compability table later. It should be also included in our release description.

Our [current approach](https://github.com/iov-one/ops/wiki/Release-notes) is to use a tool that generates release notes from commit messages. I believe we can do better.

Unless someone would like to propose a better format, here is an example of a CHANGELOG file

```
## HEAD
- Updated weave.Msg interface to contain Validate method
- Added x/foo package for working with FOO coins
- Removed the use of x/namecoin in cmd/bnsd

## 0.13.1
- Removed x/oldext extension. All code using it was deleted before.
- Added more tests to the x/untested extension

## 0.12.0
- Added foo
```

When making a release, `HEAD` section is renamed to the release number and a new `## HEAD` section is aded.
Changelog update is part of the functionality commit and should be reviewed as part of the changeset.

## Acceptance criteria
- [x] Agree on a changelog file format and update https://github.com/iov-one/ops/wiki/How-do-we-work
- [x] Remove https://github.com/iov-one/ops/wiki/Release-notes
- [x] create a `CHANGELOG.md` file
- [x] backport last ~3~ 2 releases into changelog file

**Comment by ruseinov** [comment]
I do like the idea of Changelog.

I'm not such a big fan of maintaining it, but ultimately if every person who completes an issue updates a changelog with these changes before merging - it shouldn't be a burden and could be a very nice overview of progress/changes.
