### ISSUE TITLE
Easter Egg Hunt  🐰🥚

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#468]
Let's take the time to go through the repo and hunt down the funny smells of rotten eggs. I'm sure some of this code needs some freshening. Imagine you were auditing this codebase... what parts would make you uneasy.

(The number of TODOs, particularly in app and store is a good place to start)

Let's go through the packages and create a cleanup issue for anything you find fishy (one per package, can break them down later). Maybe it is all fine. After checking it, tick it off the list and put your name on the right side. (Someone can double-check if they really want to).

- [ ]  _global_ #532
- [x] weave @ruseinov  #480 #492 
- [ ] app
- [ ] cmd/bcpd
- [ ] cmd/bnsd
- [ ] coin #475 
- [x] commands/server @ruseinov 
- [x] crypto @ruseinov 
- [x] errors @ruseinov #494 #513 #529 
- [x] gconf #456
- [ ] orm  #536
- [x] store @ruseinov #521
- [ ] store/iavl
- [x] tmtest @ruseinov 
- [x] weavetest
- [ ] x
- [x] x/batch @ruseinov 
- [ ] x/cash
- [ ] x/currency
- [ ] x/distribution
- [ ] x/escrow
- [x] x/hashlock @ruseinov #514
- [ ] x/msgfee
- [ ] x/multisig
- [ ] x/namecoin
- [ ] x/nft @ruseinov 
- [x] x/nft/base @ruseinov #515 #533
- [ ] x/paychan #481 
- [ ] x/sigs 
- [x] x/utils @ruseinov #519
- [x] x/validators @ruseinov  #485  #527

**Comment by ethanfrey** [comment]
Also nice to add a doc.go file in each package missing one when you go through it (can make mini-prs)

**Comment by husio** [comment]
Done.
