### ISSUE TITLE
Elections: Allow changing votes

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#469]
"Brexit use case"

We are running an election and I voted, but the next day I sober up and realize what an idiot I was. Luckily the election is still going on for a few days, so I want to be able to submit a new transaction to override my original vote.

Note this will not double-vote, but update it.

Question: should this be default behavior of submitting two votes on same proposal? or should we require a special "modify vote" transaction?

**Comment by kmw101** [comment]
I would favour a modifyvoteTX which would keep things cleaner.

**Comment by ethanfrey** [comment]
Tending towards simplified format. One VoteTx, override if already present. Make sure they can never record two votes on one proposal.
