### ISSUE TITLE
Number in currency code causes crash

### ISSUE THREAD

**Issue by jpincas** [iov-one/weave#47]
- whilst messing around with `init` I created a currency "CASH2" (as you do)
- when starting the blockchain, I get a panic with message `panic: CASH2: Invalid currency code`
- so, either we validate currency names to stop numbers (and other symbols etc?)
- or we do something about the actual panic

**Comment by ethanfrey** [comment]
Thanks for this report.
We do validate that the currency code is 3-4 upper case letters, hence the error.
But you are right, we shouldn't panic, but rather print a sensible error message about invalid genesis file and exit the app.

The fact there is no way to gracefully exit here is related to issue https://github.com/tendermint/abci/issues/165

> In short, only those that take user input (CheckTx/DeliverTx/Query/SetOption) can report over the quality of the execution with codes (ie. codes for OK, Not-OK-Because-X, OK-But-Y). The rest should have no possibility for error, since it's not defined what to do in those cases. Thus it seems right that eg. InitChain, BeginBlock, etc. should panic on error - we just need to make sure the panic is caught in the right place and turned into ResponseException so Tendermint can shutdown gracefully.

**Comment by ethanfrey** [comment]
ABCI implementation code for reference (`app/store.go`):

```
func (s *StoreApp) InitChain(req abci.RequestInitChain) (res abci.ResponseInitChain) {
	bz, err := ioutil.ReadFile(s.genesisFile)
	if err != nil {
		// I'm sorry Alex, but there is no other way :(
		// https://github.com/tendermint/abci/issues/165#issuecomment-353704015
		// "Regarding errors in general, for messages that don't take
		//  user input like Flush, Info, InitChain, BeginBlock, EndBlock,
		// and Commit.... There is no way to handle these errors gracefully,
		// so we might as well panic."
		panic(err)
	}

	return s.InitChainWithGenesis(req, bz)
}

// InitChainWithGenesis mocks out what we want for tendermint 0.17
func (s *StoreApp) InitChainWithGenesis(req abci.RequestInitChain,
	data []byte) abci.ResponseInitChain {

	err := s.parseGenesis(data, s.initializer)
	if err != nil {
		// I know, read above...
		panic(err)
	}
	return abci.ResponseInitChain{}
}
```

**Comment by ethanfrey** [comment]
We could replace panic with an explanation and `os.Exit(1)`, but that is worse in my opinion (ever had a test case just fail with no info, so idea which test triggered it?).

I guess we could improve the error message we show on the panic as the simplest solution. I'm open to other ideas.

**Comment by jpincas** [comment]
But couldn’t we at least stop people using an invalid code when initializing via ‘init’?

**Comment by ethanfrey** [comment]
Yes, that would be a very good addition to the changes in init. There is an IsCC function, I think in x/coin.go that checks for the proper pattern. We should use it so all checks have one source of truth. On Apr 8, 2018 19:34, Jonathan Pincas <notifications@github.com> wrote:But couldn’t we at least stop people using an invalid code when initializing via ‘init’?
