### ISSUE TITLE
Support a way to add ORM indexes without modifying the merkle hash

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#472]
**Is your feature request related to a problem? Please describe.**
I am not sure if this scenario applies to blockchain apps as well:
While we run and learn how the system is used, we may need to add new indexes so that queries can be executed more performant on the backend data
.
When indexes are stored in the merkle tree DB then adding a new index would modify the state and the app would be incompatible with previous versions.

**Comment by ethanfrey** [comment]
Well... If I deploy new code with the index, it will only apply to data stored *after* that point.

So, it would actually need a migration step. And yes, the two code bases would make different merkle roots, and diverge.

I would consider this under the topic of **upgrade path** which we should look at from many angles, this just being one. Maybe we can discuss this in person in Berlin

**Comment by ethanfrey** [comment]
I think we cannot add data without changing merkle hashes.

But if we clarify this issue to allow smooth migrations, where we add/remove an index as part of a Schema bump, then I agree :100: that we need a clean way to do so.
