### ISSUE TITLE
Add coin.Coin.String method

### ISSUE THREAD

**Issue by husio** [iov-one/weave#475]
Add `coin.Coin.String` method so that coin can be printed in a human-readable format.

[`coin.ParseHumanFormat`](https://github.com/iov-one/weave/blob/master/coin/coin.go#L341) allows unmarshaling a coin from a human-readable format. We want the `String` method to do the opposite. Return a human-readable format of a `Coin` instance.

## Acceptance criteria
- [x] `NewCoin(0, 2, "IOV").String()` returns `"0.000000002 IOV"`                       
- [x] `NewCoin(1, 2, "IOV").String()` returns  `"1.000000002 IOV"`
- [x] `NewCoin(1, 0, "IOV").String()` returns `"1 IOV"`

**Comment by ethanfrey** [comment]
I would add two points.

1. Trim trailing zeros in output

2.String() method is already defined by protobuf. Either disable this codegen with a gogo protobuf flag or use a different name for this formatting
