### ISSUE TITLE
weave package improvements

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#492]
~- [ ] TODO: GasPayment, check if this could already be implemented~ Still not there
- [x] Nicer log modification, maybe use `fmt` instead of concat
- [x] Instead of just checking `code != 0` use a const for more descriptiveness on what's happening (code 0 reserved for non-errors)
- [x] hex.go is empty, shall we ditch it? -> yes
- [x] LoadVersion to be implemented (see historical queries)
- [x] version.go does not seem to be useful -> we override it in the Makefile I believe, but int versions not used

Other related issues:

- query: TODO: rangeQuery to be implemented (#413)
- CommitKVStore TODO: historical queries, getWithProof? (#5)
- TODO: add Batch to atomic writes and efficiency -> I assume it's this ticket here: https://github.com/iov-one/weave/issues/18

**Comment by ethanfrey** [comment]
I added comments above. Three are larger tasks in other issues. The rest nice things to clean up
