### ISSUE TITLE
crypto package improvements

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#495]
- [ ] TODO: look at sources of randomness, other than default **crypto/rand** for `GenPrivKeyEd25519`

**Comment by ethanfrey** [comment]
https://golang.org/pkg/crypto/rand/

Cosmos-sdk used their own png, mixing a user-provided entropy with crypto/rand for a png or something as Jae thought you couldn't trust intel (fair enough). But in a code audit, the auditors suggested using os secure random sources was best practice and hand-rolling others more dangerous
