### ISSUE TITLE
Clarify abci/js narrative in readthedocs 

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#50]
From jon:

> For sure. I’ve read most of the docs you’ve written now and also gone back over the tendermint docs.  I think the place to start will be really teasing apart the abci building stuff from the weavejs stuff. At the moment it can be hard to know exactly which bit you are talking about at any one point. I’ll explain more when we talk.

Ethan:

> Yeah, good thought.
>
> Maybe an overview of the pieces. Then explain how to set up a pre-built abci app Then using it to see how it works from the outside.
> Like what I have but with a coherent flow...
> 
> Afterwards how to build your own abci app. And finally how to build your own client. And connect that to a js frontend
> Does that seem like a sensible narrative?

**Comment by jpincas** [comment]
My next step is to actually start building something, so I think it will graduallly become clearer docs are lacking.

**Comment by ethanfrey** [comment]
Another thought:

* overview of pieces, abci, tendermint, js lib
* explain repl, demo client
* explain tendermint, link to docs
* explain abci, link to docs
* weave architecture / explain Mycoin (two sections or one or??) 

After this flow of explaining one app from top to bottom, then a tutorial of building an app. It can go rather quickly, assuming one understands the concepts, but explaining how to apply them and how to structure the app. 


I will start a pr branch soon to try a reorganization.

**Comment by jpincas** [comment]
If its not really urgent, I reckon we should leave the reorganisation until after I have managed to build something with weave.  That way I'll have a much clearer idea of stumbling blocks for a beginner.  Meanwhile we can leave this issue open for noting down ideas.

**Comment by ethanfrey** [comment]
Readthedocs is being overhauled. Outdated issue
