### ISSUE TITLE
Extract governance votes into their own bucket

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#502]
**Is your feature request related to a problem? Please describe.**
Votes are currently stored within the proposal model. That adds some overhead to de-/serializaion which also can become quite inconvenient with queries.

**Describe the solution you'd like**
Extract votes into their own bucket and make use of DB indexes for common query cases.

**Comment by ruseinov** [comment]
@ethanfrey This seems to be done according to the latest code, I went through the code and we have votes bucket with all the indices and the proposal does not contain them.

I'm closing this.
