### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [iov-one/weave#504]
**Is your feature request related to a problem? Please describe.**
I think that this project doesn't have a logo.

**Describe the solution you'd like**
I'd like to contribute by designing one.

**Additional context**
If you do need a logo, please let me know if there are any specific things you'd want this logo to represent, and if you don't have any I'll just implement my own ideas. Looking forward to hearing from you :)

**Comment by ethanfrey** [comment]
@newfinal100
Thank you for the offer, I was just reflecting on that same issue recently. 

The name weave was supposed to evoke the concept of a loom. Braiding together individual modules to make a concrete whole.

While thinking about the logo idea, I also looked at some photos of cats cradle and other "string origami". Not sure how to represent any of that with a simple logo, but maybe some inspiration.

Thanks for the offer and initiative and look forward to a pr

**Comment by newfinal100** [comment]
![first version weave-01](https://user-images.githubusercontent.com/49202520/56141891-fe273f80-5f9d-11e9-873b-4616e4f6a07d.jpg)
![second variation weave-01](https://user-images.githubusercontent.com/49202520/56141922-0d0df200-5f9e-11e9-99f4-bdbbfdbf86c4.jpg)
![third weave-01](https://user-images.githubusercontent.com/49202520/56142067-4e9e9d00-5f9e-11e9-9ff6-b3fc7b9dbedd.jpg)
![third version weave 3](https://user-images.githubusercontent.com/49202520/56142274-aa692600-5f9e-11e9-9940-4eb11e82b438.jpg)

So here are a few variations I created, let me know what you think!

**Comment by ethanfrey** [comment]
Thank you!

I talked with a few other members of the dev team, and we all prefer the top one, the blue-green ribbon.

Do you want to make a pull request including logo.png in the repo and linking it from the README? You can add a small note at the bottom of the readme (logo by newfinal100).

**Comment by newfinal100** [comment]
I'm glad you liked that one! I think it's better if you do it cause I'm scared I'll do something wrong if I try to do that myself :))

Here's the logo:

![logo weave-01](https://user-images.githubusercontent.com/49202520/56312380-4e460380-6150-11e9-84b1-96261d83ac64.jpg)

And I'll upload all the other formats and original files on Google Drive soon and will send you that link here too in case you may need the other formats for other places
