### ISSUE TITLE
Enforce preimage size of 32 bytes

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#510]
The IOV atomic swap protocol required preimages to be exactly 32 bytes in length: https://github.com/iov-one/iov-core/pull/859

This must be enforced by BNS in order to comply with the protocol.

At this point we should think about if it is possible to derive a specialized atomic swap contract from the general Escrow to differentiate between the weave framework and the implementation of the IOV atomic swap protocol version 1.

**Comment by ethanfrey** [comment]
This was done in #571
