### ISSUE TITLE
Prevent overflow in sigs User sequence

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#511]
**Is your feature request related to a problem? Please describe.**
With #388 it would be a bit easier to reach the max int64 value and we should protect against an overflow in the codebase.

**Describe the solution you'd like**
A guard with an error in [CheckAndIncrementSequence](https://github.com/iov-one/weave/blob/master/x/sigs/model.go#L47) . Maybe other places as well.

**Describe alternatives you've considered**
Use a bigger type than int64

**Comment by webmaster128** [comment]
This is a problem for the client. The greatest supported nonce value at client side is `Number.MAX_SAFE_INTEGER = 9007199254740991 = 2^53 − 1`. If greater values must be supported, we get much more complicated client code.

**Comment by ethanfrey** [comment]
Let's make a guard that nonce is always less than 2^53
