### ISSUE TITLE
Update error names

### ISSUE THREAD

**Issue by husio** [iov-one/weave#513]
Current error names are sometimes unnecessary long. Replace them with a short form when feasible.

Some words make little sense to use in the context of an error. For example `ErrInvalidType` can be replaced with `ErrType`. It is an error caused by the type. Adding that the type was invalid brings no additional information.

A good error is for example [`ErrCurrency`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L67) (not `ErrInvalidCurrency`), `ErrPanic` or `ErrOverflow`.

Some errors represent a superset of already existing errors. For example `ErrInvalidMsg` is returned when a message validation fails. But instead of this a more precise error should be used, for example `ErrOverflow`, `ErrCurrency` or more generic `ErrInvalidState`.

## Rename

- [ ] [`ErrCannotBeModified`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L37) to `ErrImmutable`
- [ ] [`ErrInvalidState`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L43) to `ErrState`
- [ ] [`ErrInvalidType`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L46) to `ErrType`
- [ ] [`ErrInvalidAmount`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L53) to `ErrAmount` 
- [ ] [`ErrInvalidInput`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L56) to `ErrInput`

## Remove
- [ ]  [`ErrInvalidMsg`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L67) and use a more granular error instead
- [ ]  [`ErrInvalidModel`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L25) and use a more granular error instead
- [ ]  [`ErrInsufficientAmount`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L50) and use `ErrAmount` instead
- [ ]  [`ErrEmpty`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L40) and use `ErrInput` or `ErrState` instead
- [ ] [`ErrHuman`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L33) as this is most of the time `ErrInput`.

**Comment by ethanfrey** [comment]
Makes sense.

I would leave `ErrInvalidMsg` (rename to `ErrMsg`) and `ErrInvalidModel` (rename to `ErrModel`) for now. Leave `ErrEmpty` for now.

We can check off the rest of the boxes and have a larger discussion before finishing this issue

**Comment by husio** [comment]
>I would leave ErrInvalidMsg (rename to ErrMsg) and ErrInvalidModel (rename to ErrModel) for now.

If validation error will be implemented (https://github.com/iov-one/weave/issues/529) then it will replace both errors with a new error code.

**Comment by ethanfrey** [comment]
> If validation error will be implemented (#529) then it will replace both errors with a new error code.

Now that is a good concrete suggestion.
We can implement the rest in the meantime if people need a small "breather" task, and tackle the last points as part of #529
