### ISSUE TITLE
x/hashlock package improvements

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#514]
- [ ] It would probably help to have some scenario tests for this to provide better overview
- [ ] Not a particular fan of using ```ctx.Value(contextKeyPreimage)``` as this seems to be global to the context and using iota (0) in this case. I would much rather prefer a format of ```extension:variable```

**Comment by ethanfrey** [comment]
Let's just delete this as per #540

**Comment by ethanfrey** [comment]
>  Not a particular fan of using ctx.Value(contextKeyPreimage) as this seems to be global to the context and using iota (0) in this case. I would much rather prefer a format of extension:variable

This is actually a powerful go trick to make package local keys in context that no other package can read or write. Got this some years ago.

Trick is keys in Context are interface{} which stores type info, and nothing can force a collision with a private type.

**Comment by ruseinov** [comment]
@ethanfrey ah, I didn't really know this. Cool!
