### ISSUE TITLE
store package improvements

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#521]
- [ ] btree -> Allow discard (TODO fix)
- [ ] btree -> reuse FreeList between multiple cache wraps (TODO fix)
- [ ] btree -> add support for Combine (deleting those below)  (TODO fix)
- [ ] SliceIterator -> private (TODO fix)
- [ ] recorder -> fix TODOs
- [x] Revisit Store interfaces and implementations to support returning errors instead of panics, the interface is hard to work with

**Comment by kmw101** [comment]
Items covered in the TODO issue #532 closing
