### ISSUE TITLE
Cleanup `x/nft` handlers

### ISSUE THREAD

**Issue by husio** [iov-one/weave#533]
Cleanup `x/nft` package.

## Acceptance criteria
- [ ] move `x/nft/base` to `x/nft`. In other words, merge it into a single package. `base` subpackage provides generic NFT handler that is part of NFT functionality,
- [ ] remove [`handlers_test.go` dependency](https://github.com/iov-one/weave/blob/master/x/nft/base/handler_test.go#L8) on the `bnsd` application

**Comment by ethanfrey** [comment]
Code was deleted. Issue resolved :tada:
