### ISSUE TITLE
Add schema numbering to enable upgradability

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#537]
**Is your feature request related to a problem? Please describe.**
No clear way to upgrade the blockchain. What if we want to change the data format we store in a bucket, add a new message, etc. How do we enable that?

**Describe the solution you'd like**

* We add a `uint32 schema = 1;` field to all top level Msg and Object protobuf defintions.
* We add a global `migration` Bucket that stores mapping from `package name` -> `latest schema`
* When running, each package can use the latest schema to both enable different code paths, as well as force message versioning and set data storage versioning.

Process of an upgrade is:
* Deploy new code that knows how to process schema 1 and 2.
* Wait til 80%+ of validators upgrade
* Send a UpdateSchema(cash, 2) message (this must be permissioned somehow.. like by a governance vote)
* From this point on, version 2 of the code is active. That means re-running the chain from scratch with the new version will automatically use the schema 1 code path before this tx and the schema 2 path afterwards.
* (Optionally) run a batch data migration as part of the upgrade transaction to update buckets

Migration rules:
* We can define and register migrations such as `Migrate(msg Msg) (Msg, error)` and register them for (Msg, schema) pairs. These may also want `Context` and `ReadOnlyKVStore` as parameters, but we can discuss this later
* Two default migrations are `noop` (when the msg is the same for both schemas) and `invalid` (which always returns error). Otherwise, write custom logic.

Message Migrations:
* On receiving a message, check `message.schema` against `latest_schema`. 
  * For `latest > message`, run migration for `message.schema` until it hits an error, or reaches latest. If successful, contninue to next step
  * If `latest = message` process the message
  * If `latest < message` reject the message as SchemaTooHigh (trying to use a feature before it is enabled)
* Note that this means that all Handlers can check `message.schema` to switch codepaths, the same as using `latest`

Data Migrations:
* We probably want to use a batch migration for all stored data upon updating a schema. If the migration is a noop, we don't want to load then at all.
* We may want to update the models lazily, running the migration when they are read (and then saving the newer version). This is an optimization, but adds plenty of complexity
* We can assume that in either case, all data is updated to `latest_schema` upon reading from a Bucket.
* All data must be saved in `latest_schema` format

Note that there are many Messages, Handlers, and Buckets in one module. For simplicity, we will use a global schema per module, but that means that often `SendMsg(schema=1)` is the same as `SendMsg(schema=2)`. This is the main purpose of the `noop` Migrations.

Adding new features:
* Imagine the latest schema is 2, and we want to add a new message `IssueToken`, but we want a clean roll-out. We can use this same set.
* `IssueTokenHandler` will use a switch on the `message.schema` and return an error if schema is less than 3. Enabling the original code for schema=3
* Migration from 2 -> 3 will be invalid
* If a message is posted before activation, it will either be rejected by handler with schema 2, or rejected by migration rules if schema=3 (higher than latest schema)
* Upon activation of schema 3, the feature will work normally with `IssueToken(schema=3)`.

-> This avoids all config files that need to be kept in sync and the entire upgrade history is stored in the blockchain. One point is that the newest version of the software must be able to process all older transactions as well, so we will have mutliple code paths. Ideally we make code quite stable before releasing, but there will be some complexity with testing multiple paths

**Describe alternatives you've considered**
Dumping state and restarting the chain.

Seems like a good idea in emergency cases, hard forks, byzantine behavior, and we should add support at some time. For now, this is a smoother upgrade process

**Additional context**

It may be useful to expose the currently supported schema (node dependent) in addition to the currently activated schema (in kv store via abci_query).
The [abci_info endpoint](https://github.com/tendermint/tendermint/blob/master/rpc/core/abci.go#L100) returns a [few extra fields](https://github.com/tendermint/tendermint/blob/master/abci/types/types.proto#L131-L139) in addition to the app hash and app height that we return:

```go
message ResponseInfo {
  string data = 1;

  string version = 2;
  uint64 app_version = 3;

  int64 last_block_height = 4;
  bytes last_block_app_hash = 5;
}
``` 

It is probably best to use the data field (or version?) to return a json map of `package -> schema`. Then we have an easy way to check which nodes have upgraded before trying to run the upgrade transaction

**Comment by ruseinov** [comment]
@ethanfrey 

> When running, each package can use the latest schema to both enable different code paths, as well as force message versioning and set data storage versioning.

Meaning that when we run migrations we should aim to bump this version to latest and same goes for when we process the message?
 

> Two default migrations are noop (when the msg is the same for both schemas) and invalid (which always returns error). Otherwise, write custom logic.

Why is this needed? Do we need noop because we want to bump overall schema version and then upgrade message versions even if they didn't change, hence we still "migrate" them? I guess so.

What is `invalid` used for? When we have different schema on 2 messages, but no logic?


Also, I'm trying to understand how are we going to enforce certain versions:

Example:

```
message A {
  int version; (equals 1 in this case)
  string name;
  string lastname;
}
```
```
message Aver2v1support {
  int version; (equals 2 in this case)
  string name;
  string lastname;
  string fullName;
}
```
```
message Aver2 {
  int version; (equals 2 in this case)
  string fullName;
}
```

So in this case when we have a method GetFullName() while still migrating validators it would be something like this and backed by `Aver2v1support`
```
func(n *obj) GetFullName() {
   if version == 1 {
     return n.name + " " + n.lastname
  } else {
    return n.fullName
 }
}
```
and then after validators have been upgraded we deploy following code backed by `Aver2`
func(n *obj) GetFullName() {
   return n.fullName
}
```

**Comment by ethanfrey** [comment]
As per @husio comment, we don't just embed a Schema everywhere, but a generic Header message, which can be upgraded later without breaking changes.

```
message ExampleMsg {
  Header header = 1;
  // ... rest of fields...
}

message Header {
  uint32 schema = 1
  // if we ever decide to add something globally, this space is available without breaking changes
}

**Comment by ethanfrey** [comment]
Question: as designed, every handler and every bucket will need to refer to the migrations package.

1. To migrate Object and Msg (maybe this code can be registered globally in the migrations package, some helper code to auto-execute)
2. To determine which code path to run in the handler.

Even if this does a read for every tx (try to optimize later), we need to figure a way to not make huge developer overhead to integrate this. And all packages depending on this migration bucket makes unit tests hard to do.

First step is some "ActiveSchema()" function/interface passed into each Handler that can be swapped out with a mock for unit tests. Let's refine how this is done as the code develops.

**Comment by ethanfrey** [comment]
Also, note we must register all schemas in the genesis file. If they are not registered there, they are in a disabled state, ready to be enabled with an enable tx. This is a bit of cognitive overhead, but I think unavoidable, as when we upgrade the chain and add a new module, that module must be disabled at first, only when explicitly registered with schema=1,2,etc will any message for that module be processed.

To allow smooth upgrades, we require to register a schema for every package we want to activate

**Comment by ethanfrey** [comment]
Make sure to add good documentation on how to use this.

`doc.go`
`CHANGELOG.md`
and ideally, a file in "readthedocs" docs directory

**Comment by husio** [comment]
The functionality is implemented in https://github.com/iov-one/weave/pull/547

What is left is to port all extensions, deploy `bnsd` and `bcpd` and restart networks as those are fully breaking changes.

**Comment by ethanfrey** [comment]
Closing this issue as the general work is done.

Implementation in bnsd is a separate issue #564
