### ISSUE TITLE
Add validation rules to Configuration

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#538]
**Is your feature request related to a problem? Please describe.**

We will likely want to make minor adjustments to the validation rules over the lifetime of the chain, such as changing the maximum allowed memo length, or rules for valid usernames. However, if we change it, we cannot re-run the historical blockchain, and we would need a complex schema migration process (#537) to do this. We should enable an easier aspect for changing a few variables

**Describe the solution you'd like**
We can move many of the validation rules (min/max numbers, even regexp) into the Configuration object (after #456 and #503 are finished). At that point, the rules are on the blockchain and any change is "simply" a (permissioned) `UpdateConfiguration` message. No hard-forking, no complex upgrade process. And we ensure all node update at the exact same point.

This would also be a good way to put the new gconf to the test and should be done shortly afterwards **before cutting a breaking release** to ensure we are happy with the API before breaking everything.

Adding all this info to Configuation would also make enabling schema migrations #537 useful for Configuration objects as well as Msg and Value objects. 

**Describe alternatives you've considered**

Hard-forking. Blah.

**Comment by ruseinov** [comment]
@ethanfrey I have got a bunch of questions here:

1. Are we talking about adding a Configuration object per extension? I assume so. And then possibly adding a Msg to update it sometime in the future, right?
2. It would make sense to have defaults for these values, as initialising the app with tens of configuration values in genesis on app start does not really seem like a nice way of doing this. For example: every time tendermint introduces a required value to it's config - it's such a pain to find out which and update genesis. WDYT?
3. Also, how do we validate things like regexp? I suppose we just trust that it's already been tested and works.

**Comment by ethanfrey** [comment]
Let's design this a bit more....

Idea is good, details matter.

One idea is that v1 of the code has hardcoded regexp
v2 adds those to a configuration object and a migration to set default values.

We can always launch with v1, then upgrade to v2, then modify manually.
Or start with v2 if we want to include those in genesis.

We should always add migrations with sensible defaults when we add new configuration parameters.

Just some ideas, maybe someone can develop those further or come up with a better proposal.

**Comment by ruseinov** [comment]
****

> We can always launch with v1, then upgrade to v2, then modify manually.
> Or start with v2 if we want to include those in genesis.

Now the migration bit makes sense to me. 

My proposal with some open questions then would be as follows:
1. Do not require genesis init for this, but rather incorporate an initial "dynamic" version as a migration of some sort, that would write this on application startup.
2. When needed to update dynamically - just send a message to update. 
3. Still an open question - what do we do if an update contains a broken regex, for example? Should there be some sort of testing for this? Or should we, instead, only allow to supply parameters to original regexes and such to reduce the chance of failure?

**Comment by ethanfrey** [comment]
> Do not require genesis init for this, but rather incorporate an initial "dynamic" version as a migration of some sort, that would write this on application startup.

We need to think it through. But I like some idea like defaultConfiguration stored in the code. This *may* be overriden by the genesis file (eg. patch present fields) to create initial configuation. Then this may be updated later via an UpdateConfiguration message. If nothing is defined in genesis, we use defaults.

Note that this means the defaults can never change. Unless there is some migration step (eg. updating to schema 3 will upgrade the configuation object). Not sure how this would work. I guess you must override in genesis if you ever want different Configuration is simplest.

> Still an open question - what do we do if an update contains a broken regex, for example? Should there be some sort of testing for this? Or should we, instead, only allow to supply parameters to original regexes and such to reduce the chance of failure?

I agree here. We need a good `Validate` function for the Configuration object (from Init and Update) to ensure they compile. We could also do so some common sense hard-coded limits in Validation like requiring some int to be positive, while allow configurations to change them from eg. 5 to 100
