### ISSUE TITLE
Make custom atomic swap module

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#540]
**Is your feature request related to a problem? Please describe.**

As atomic swap [becomes more specified](https://github.com/iov-one/iov-core/pull/859) by the iov-core team, and implemented on ethereum, we need to enforce very specific rules. Such as #510 #446 etc. We also discuss enabling bonus payment to whoever pays the fees on claim, to allow a "cobbler" to help bootstrap.

All these start deviating from the generic escrow design. We also are stuck with some inconsistencies like using Condition for Arbiter, but Address for sender/receiver to support atomic swap. Let us make proper solutions for both problems. Escrows are useful for many cases. Also can do magic like handling token vesting. Let them do that well.

**Describe the solution you'd like**

Once https://github.com/iov-one/iov-core/pull/859 is merged, we should make a custom package to implement this precisely. Once that is deployed and the client is updated, we can make other breaking changes to remove unneeded legacy code:
- remove hashlock package and middleware
- use Address instead of Condition for arbiter
- TODO: @husio add your list of complaints here :)

Make sure to check in wth @webmaster128 and the iov-core team for final version of the atomic swap spec (eg. paying the fee payer) before implementing

**Comment by husio** [comment]
This story is about creating a new extension (for example `x/aswap`) without changing `x/escrow` or about modifying an existing `x/escrow` extension to fulfill new requirements?

**Comment by ethanfrey** [comment]
Make a new module aswap.

After that we can simplify escrow, like making arbiter an address. Also likely remove hashlock Middleware

**Comment by webmaster128** [comment]
> We also discuss enabling bonus payment to whoever pays the fees on claim, to allow a "cobbler" to help bootstrap.

As discussed with Martin, this feature is great but not considered MVP. Thus we should not get blocked by that missing addition.

To mitigate the problem of onboarding, we now ecplicitly require that _claim_ can be called by anyone, so I can ask a friend to claim my swap for me as long as I can't affort fees.

> Once iov-one/iov-core#859 is merged

No further change to the PR is expected before MVP, so please feel free to start working based on the current state of the PR.

**Comment by ethanfrey** [comment]
When building this module, it would be interesting to make it like a tutorial.
If each commit is one step, and there are good comments, we can use it as the basis for a real-life tutorial example for the docs (which we need). Better than some silly blog example.

Also, if there is anything too boilerplate that can be simplified, good to make an issue so we can improve.

And we should document all the knowledge needed (init, handler, config, db reads, indexes, etc etc)

**Comment by ruseinov** [comment]
@webmaster128 @alpe @husio  
After reviewing the code I have some questions, I guess whoever can answer them - be my guest:
1. Currently preimage is a field in a Tx, rather than field in a message and used by hashlock to add a condition to auth. In my understanding that would now be included in `CreateEscrowMsg|ReleaseEscrowMsg` messages? 
2. Arbiter keeps being a condition, right?
3. Preimage is now a 32-byte hash, which needs to be supplied when Releasing and Creating and escrow (check if it's a match on Release)?
4. Preimage used to be a condition, containing arbiter "address", but now it's just a user-generated hash stored in the db and checked upon certain operations?

**Comment by ruseinov** [comment]
I got a bit confused by the atomic swap spec, which stated that preimage should be a user-generated string/hash, but after discussing this with @webmaster128, my takeaways are:
1. We keep preimage as is in terms of how it's sent and used, currently it contains a weave.Condition with an address that allows to authenticate the operation
2. We keep arbiter as is
3. 32-byte restriction is going to be implemented later
