### ISSUE TITLE
Move from `dep` to go modules

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#551]
**Is your feature request related to a problem? Please describe.**
Go modules are optional in 1.11 and default in 1.12+. They replace `dep` (and glide etc) as package management. From my experience, it seems to work better, avoid make file steps (`go test` just works without needing to run `dep ensure --vendor-only` first). And it handles tendermint dependencies nicer (which was a headache with glide and dep by each upgrade).

**Describe the solution you'd like**

I would like to:
* commit `go.mod` and `go.sum` files to the repo for reproduceable builds
* declare minimum support go 1.11+
* add to readme how to run code with modules (`GO111MODULE=on`)
* upgrade CI to use go 1.11 or 1.12
* clean up Makefile

**Describe alternatives you've considered**
I've tried every package manager used by go. They seems to come out every 18 months or so and each iteration is better than the last. Having this tooling in the go binary and integrated with `go build` and `go test` by default is a nice bonus, and makes me think this solution is (finally) here to stay

**Comment by husio** [comment]
This is blocked by https://github.com/iov-one/weave/issues/249 - some tests are still using `goconvey` which does not compile with Go 1.12.

**Comment by ruseinov** [comment]
@husio why is it blocked? We can use go 1.11 for now I suppose, as convey works fine with that

**Comment by ruseinov** [comment]
This issue seems pretty complete to me in it's current state. Shall we move this to ready for dev? 
We can opt for 1.11 golang while convey tests are still there I suppose, or make this a dependency

**Comment by ethanfrey** [comment]
I would clean that up first, as only supporting go 1.11 with an env variable set seems weak.

We can support 1.10 and 1.11.
Or 1.11 and 1.12

Looking at goconvey, there are only 7 files left where it is used, so shouldn't be *that* hard to remove the dependency.

- [ ] `conditions_test.go`
- [ ] `x/batch/decorator_test.go`
- [ ] `x/batch/msg_test.go`
- [ ] `x/nft/base/handler_test.go`
- [ ] `x/nft/helper_test.go`
- [ ] `x/nft/msg_test.go`
- [ ] `x/validators/controller_test.go`

Once those 4-5 packages are migrated in #249, this should be good to go.
