### ISSUE TITLE
Remove genesis generation

### ISSUE THREAD

**Issue by husio** [iov-one/weave#557]
Both [`bnsd` ](https://github.com/iov-one/weave/blob/master/cmd/bnsd/app/init.go#L32-L77) and [`bcpd`](https://github.com/iov-one/weave/blob/master/cmd/bcpd/app/init.go#L26-L68) provide a functionality to generate an example genesis. I believe this is not maintained and not used functionality. Generated this way genesis is no longer valid.

Pick one of the below solutions or propose another one. Remove the rest.

## Acceptance criteria (option 1)
- [ ] remove genesis generation from `bnsd`
- [ ] remove genesis generation from `bcpd`

## Acceptance criteria (option 2)
- [ ] keep the exampl genesis of each extension in the extension itself. Update each extension to provide a function, for example `ExampleGenesisJSON(...) json.RawMessage` that returns example genesis content
- [ ] update `bnsd` and `bcpd` to call `ExampleGenesisJSON` of each installed extension instead of manually building the whole genesis

I think the first solution is better because it requires no work and no one seems to care about example genesis creation. At the same time, we maintain genesis documentation anyway https://github.com/iov-one/weave/blob/master/cmd/bnsd/client/testdata/genesis_json.md

**Comment by ethanfrey** [comment]
This functionality is needed for dev demo. Bnsd init and go.

Nicer than having to make a genesis by hand to test out a software. We should have a valid default. 

But yeah, one. And not 5.

**Comment by husio** [comment]
For the high number of genesis declarations I have created another issue as those two topics are not related https://github.com/iov-one/weave/issues/559

**Comment by ethanfrey** [comment]
I like the auto-generation for the dev experience and providing a template to edit more.

You are right, we manually create them for real blockchains, but no need for devnets.

Closing issue, remaining points to be addressed in #559
