### ISSUE TITLE
Limit number of genesis files

### ISSUE THREAD

**Issue by husio** [iov-one/weave#559]
Currently, we declare genesis in many places. Each package seems to maintain its own genesis configuration for the tests. I think they could as well use a single genesis configuration as well.

Because we have so many genesis declarations, most of them are outdated or invalid. It is impossible to keep all of them in sync with the changes. Introducing new genesis requirement is a demanding task.

## Acceptance criteria
- [ ] provide a single genesis declaration that is used by all tests, regardless of where they are

**Comment by ethanfrey** [comment]
I think each package needs to maintain some default for it's subset of the genesis.
But bnsd has like 3 versions of them combined as well.

Maybe every module we write with init.go could expose a `DefaultGenesis(admin weave.Address)` function or such to provide a default genesis for tests (and bnsd init?). Then bnsd can just combine these together into one big genesis file.

That way, you just update the local genesis when you unit test init.go and the scenario tests are done automatically. We could then run `bnsd init` to get a sample genesis file for reference.
