### ISSUE TITLE
Transaction schema versioning

### ISSUE THREAD

**Issue by husio** [iov-one/weave#572]
Package `migration` in [current form](https://godoc.org/github.com/iov-one/weave/migration) does not support schema versioning of the transaction. Provided functionality makes it possible to schema version models and messages only.

Middlewares are not working on the message but on [set of additional transaction attributes](https://github.com/iov-one/weave/blob/master/cmd/bnsd/app/codec.proto#L19).

Do we need to support schema versioning of the transaction as well? Protobuf is designed in a way that allows adding fields without breaking the schema. 
Do we need to put on the blockchain the information which middleware fields are required in the transaction?

Is it acceptable that the decorator is looking/changing the message contained in the transaction? If yes than current `migration` package implementation of [`SchemaMigratingHandler`](https://github.com/iov-one/weave/blob/master/migration/handler.go#L9-L15) must be replaced as it upgrades the message before the handler call but **after** all middlewares calls.

**Comment by alpe** [comment]
Schema versioning is a cross cutting concern that affects all messages in the modules. I see it very similar to fees or other metadata that is stored at the Tx level. A single decorator should therefore be able to do the schema upgrades for messages and fail fast when it is not possible. This keeps the migration logic out of the handles, provides a straight way in the flow and allows loose coupling at the framework level.
It should be less work than updating all existing msg with the new metadata attribute. Also at the client side.

**Comment by alpe** [comment]
Thinking about this a bit more.... although I prefer this approach, adding the schema version to the `Tx` won't work nicely with the current batch implementation.

**Comment by husio** [comment]
> A single decorator should therefore be able to do the schema upgrades for messages and fail fast when it is not possible

I like this approach. Having such decorator/middleware would require less typing and [`SchemaMigratingHandler`](https://github.com/iov-one/weave/blob/master/migration/handler.go#L9-L15) will no longer be needed.
I have two concerns that make this approach hard to implement right now, maybe we can figure it out together.

* I do not know if it is a rule or not, it seems that decorators are not looking/chaning the message represented by the transaction. They only interact with [middleware reserved fields](https://github.com/iov-one/weave/blob/master/cmd/bnsd/app/codec.proto#L19).
  * if this is true than a decorator migrating messages will break this rule. It will not only look at the transaction message but also modify
  * if this is false than we must change where we migrate our messages. Right now it is done before handlers and after middlewares. It must be done as a first thing, before any code use the message
* It is not possible to provide a single decorator that will migrate any message. This is because a [package name is required to learn about its current schema number](https://github.com/iov-one/weave/blob/master/migration/handler.go#L55). We cannot (unless using `reflect`) know what package a message comes from without an explicit information.
The above issue cannot be solved by registering a decorator per package, because such decorator still does not know which messages belong to the package it is supposed to migrate. The only solution seems to be a custom decorator implemented by each extension. This requires more work than current handler decorating solution.
