### ISSUE TITLE
Bucket query autoatic migration

### ISSUE THREAD

**Issue by husio** [iov-one/weave#579]
When a bucket is using [`migration.Bucket` implementation](https://github.com/iov-one/weave/blob/master/migration/orm.go#L60-L92) accessed data is migrated on the fly to the latest version.

This is not the case for the query interface, which is implemented only by [`orm.Bucket`](https://github.com/iov-one/weave/blob/master/orm/bucket.go#L105-L136).

**Should `migration.Bucket` provide a query interface that migrates the data before returning, similar to how `Get` method does this?**

## Issues

* `migration.Bucket` does not have access to [`orm.bucket` indexes](https://github.com/iov-one/weave/blob/master/orm/bucket.go#L111-L113) and therefore it cannot register for queries,
* range query is right now iterating over raw data. `migrationBucket` would have to unmarshal each value, possibly migrate and serialize back. While possible, this will be a major slowdown.

**Comment by alpe** [comment]
We had discussed this case at the meeting. We can not upgrade the data on queries without violating proofs.

**Comment by husio** [comment]
:tada: That is both awesome and a shame :smile:

**Comment by ethanfrey** [comment]
Let's not migrate on read.

If we want consistency, best to do all upgrades (writes) as a batch. That logic is not written, just on demand.

Anyway, don't migrate on query. Guess you can close this.
