### ISSUE TITLE
Change weave.BlockTime notation

### ISSUE THREAD

**Issue by husio** [iov-one/weave#582]
Current `BlockTime` implementation returns the block time value and a boolean. Second argument value is `false` if the block time is not present.

https://github.com/iov-one/weave/blob/9840938a8ba63ef3d86a2bd268d34789b26ea43c/context.go#L96-L99

It seems a common practice throughout the code to ignore second argument https://github.com/iov-one/weave/search?l=Go&q=BlockTime This is the exact opposite what a second argument was supposed to cause.

Consider refactoring this code. Two possible solutions (pick one of propose another one)
1. Change notation removing second argument and panic if block time is not present
2. Add another function `MustBlockTime` that returns time or panics if not present

**Comment by ethanfrey** [comment]
I like `MustBlockTime`. We can even remove the other accessor and force a panic. But the name will warn us
