### ISSUE TITLE
Scenario tests for schema upgrades

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#585]
_As requested, I have rewritten this story to better reflect the current requirement._

As a developer, I want to provide a real use test for our [`migration` package](https://github.com/iov-one/weave/tree/master/migration), so that we can show how the migration process must be coded.

`migration` package contains unit tests and it is well tested. We want to add to this a higher level test that is done for a single extension/application and can be used as a reference for how to introduce migration to an application.
Described above application/extension is not needed in weave. For that reason, we may prefer to keep it as part of our tutorial repository.

## Acceptance criteria
- [ ] provide an extension that use `weave/migration` package,
- [ ] created extension must not be part of the weave repository,
- [ ] provided extension should migrate at least two versions (at least versions 1, 2 and 3) to show how the code can change and adjust

**Comment by ethanfrey** [comment]
Let's push this into a tutorial app.

We need to create one for docs showing step by step how to use the features, including migrations. As part of that (advanced chapters) we can set up and test a migration. This serves as documentation of how to use it correctly. Code is already tested.

When we have an active migration in bnsd app, we add the AT for it, until then, I agree there is no real use

**Comment by husio** [comment]
I have worked on this once and because we did not want to pollute our repository, the code was not merged. https://github.com/iov-one/weave/pull/591

I understand that this task is about creating the code in a separate (not `/weave`) repository. Is this worth doing now, knowing that weave tutorial is not our priority? Should we postpone it or help @orkunkl to take care of it?

**Comment by orkunkl** [comment]
Thanks for mentioning me. I am currently focused on _weave-starter-kit_. Added this issue to Evangelism and docs project. I will look into it when I have free time :+1:
