### ISSUE TITLE
Versioning for electorate

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#587]
**Is your feature request related to a problem? Please describe.**
Simplified versioning

**Describe the solution you'd like**
Proposals point to a fix version of the electorate.

Take version available at proposal creation. Alternative to version available at start time.

**Comment by ethanfrey** [comment]
![DSC_0717](https://user-images.githubusercontent.com/5689864/57301363-21df3080-70d9-11e9-9d50-8a52027a0076.JPG)

**Comment by ethanfrey** [comment]
I sadly cannot find photos of the whiteboard discussion of this. Maybe you have some @alpe ?

Main points were to simplify this, form a key like `(bucket prefix, id, version)` where version is eg. uint32 big endian encoded to provide lexographical ordering. You can do a reverse iterator over the range `(bucket prefix, id +1)` to `(bucket prefix, id)` and the first result is the latest version of the item. No need for an orm index on that.

Having easy accessors and helpers for versioned objects sounds good, kind of like how sequences are supported in orm, but a bit more advanced.

**Comment by ethanfrey** [comment]
Closed by #614 and #616
