### ISSUE TITLE
Consider always using cachedKVStore and discarding on errors returned from check/deliver?

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#595]
While I'm not entirely sure it is a straightforward enough and correct approach, one thing that I have noticed working on `aswap` and integrating `IDGenBucket` there is that we no longer do `Build` and then `Save` on success, instead we are forced to do `Create`, which does the `Save`.

What this means is if we need to do some operations after we have generated the key - we're forced to use cache to make sure that `Save` can be discarded if operations that follow don't succeed. 

Here's an example: https://github.com/iov-one/weave/blob/c3c80a99deaf28ba39c3b5a6cfcf462e78b530c9/x/aswap/handler.go#L76

**Comment by ruseinov** [comment]
@ethanfrey I have just checked decorators in bnsd and it seems like we are always using onCheck and not onDeliver for checkpoint, which means that the changes won't be discarded should anything go wrong with writes in deliver. This makes aswap implementation potentially harmful in terms of producing swaps that are not executable and just polluting the store. Correct me if I'm wrong.

**Comment by ethanfrey** [comment]
Look at dynamic fee decorator implementation

It has a checkpoint internally. 

It should be in the docs. If not, please add some better docs as a pr to close this issue

**Comment by ruseinov** [comment]
It is in the doc comments to DynamicFeeDecorator, yes, but I keep wondering if it's better to be explicit about this instead of embedding?

I think the cool thing about having modular building blocks is it allows us to be explicit about what we are doing without making any assumptions along the way, but maybe I'm missing a bigger picture here. 

I would at least add a comment in bnsd where this decorator is being used that it also enables `OnDeliver` functionality as I don't see how a user can deduce this behaviour without reading docs for each enabled Decorator. WDYT?

**Comment by ethanfrey** [comment]
I agree. And I like the PR adding comments
