### ISSUE TITLE
Simplify escrow

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#601]
Points from https://github.com/iov-one/weave/issues/540

- remove hashlock package and middleware
- use Address instead of Condition for arbiter
- moveCoins helper from escrow and aswap can be moved to cash for reusability

Anything else?

**Comment by ruseinov** [comment]
@ethanfrey question: do we want to break binary compatibility when removing `preimage` from bcpd/bnsd? Or shall we just leave multisig as 4?

I'd say let's break it for consistency.

**Comment by ethanfrey** [comment]
The plan when making such spaces for the field numbers was not to change any of them again. Please leave the gap

**Comment by ruseinov** [comment]
@ethanfrey fair, I'll leave the comment as to why then.
