### ISSUE TITLE
Add CHANGELOG check to CI

### ISSUE THREAD

**Issue by husio** [iov-one/weave#631]
We have decided to maintain our CHANGELOG by hand. This is a fresh process and we often times forget to update the CHANGELOG file. As a result, we either do not mention changes or describe them badly.

## Acceptance criteria
- [x] add a test to our CI builds to check if the `CHANGELOG.md` was altered. Fail the tests if not.
- [x] CI must not fail the tests if the pull request is explicitly marked as one that should not have CHANGELOG modifications. This could be done via GitHub tag, a certain phrase in the commit message etc.

**Comment by ruseinov** [comment]
Sounds like a good idea to me. Marking a PR is not a hard thing to do, but could go a long way.

I guess I’d also introduce a check that fails the release when tagging a version, when there is no such version in changelog.

**Comment by ethanfrey** [comment]
Nice Auto reminder idea.

More. Bots ftw

**Comment by ruseinov** [comment]
I have found a really cool tool to deal with it, going to integrate this coming Friday if everyone is ok with that:
https://github.com/danger/danger
Check this example out: https://github.com/danger/danger/blob/master/Dangerfile#L29-L33

Maybe we can use some more of that?

**Comment by ruseinov** [comment]
It's basically available as a docker container, so should be easy to integrate.

**Comment by ethanfrey** [comment]
Took a quick look seems nice as long as we run it in docker.
We can start with a simple dangerfile for CHANGELOG and easily add more items if they become useful.

Great Friday project

**Comment by ruseinov** [comment]
To mark a PR that does not require `CHANGELOG.md` add `#trivial` to either it's description or title
