### ISSUE TITLE
Anti-Spam default fees in genesis

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#635]
The anti-spam fees set in genesis are denominated in IOV as follows:

Transaction | Anti-Spam fee |
-------------|-----------------|
Send a token | 0.05 |
Create Escrow (1 side of atomic swap) | 0.1 |
Release Escrow (claim) | 0 |
Return Escrow (swap time out) | 0 |
Update Escrow parties | 0.05 |
Set Validators | 0.05 |
Add chain address for username | 0.05 |
Remove chain address for username | 0.05 |
Set revenue distribution | 0.05 |
Distribute revenue to validators and depositors | 0.05 |
New username registration | 0.05 |

**Comment by ethanfrey** [comment]
Anti-spam fee cannot be variable currently.

Please set to 0.05 IOV in all devnet genesis files (and scenario tests)

**Comment by husio** [comment]
I think this also alters genesis file, so let's merge https://github.com/iov-one/ops/pull/172 first.

**Comment by alpe** [comment]
Implemented in https://github.com/iov-one/devnet-operations/pull/17
