### ISSUE TITLE
Set Product fees in genesis

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#636]
The product fees set in genesis are denominated in IOV as follows:

Transaction | Product fee |
-------------|-----------------|
Set Validators | 10 |
Set revenue distribution | 100 |
Distribute revenue to validators and depositors | 100 |
New username registration | 150 |

Note that the product fee is combined with anti-spam fees.

**Comment by ethanfrey** [comment]
Note that we use `min(product fee, anti spam fee)` for fee handler.

So you can use numbers here as 10, 100, 150.

Interesting that usernames are 15 euros at launch price.

**Comment by kmw101** [comment]
> Note that we use `min(product fee, anti spam fee)` for fee handler.
> 
> So you can use numbers here as 10, 100, 150.
> 
> Interesting that usernames are 15 euros at launch price.

Fixed it. 

A username with a link to LSK, ETH, IOV would be 150 + 10 + 10 + 10 = €18

**Comment by ethanfrey** [comment]
We can create a name with any number of addresses. Maybe there are included in the 150 price?

Benjamin should be able to clarify

**Comment by kmw101** [comment]
I can confirm that there is a charge of 10 tokens for each additional chain, so in the case where I add ETH and LSK the fee is 150+10+10

**Comment by kmw101** [comment]
I have removed the add/remove chain product fee as the functionality for this has not been specified for MvP in any of the project streams.

**Comment by husio** [comment]
This is blocked by antnet merge to master. https://github.com/iov-one/devnet-operations/pull/15

**Comment by ethanfrey** [comment]
:tada:
