### ISSUE TITLE
Introduce a migration for escrow package schema

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#660]
Closes #585 

Based on comment here https://github.com/iov-one/weave/pull/656#pullrequestreview-240589663

With #547, #550, #556, and #580 we now have a manner of migrating extensions to new versions gracefully with an on-chain switch. Signed Messages and stored Models all have `Metadata.Schema` fields, which can be updated. We have hooks for migrating an older model version to a new one, and the same with messages. There are even unit tests. However, we have no good example of such in use, to verify the api is good and functionality works as expected when integrated in an application.

As we are doing a minor update to a long-living and established module (escrow), this is a good chance to give the migrations package a proper test.

Requirements (x/escrow)
* Provide schema 1 (arbiter = Condition) and schema 2 (arbiter = Address) for appropriate messages and models (`CreateEscrowMsg`, `Escrow`, others)
  * They can have different interpretations of the same []byte field, but I think cleaner is to add a new field (arbiterAddr), such that v2 uses one field and v1 the other, and gogoproto can type cast them cleanly.
* Validations should check the Schema to determine with rules to apply. (The non-supported one must be nil
* Choose the desired migration wrapper for your use case (I think there are two)
* Handlers should use the Schema from the message to determine which code path to use (check against arbiterCond or arbiterAddr)
* Unit tests code both code paths for messages (Validation), models (Validation and Save), and handlers
* Test migrations, both the migration code itself, but also an escrow created v1, then a schemabump, then released by the arbiter with a v2 message (or auto-migrated v1 message).
* Consider the init files - how to determine v1 vs v2 when parsing genesis file. Test both cases.

Requirements (scenario tests):
* Create genesis file with v1 escrow enabled. Create two escrows. Try to claim with v2 message (fail). Update the schema. Claim one with v1 message, other with v2 message. Verify it works, and perform a few telling queries.

Requirements (docs):
* This PR should be an acceptable reference to link from docs to demo how migrations are done, so aim for clean commit history.
* Add a `Migrations.md` file to `x/escrows/` explaining (a) how the two versions work and how to choose them and (b) how this was implemented in code, as a reference to someone looking to add migrations to another module.
* Docs don't have to be perfectly readable and will be cleaned up, likely moved into our readthedocs, but they should contain all relevant information, so someone with an understanding of go and the weave framework can use that to build their own migrations.

**Comment by ethanfrey** [comment]
Closing in favor of #710.

Please review that issue and let me know if it is clear enough to start working on. I think it would be a nice realistic test of our migration package, and it would be good to test this out before code freeze
