### ISSUE TITLE
Some links are broken on README.md

### ISSUE THREAD

**Issue by orkunkl** [iov-one/weave#672]
In the introduction and instruction sections of README there are some broken links needs to be fixed.

- [ ] [Desing Documents](https://github.com/iov-one/weave/blame/master/README.md#L52)
- [ ] [tendermint](https://github.com/iov-one/weave/blame/master/README.md#L83)
- [ ] [tendermint cli commands](https://github.com/iov-one/weave/blame/master/README.md#L85)

**Comment by theodesp** [comment]
Design Documents is fixed
