### ISSUE TITLE
Spelling typos report from Goland

### ISSUE THREAD

**Issue by theodesp** [iov-one/weave#690]
## Expected Behavior
---
## Actual Behavior
---

## Steps to Reproduce the Problem
---

## Additional info
Goland reports tons of spelling mistakes (among other things). I reference this ticket for a PR that I will push that fixes most of them.

**Comment by ethanfrey** [comment]
Thanks for the initiative @theodesp 

If you are looking for new opportunities, take a look at https://iov.bamboohr.com/jobs/view.php?id=49 I think this position would fit you well. It is a technical writer to help with the public facing docs for weave (and iov-core). We are looking for someone who can write well and explain how to use the key packages, document a tutorial (we are working on sample code, but it needs a narrative and more), etc.

**Comment by theodesp** [comment]
Thank you very much for the info @ethanfrey. Although I'm not looking for a new role right now, especially as a contract, I will be in touch if anything changes. For now, I'm still doing baby steps in the world of blockchain by contributing to codebases that I like such as this one for start.
