### ISSUE TITLE
cash.Configuration.Owner is not used

### ISSUE THREAD

**Issue by husio** [iov-one/weave#694]
~[`cash.Configuration.Owner`](https://github.com/iov-one/weave/blob/master/x/cash/codec.proto#L40-L45) attribute seems to not be used~.

~Either remove it or~ add documentation of what this field is used for.

**Comment by ethanfrey** [comment]
This could better be called `admin`.

It is the account that is able to update the Configuration (eg. set the fee collector address or minimum fee). If empty, no one can change the config.

It is needed to implement these interfaces: https://github.com/iov-one/weave/blob/756058836541daa8d9a69394e7bec1861c653e8e/gconf/handler.go#L14-L26
(please change the names and add docs if that helps clarity).

So... this field is actually used:
https://github.com/iov-one/weave/blob/756058836541daa8d9a69394e7bec1861c653e8e/x/cash/handler.go#L17
https://github.com/iov-one/weave/blob/756058836541daa8d9a69394e7bec1861c653e8e/x/cash/handler.go#L79-L82

Do you want to add better docs on this? You did write the code that uses it: https://github.com/iov-one/weave/commit/c31da1a0c94919c9f3338d49cd216bc8fbe906e8

**Comment by ethanfrey** [comment]
Correction, it seems *I* wrote this code, and Piotr just did the cleanup on it. (thus last commit).
I guess I will enhance the docs....
