### ISSUE TITLE
Validator cli tool does not set multiSig address

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#696]
## Expected Behavior
[MultiSig](https://github.com/iov-one/weave/blob/master/cmd/bcpd/app/codec.proto#L29) field in Tx should be set with `./cmd/validators multisig-new ` command
## Actual Behavior
Not set:
```json
{
	"Sum": {
		"SetValidatorsMsg": {
			"validator_updates": [
				{
					"pubkey": {
						"type": "ed25519",
						"data": "FRDvFQhFuLKP/Cue3qG6dtJE0zzIahNMFCYbCIbuIAc="
					},
					"power": 1
				}
			]
		}
	}
}
```

## Steps to Reproduce the Problem
```
# Create multisig Tx
go run ./cmd/validators multisig-new  -power=1 -pubkey="FRDvFQhFuLKP/Cue3qG6dtJE0zzIahNMFCYbCIbuIAc=" -multisig=1 > myTx.bin

# View
go run ./cmd/validators multisig-view  < myTx.bin
```

## Additional info
The doc is very bad in which format the multiSig parameter should be submitted. I made an assumption that it is simple integer and the CLI tool takes care of proper encoding.

Would be good to verify the other steps to modify a validator and actually improver the doc for a real use case. I tried the following:
```bash
# Create multisig Tx
go run ./cmd/validators multisig-new  -power=1 -pubkey="FRDvFQhFuLKP/Cue3qG6dtJE0zzIahNMFCYbCIbuIAc=" -multisig=1 > myTx.bin

# View
go run ./cmd/validators multisig-view  < myTx.bin

# Sign
go run ./cmd/validators multisig-sign -key XXXXXX -tm https://bov.hugnet.iov.one:443 < myTx.bin >myTx.bin.signed

# View again
go run ./cmd/validators multisig-view  < myTx.bin.signed

# Submit
go run ./cmd/validators multisig-submit -tm https://bov.hugnet.iov.one:443 < myTx.bin.signed

# Result
cannot broadcast transaction: CheckTx error: (3) Unauthorized
```

**Comment by ethanfrey** [comment]
We will merge validators functionality into the new `bnscli` tool.
Make sure we support mutlisigs properly in the `bnscli` tool and validator support integrated and you can close this issue.
