### ISSUE TITLE
Fix protool docker image to stop downloading tools on every run.

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#701]
```docker run --rm -v /Users/romanuseinov/go/src/github.com/iov-one/weave:/work iov1/prototool:v0.2.0 prototool format -w
error downloading https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip: Get https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip: EOF
Make sure GitHub Releases has a proper protoc zip file of the form protoc-VERSION-OS-ARCH.zip at https://github.com/protocolbuffers/protobuf/releases/v3.7.1
Note that many micro versions do not have this, and no version before 3.0.0-beta-2 has this
make: *** [protofmt] Error 1```

I'm pretty sure this can be done by simply running all the needed tools as part of the Dockerfile initialisation to cache them.

**Comment by ethanfrey** [comment]
Nope. Running prototool once is a good idea, but not enough.

`/tmp` is set to the CACHE and is mounted as a temporary file system.
I think it needs a few changes to do so.

Also, it will only cache the version of protoc that is in the docker image setup.
You specify the version you want in the weave prototool.yaml file.

Ideal would be to use a permanent "cache" directory and download 3.6.1. 3.7.0 and 3.7.1 protobuf tools, so they are pre-cached.

I do like the idea, but not high priority.
Also, issue belongs on github.com/iov-one/prototool-docker repo

**Comment by ruseinov** [comment]
@ethanfrey I don't think we can create issues there, as it's a fork. It also cannot be added to the board.

I'd say this is a low hanging fruit and should probably be prioritised because it prevents from working on codec changes offline, which is pretty bad I'd say, but this is your call. 

I have a pretty good idea how to fix this.

**Comment by ruseinov** [comment]
I see no reason currently to precache more than one version, because it would require introducing a prototool.yaml config. Current default is 3.7.1 so I'll go with that for now, when that bumps - we can do it.

The prototool itself does not support ant flags to `prototool cache update` so that has to be overridden either through yaml or just fetches default.

**Comment by ethanfrey** [comment]
:+1:
