### ISSUE TITLE
Add token issuance to currency package and migration path for it

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#710]
**Is your feature request related to a problem? Please describe.**

We need a test for the migration paths. #660 was an attempt to do an artificial migration, but I came up with a more realistic and useful one. The general problem is token issuance. We cannot issue more tokens of existing types on the chain, not can we issue new types of tokens. For many use cases, a simple stock erc20 like token (eg. multisig issues fiat-backed token) is plenty 

**Describe the solution you'd like**

Create a `schema: 2` of `x/currency` and a migration path for it. All existing queries should work identical (thus backwards compatible with clients as well).

Changes requested:

1) Add `Configuration` with one field - `Admin Address`.
  - in schema 2: you can set this via genesis file
  - when migrating from schema 1 to schema 2, this is set to the current value of `migrations.Configuration.Admin` (this must be some governance address)
2) `TokenInfoHandler` no longer takes issuer as a constructor argument, but uses the value from `currency.Configuration`. Only this Address can authorize `NewTokenInfoMsg`
3) Change all names from `TokenInfo` -> `Token` (like the above)
4) Update protobuf definitions of tokens as below
5) Add new `IssueTokenMsg` that takes one coin, and must be authorized by the issuer of the given Token, and respect the maximum issuance. It mints X tokens in the target account and updates the `current_supply` (this message only exists for schema 2 and must fail on schema 1).
6) Create all proper migration paths, as well as enhancing the migrations package as needed. As far as I can tell, we need to register two functions - one batch and one lazy. Upon updating schema, we run the batch function to eg. set the new Configuration object. This is not called by the Bucket on demand, but actively. We can use the lazy function to update existing TokenInfo objects as they are loaded.

-----------------------

Current:

```proto
message TokenInfo {
  weave.Metadata metadata = 1;
  string name = 2;
}

message NewTokenInfoMsg {
  weave.Metadata metadata = 1;
  string ticker = 2;
  string name = 3;
}

```

Proposed:

```proto
message Token {
  weave.Metadata metadata = 1;
  string name = 2;
  bytes owner = 3 [(gogoproto.casttype) = "github.com/iov-one/weave.Address"];
  // this is zero on creation and updated with each issuance
  coin.Coin issued = 4;
  // zero or nil cap means no limit
  coin.Coin cap = 5;   
}

message NewTokenMsg {
  weave.Metadata metadata = 1;
  string ticker = 2;
  string name = 3;
  bytes owner = 4 [(gogoproto.casttype) = "github.com/iov-one/weave.Address"];
  // zero or nil cap means no limit
  coin.Coin cap = 5;
}

// IssueTokenMsg must be authorized by the owner registered for .Amount.Ticker
// It will increments Token.Issued, and fail if it would exceed Token.Cap
// If successful msg.Amount tokens are cash.Issued in msg.Dest account
message IssueTokenMsg {
  weave.Metadata metadata = 1;
  coin.Coin amount = 2;
  bytes dest = 3 [(gogoproto.casttype) = "github.com/iov-one/weave.Address"];
}
```

**Additional context**

This functionality may be valuable for many use-cases, such as e-money issuance. If only the governance board can authorize new tokens, we can hand-pick which tokens are issued on our chain.

**Comment by kmw101** [comment]
Migration will be done with another issue.
