### ISSUE TITLE
sigs.StdSignature.Metadata is unused

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#717]
## Expected Behavior

If the field is present, we should check the contents somehow. 
We should either enforce the contents of this field (even hardcoding 1 for now, or deeper integration with migrations package), or remove this field from StdSignatures, in order to not give the false impression this field is used.

## Actual Behavior

It is not even read in `Validate()`: https://github.com/iov-one/weave/blob/master/x/sigs/tx.go#L21-L35
It is not written when we `SignTx()`: https://github.com/iov-one/weave/blob/master/x/sigs/controller.go#L157-L161

## Additional info
Add any other context about the problem here (e.g. screenshots, links)

**Comment by ethanfrey** [comment]
I noticed that `FeeInfo` also has such a field: https://github.com/iov-one/weave/blob/master/x/cash/codec.proto#L32-L38

And it is unused in eg. `Validate`:
https://github.com/iov-one/weave/blob/master/x/cash/msg.go#L91-L108

**Comment by ethanfrey** [comment]
`Multisig` is just defined as `[][]byte` and not a struct, and therefore doesn't have such a field:

https://github.com/iov-one/weave/blob/master/x/multisig/tx.go#L3-L8

Whatever we do, let's unify this all and define behavior for middleware components

**Comment by husio** [comment]
I think it should be removed. I must have added it by a mistake without thinking about it enough.

The current migration implementation does not support middlewares. We do not know how to deal with the transaction migration as well. I believe that middleware fields (first 50 attributes being direct transaction attributes) are part of this issue and we do not plan to address it anytime soon.

**Comment by ruseinov** [comment]
Agreed with @husio on that one, no reason to keep this for now.
