### ISSUE TITLE
Remove timeout restriction for atomic swap

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#718]
## Expected Behavior

A user can choose an arbitrary timeout

## Actual Behavior

With the migration from escrow to aswap, a new minimal timeout of 24 hours from now was introduced

## Steps to Reproduce the Problem

weave v0.15.0, aswap module

## Additional info

Surprisingly, the blockchain got oppinionated about the question which atomic swap timeout is good for the user. On the one hand there are multiple risks related to timeouts that are not choosen wisely, many of which are discussed in https://github.com/iov-one/iov-core/blob/master/docs/atomic-swap-protocol-v1.md#risks. On the other hand, the minimal timeout makes high frequent trades impossible (which might very well be super low value trades).

Since the blockchain can never be clever enough to make a judgement, which timeout is good for which user in which situation, we should not pretend we are able to take that responsibility from the user. Timeout handling must be done in the client and needs to be carefully crafted in terms of UX, to allow the user to make smart decisions in a guided fashion. Thus I think we should remove any restriction on the timeout.

From a correctness perspective, there is also nothing wrong with timouts set in the past.

**Comment by kmw101** [comment]
A good assessment, let's move the timeout further up the stack where the end user decides. The timeout will be a mandatory field in the UI so we don't end up with the situation where there is no timeout.
