### ISSUE TITLE
Introduce a wiki(ish) knowledge base.

### ISSUE THREAD

**Issue by husio** [iov-one/weave#726]
I do not know a single company that does not have this problem, so we must be doing something right :wink: 

Currently, we are using a mixture of software/methods/places to store and share information.
1. we use sphinx and read the docs for [weave documentation](https://weave.readthedocs.io/en/latest/),
2. we are using GitHub wiki on private ops repository for ops-related notes,
3. we are using `doc.go` for some of the usage examples and explanations,
4. we are using `README.md` in `weave` for some other usage examples and explanations,
5. we are using `DEVELOPER.md` for other notes.

There are probably more places that I have simply forgot about.

The problem is that this is in my opinion too chaotic. Too many places, too many formats.

I would make two exceptions to this list - weave documentation on read the docs (1.) and `doc.go` (3.) should be excluded as it is quite complete and serves well. What I think we should focus on are all other places.

We have a lot of pages on GitHub wiki (2.). In my opinion this the worst medium we use today. I like markdown. I like that GitHub wiki is easy to edit. I don't like how hard it is to find anything there. Content is randomly placed. Seach is terrible.

Both `README.md` (4.) and `DEVELOPER.md` (5.) seem to serve the same purpose. The problem is that there is no rule where to put what and where to find those files. There is no structure in those files. Content seems to be getting outdated.

I do not have a solution proposal. I have described the problem that I think we have and if we agree on it, we should come up with a solution or a list of possible solutions to try out.

--- 

I would like to document how to use [`bnscli`](https://github.com/iov-one/weave/tree/master/cmd/bnscli) and I do not know where should I do this. Readme? Dveleoper? `-help` flag? wiki?

**Comment by ethanfrey** [comment]
Did I hear a job for a Technical Writer? @davepuchyr

**Comment by orkunkl** [comment]
I would be amazingly glad if this issue is resolved. Weave documentation requires a lot of crawling around

**Comment by ethanfrey** [comment]
We have come up with a few concrete proposals, but let's clarify requirements:

- [ ] Easy to write (also for non-hardcore devs.... so no latex)
- [ ] Easy to read (not too ugly, some formatting, links, images, etc)
- [ ] Easy to find (nice table of contents, built-in search)
- [ ] Easy to build (both in CI and local dev machines)
- [ ] Public facing (not for private/ops docs... design to be world readable)

From that, we have agreed upon a few more detailed points:

- [ ] Code in git
- [ ] Update with PR
- [ ] Use Markdown as format to edit
- [ ] Host in static server, github pages if possible

**Comment by ethanfrey** [comment]
After some discussion, I think there are two contenders to this:

1) [Read the docs](https://weave.readthedocs.io)

Stick with current apporach, Use MD not RST. Clean it up and reorganize.

2) [Docusaurus](https://docusaurus.io/en/)

Facebook build engine, using server-rendered react and node. Uses algolia backend for fast elastic search results. Example:  https://docs.accordproject.org/ (try the search with network inspector open)
https://docusaurus.io/en/.

**Comment by husio** [comment]
If the build can be done via CI, then I don't think it matters what is building the documentation. 

For me the perfect work flow is quite simple from the user perspective.
When editing:
1. I am editing a file locally then push it via `git` (or edit via GitHub interface if I am a "normal" user)
2. I can either push directly to `master` branch or create a pull request
3. My changes are instantly picked by the CI, documentation is rebuild within 5min.

When using the documentation:
1. I expect clean HTML with minimal CSS and no Javascript required
2. Search option provides full text search for the whole documentation

**Comment by ethanfrey** [comment]
I like that workflow bit. And docker for local/CI builds is nice.

> I expect clean HTML with minimal CSS and no Javascript required

Afaik, almost all search bars use javascript for auto-complete/preview, since like 7 years.
I agree it should render fine without js though.

What is reason for minimal CSS?

**Comment by husio** [comment]
Those are perfect workflows. We may not be able to find anything that fulfills all of them. If javascript is required only for search, then I think we can accept this. If javascript is mandatory to load content and there is 2MB of it to download, then this is unacceptable.

> What is reason for minimal CSS?

It might be a personal preference. For me [minimal is good](https://tendermint.com/docs/) (high contrast, very little colors, text is pleasure to read) and [some are bad](https://tendermint.com/rpc/) (small letters, a lot of spacing, low contrast, many colors)

**Comment by ethanfrey** [comment]
Ahhh... I thought minimal css meant very small css file.

I like clear design as well. Sometimes css is big to handle all the spacings. But ideally not lots of colors/fonts/styles

**Comment by ethanfrey** [comment]
I would propose two spikes:

One to try to make a sample docusaurus project with search (grab some wiki docs or other, don't spend much time on content)

One to try out readthedocs with markdown and custom style (anything else desired)?

I will create two repos to try out for this, so we can have simple CI, etc. 
* https://github.com/iov-one/doc-saurus
* https://github.com/iov-one/doc-rtd

Grab whatever sample markdown files you want for this.... focus is not on the content, but on the easy of use and the output quality

**Comment by husio** [comment]
Here is my approach with sphinx & read the docs https://test-sphinx-iov.readthedocs.io/en/latest/

Some learning and good to know:
- any file can be either markdown or restructured text. Index is .rst because it is a more powerful format that allows for example for table of contents,
- there is [a ton of themes](https://sphinx-themes.org/) to pick from. I went with `flask` which is almost the same as default,
- `make html && python3 -m http.server` to run documentation locally. Full text search works locally using a static javascript generated index,
- because of the above, pushing generated HTML as GitHub page would provide a basic full text search,
- I have not tested but there seems to be [an extension for GitHub pages](http://www.sphinx-doc.org/en/master/usage/extensions/githubpages.html),
- read the docs allows for private documentation. [Privacy levels](https://docs.readthedocs.io/en/stable/privacy.html) together with a private repository might be a good solution for internal documentation,

**Comment by ethanfrey** [comment]
Nice progress @husio 
Can you link to the code? Ideally push to https://github.com/iov-one/doc-rtd

**Comment by orkunkl** [comment]
I've almost finished my example with docusaurus: https://iov-one.github.io/doc-saurus/
Currently search do not work but it will soon. Reason is: docusaurus using [Algolia docsearch](https://community.algolia.com/docsearch/) service which is free to use but you have to send them your github pages link and get approved. Waiting for approval for doc-saurus. I will recieve an api key and put it into [siteConfig.js](https://github.com/iov-one/doc-saurus/blob/master/website/siteConfig.js#L37). Impressively easy.

Outputs: 
 - It is pretty easy set it up and run.
 - I did not touch any node js file. You only have to add your `md` file under `docs` and refer it in couple of json([siteConfig.js](https://github.com/iov-one/doc-saurus/blob/master/website/siteConfig.js#L47)) files. That's all.
 - Enabling travis-ci seems pretty easy [setup link](https://docusaurus.io/docs/en/publishing#using-travis-ci). Could not do it because I need access to travis ci (I dont want keep you waiting for my spike report)
 - Custom theme could be achieved by simple adjustments to [static folder](https://github.com/iov-one/doc-saurus/tree/master/website/static).
 - [Versioning](https://docusaurus.io/docs/en/versioning) is quite easy. For seperating versioned document you just have to classify them as `website/versioned_docs/version-${version}`

 - Disadvantages: No auto conversion to pdf.

**Comment by ethanfrey** [comment]
I reviewed both approaches. Here is my feedback:

- Piotr's approach seems somewhat simpler to set up, as everything is built into readthedocs by default. Like search. Also the CI integration with github hooks.  Nice to see it worked with vanilla md copied from our repo. However, the output was somewhat lacking for me.

- Orkun's approach seemed a bit more work to set up (you need to set up github pages, algolia, travis), but once that is done one time, it doesn't seem the build steps are harder. I definitely like the ability for the intro page and customizable links. Such that the top navbar or main buttons lead to sub-sections, and there are sidebars only on the subsections (eg. tutorial). I think that allows much better potential when we have many different topics together in one repo (weave tutorial, api/binary specs, iov-core intro, bapp/extension development, etc.)  I would like to see the search working, but I understand the reason, and I did see it on other docusaurus sites and I liked it there.

I would propose to go with docusaurus with the following steps:

- [ ] Rename repo, so it is hosted at https://iov-one.github.io/docs
- [ ] Set up build process on Travis CI
- [ ] Remove most of the sample design that comes out of the box (just tag before removing, so you can use that for reference when adding).
- [ ] Set up subsections/placeholders for: weave intro (current rtd), weave tutorial, iov-core intro, weave api specs, even coding stardards and pr flows
- [ ] Set up algolia starter plan (smallest paid one) to power search 
- [ ] Send request for design team to provide nice css for this site

After that, @orkunkl can begin on #840 - #842 in this repo. Moving other docs into this repo can happen later.

**Comment by orkunkl** [comment]
I propose instead of renaming the repo, I should create a new one named `docs`. Since it was trying to make it fast, there might be missed points.

**Comment by husio** [comment]
I think the first part of this issue is complete - we are hosting documentation at https://docs.iov.one/docs/doc1

Second task is to agree to a few simple rules and a helpful description how we maintain the content on this page.
- how do we apply changes to the content
- basic formatting rules (just an example: use `##` for section, `###` for subsection, don't use `#` or `####`)

Third and the last step will be to migrate all information spread around into this single place.

Does this make sense?

**Comment by orkunkl** [comment]
Quick fix: on [iov-one/docs](https://github.com/iov-one/docs) link on description ```The main point for iov documentation, published at https://iov-one.github.io/docs``` redirects to non-http version. @ethanfrey can you change it to https://docs.iov.one?

**Comment by ethanfrey** [comment]
I fixed the redirect. (May not be on your browser yet due to cached 301, but tested it is served properly with curl now. Also, the link on the repo has been updated

**Comment by ethanfrey** [comment]
> Second task is to agree to a few simple rules and a helpful description how we maintain the content on this page.

It would be great to add all this workflow info to a top level README.md in the docs repo

**Comment by ethanfrey** [comment]
> Third and the last step will be to migrate all information spread around into this single place.

Definitely, I think that is a huge task, and I would create separate issues for each piece of documentation to migrate, closing this once the basic structure is there to insert new docs.

**Comment by ethanfrey** [comment]
We have the place for this now in https://github.com/iov-one/docs

Please ensure search is working
