### ISSUE TITLE
Ability to transfer a name to another owner

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#737]
**Is your feature request related to a problem? Please describe.**
When a name is registered it belongs to one address and cannot be transferred.

**Describe the solution you'd like**
As a user I want to be able to transfer my name to another address.

**Describe alternatives you've considered**
Not applicable

**Additional context**
For Weave 0.17 release

**Comment by ethanfrey** [comment]
* There is no need of the recipient to accept it.
* Owner of a name can submit a transaction to change the owner of a username to any valid Address

**Comment by husio** [comment]
Implemented in https://github.com/iov-one/weave/pull/771
