### ISSUE TITLE
Supports all messages with bnscli as-batch, as-proposal

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#739]
- [ ] Please add all supported types to the batch switch: https://github.com/iov-one/weave/blob/efe6ed806da868fc8fc8c46131bb0af4930c2c73/cmd/bnscli/cmd_batch.go#L41-L54
- [ ] Please add all supported types the the as-proposal command (notably it has one more than batch :mag: https://github.com/iov-one/weave/blob/efe6ed806da868fc8fc8c46131bb0af4930c2c73/cmd/bnscli/cmd_gov.go#L50-L62 and https://github.com/iov-one/weave/blob/efe6ed806da868fc8fc8c46131bb0af4930c2c73/cmd/bnscli/cmd_gov.go#L70-L88

**Comment by husio** [comment]
This is implemented in https://github.com/iov-one/weave/pull/735
