### ISSUE TITLE
Add basic key management to bnscli

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#740]
clitests is a great directory. But there is no example of signing, nor is it clear where this key comes from (used in one example).

I would propose adding a few commands (change syntax please, but the functionality would be good)

- [x] `bnscli keygen > keyfile` - generate a new random private key and store in the same format expected as input to `bnscli sign`
- [x] `bns address < keyfile` - print out a hex-address associated with this private key, to properly set `src`
- [x] Some tests with signing and extracting address in `clitest`

As well as anything else you think is useful here (you may have to add a `-nonce` flag to `bnscli sign` as an alternative to querying the nonce from the blockchain for testing purposes)

**Comment by ethanfrey** [comment]
What branch are those fixes on?

Thanks for tackling it.

**Comment by husio** [comment]
https://github.com/iov-one/weave/pull/745
