### ISSUE TITLE
weave.readthedocs is not linked to most explanatory version

### ISSUE THREAD

**Issue by orkunkl** [iov-one/weave#758]
As a new user of weave framework while working on [iov-one](https://github.com/iov-one/tutorial) with @ethanfrey I've noticed [weave.readthedocs](https://weave.readthedocs.io/en/latest/index.html) is not linked to the best version. I am lucky Ethan pointed out the correct version but for a new learner it is difficult to find out its existence. This needs to be fixed.

**Comment by ethanfrey** [comment]
Yes, the current version is nicer but only a portion of the info in the older version.

It definitely needs to be fixed and I am glad you have been reading the docs. I'd be happy for anyone else to pitch in in it as welll

**Comment by orkunkl** [comment]
Collecting docs to https://docs.iov.one/docs/intro.html. Closing the issue.
