### ISSUE TITLE
Simplify weave.Iterator interface (and all usages)

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#763]
**Is your feature request related to a problem? Please describe.**

A very interesting PR comment https://github.com/iov-one/weave/pull/762#discussion_r292935828 spurred the idea of revisiting the weave.Iterator API. It is quite old and not heavily used, so why not take a second look.

The current interface is

```go
type Iterator interface {
	// Valid returns whether the current position is valid.
	// Once invalid, an Iterator is forever invalid.
	Valid() bool

	// Next moves the iterator to the next sequential key in the database, as
	// defined by order of iteration.
	//
	// If Valid returns false, this method will panic.
	Next() error

	// Key returns the key of the cursor.
	// If Valid returns false, this method will panic.
	// CONTRACT: key readonly []byte
	Key() (key []byte)

	// Value returns the value of the cursor.
	// If Valid returns false, this method will panic.
	// CONTRACT: value readonly []byte
	Value() (value []byte)

	// Close releases the Iterator.
	Close()
}
```

And a for loop to iterate over everything is like:

```go
func consumeIterator(itr weave.Iterator) ([]weave.Model, error) {
	defer itr.Close()

	var res []weave.Model
	for itr.Valid() {
		mod := weave.Model{
			Key:   itr.Key(),
			Value: itr.Value(),
		}
		res = append(res, mod)
		err := itr.Next()
		if err != nil {
			return nil, err
		}
	}
	return res, nil
}
```

**Describe the solution you'd like**

@husio implicitly proposed a much simpler interface:

```go
type Iterator interface {
        // Next returns (nil, nil, ErrDone) when there are no more value left
	Next() (key []byte, value []byte, err error)
	Stop()
}
```

Along with a special ErrDone to signal the end of iteration, this actually seems like it covers all needed usages of the interface. I think there are no real cases when we need to read data multiple times between calling Next(), which is the only functionality lost here.

Consuming the entire interface would then look like:

```go
func consume(itr Itr) ([]weave.Model, error) {
	defer itr.Stop()
	var res []weave.Model

	key, value, err := itr.Next()
	for err == nil {
		mod := weave.Model{
			Key:   key,
			Value: value,
		}
		res = append(res, mod)
		key, value, err = itr.Next()
	}
	if err == ErrDone {
		err = nil
	}
	return res, nil
}
```

**Comment by ethanfrey** [comment]
(Note that this can also include cleaning up current implementation as proposed in that PR comment as well, as the new API makes implementation as well as usage simpler)

**Comment by ruseinov** [comment]
This looks like a proper iterator to me. I would, however, use `Close()` and not `Stop()` to close the iterator as it's consistent with other golang libraries and makes more sense. `Stop()` implies that we are going somewhere, which we are not before we call `Next()`.

**Comment by ethanfrey** [comment]
After digging through google to see proper terminology, it is refered to as "closing an iterator".

However, both python and javascript snippets show `next()` and `return()`.

I will use `Return` instead of `Stop` or `Close` to end it

**Comment by ruseinov** [comment]
IMHO Return is cryptic in that regard, I'd much prefer explicit Close(). And neither python nor javascript are good examples of nice language api.

But the implementation is up to you. Just as a user I don't really understand `Return()` in context of operator and as a method name in general.

**Comment by ethanfrey** [comment]
Went with `Release()`
