### ISSUE TITLE
Tiny nft/username

### ISSUE THREAD

**Issue by husio** [iov-one/weave#767]
Original NFT specification can be found on GitHub https://github.com/iov-one/bcp-spec/blob/master/library/demo/NonFungibleTokens.md

I believe that [the current `nft/username`](https://github.com/iov-one/weave/tree/master/cmd/bnsd/x/nft/username) implementation can be greatly simplified if implemented directly. Forget the original NFT specification. Drop all abstractions. Do not build generic solution. Focus on the problem at hand and think of the smallest implementation to solve the problem.

---

_Username is used for both the token and the actual username (ie `piotr*iov`). To avoid confusion of those two terms, the first will be called `Token` and the second `username`._

> There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.
---

My understanding of the `nft/username` package functionality can be compared to a domain name. We want to maintain a register of username strings in format `<name>*<namespace>`. A single username points to a blockchain network and an address on that network. To simplify the implementation neither blockchain network string nor the address is validated. Namespace string is case sensitive.

BNS users will make request providing a username (ie `alice*iov`) and in exchange they expecte the corresponding blockchain string and an address.

Token entity is following a set of rules:
- each Token is using a username as an ID
- username is case sensitive and must contain `*` symbol
- username must follow additional rules as for what are allowed `<name>` and `<namespace>` values
- many Token entities can point to the same address on the same blockchain network
- each Token can point to any address on any blockchain network
- each Token has an owner, that is a weave address

The above can be represented by the following protobuf declaration. This is our Token model as stored in the database. The username value is used as the key.

```protobuf
// Token model represents a NFT username mapping to an address together with
// all metadata.
//
// Each Token model is stored using the username as the key. This guarantee
// that the name is unique.
//
// Each token points to a blockchain and an address on that blockchain. Both
// blockchain ID and address are an arbitrary string as we do not want to limit
// ourselves to certain patterns.
message Token {
  weave.Metadata metadata = 1;
  // An arbitrary blockchain ID.
  string blockchain_id = 2;
  // Address is not a weave.Address as we cannot know what is the format of an
  // address on the chain that this token/username instance links to.
  string address = 3;
  // Owner is a weave address that owns this token. This is used only 
  // for permission tests.
  string owner = 4 [(gogoproto.casttype) = "github.com/iov-one/weave.Address"];
}
```

There are three requests that can be made in order to alter a Tokens collection state. 

We can register a username by creating a Token if that username is not yet registered. The created token owner is always the main transaction signer. Ownership can be transferred with another message.

```protobuf
// RegisterTokenMsg is creating a new username token. The owner is always set
// to the main signer.
message RegisterTokenMsg {
  weave.Metadata metadata = 1;
  // Username is the unique name of the token, for example alice*iov
  string username = 2;
  // An arbitrary blockchain ID.
  string blockchain_id = 3;
  // Address is not a weave.Address as we cannot know what is the format of an
  // address on the chain that this username instance links to.
  string address = 4;
}
```

An ownership of a token can be transferred. Only the owner of a token can request this operation. New owner does not have to accept this change in order to succeed.

```protobuf
// ChangeTokenOwnerMsg is a request to transfer an ownership of a username.
// It must be signed by the current token owner. Acceptance of the new owner
// is not required.
message ChangeTokenOwnerMsg {
  weave.Metadata metadata = 1;
  // Username is the unique name of the token, for example alice*iov
  string username = 2;
  // Owner is a weave address that owns this token.
  string owner = 3 [(gogoproto.casttype) = "github.com/iov-one/weave.Address"];
}
```

A token can be modified in order to point to a new address or a different blockchain network. This operation can be done only be the token owner.

```protobuf
// ChangeTokenAddressMsg is a request to change the address that this token
// points to. Only an owner of a token can request this operation.
message ChangeTokenAddressMsg {
  weave.Metadata metadata = 1;
  // An arbitrary blockchain ID that the new address belongs to.
  string new_blockchain_id = 2;
  // An arbitrary address
  string new_address = 3;
}
```

---

This is my proposal of the username implementation. I think that having the protobuf declarations, writing handlers is quite easy. Integration with the `bns` is then trivial because we use `weave` :muscle: 

Let me know what you think.

**Comment by ethanfrey** [comment]
Looks good and I agree with most the points. Just one comment

> username is case sensitive and must contain * symbol

Namespace management will need a reference to a namespace token. Add this is not fully specified, or shall I say, Dave asked us not to implement the spec by Martin add they will come up with a new spec, we cannot yet implement Namespaces. However, will should plan to add them shortly. 

Right now we store no namespace, client assumes iov. 
We could add a separate field here, that is always iov. 
However, please sie them separately, so we can use it for lookups later. 

Eg
String name
String namespace

Client can combine them with a *

Other than that minor point, sounds good and I'm happy to see an implementation

**Comment by ethanfrey** [comment]
The other point is that if needs a list of( blockchain Id address) not just one. Default behavior of the wallet now is to register 4 chains to the same name upon creation. Creston and change address should both accept lists. 

You can sort them before saving for determinism. And if Change Token Address removes an entry where address is null, this will function like add and remove and modify, which we should support.

**Comment by husio** [comment]
> The other point is that if needs a list of( blockchain Id address) not just one. Default behavior of the wallet now is to register 4 chains to the same name upon creation. Creston and change address should both accept lists.

Wouldn't it be better to keep the creation message as it is and use a batch transaction? It would keep the implementation simple and the functionality remains the same.

**Comment by ruseinov** [comment]
> Wouldn't it be better to keep the creation message as it is and use a batch transaction? It would keep the implementation simple and the functionality remains the same.

This would be limited by the max size of batch transaction then, which is not right in case you want to register more than `maxBatchSize` at the same time.

**Comment by husio** [comment]
Max batch size is [currently 10](https://github.com/iov-one/weave/blob/master/x/batch/decorator.go#L16) which indeed makes it unsuitable for a mass registration.

I can change the [`RegisterTokenMsg`](https://github.com/iov-one/weave/pull/771/files#diff-6806e712895891db247966f3a28e0882R43) to accept multiple username to location mappings. That would mean that the user can no longer be charged for a name registration but only for a message. If this is not a problem, then I can apply the change.
