### ISSUE TITLE
Add governance to cmd/bnscli

### ISSUE THREAD

**Issue by husio** [iov-one/weave#772]
As [discussed briefly](https://internetofvalues.slack.com/archives/GFASTCVPZ/p1560766927011000) as a governance member, I would like to use `cmd/bnscli` to access `x/gov` functionality so that I can participate in the governance process.

The current `bnscli` version contains support [for the proposal creation](https://github.com/iov-one/weave/blob/master/cmd/bnscli/cmd_gov.go#L20). Support for other operations must be added.

## Acceptance criteria
- [x] add support in `cmd/bnsd` for creating the [`DeleteProposalMsg`](https://github.com/iov-one/weave/blob/master/x/gov/codec.proto#L202),
- [x] add support in `cmd/bnsd` for creating the [`VoteMsg`](https://github.com/iov-one/weave/blob/master/x/gov/codec.proto#L217),
- [x] add support in `cmd/bnsd` for creating the [`TallyMsg`](https://github.com/iov-one/weave/blob/master/x/gov/codec.proto#L230),
- [x] add support in `cmd/bnsd` for creating the [`TextResolutionMsg`](https://github.com/iov-one/weave/blob/master/x/gov/codec.proto#L239),
- [x] add support in `cmd/bnsd` for creating the [`UpdateElectorateMsg`](https://github.com/iov-one/weave/blob/master/x/gov/codec.proto#L244),
- [x] add support in `cmd/bnsd` for creating the [`UpdateElectionRuleMsg`](https://github.com/iov-one/weave/blob/master/x/gov/codec.proto#L253),

**Comment by kmw101** [comment]
Further analysis and discussion on use cases needed.

**Comment by kmw101** [comment]
Test tools for Governance
=================
!!! Not intended for release on mainnet !!!
-----------------------------------------------

While the voting tools are being built in IOV Core and the UI team there is a need for some internal tools to test the following:

- [ ]  Create a proposal to add a validator
- [ ]  Create a proposal to remove a validator
- [ ]  Vote on validator committee proposals
- [ ]  Run a tally on validator voting.
- [ ]  Vote on economic committee proposals created by the BNSCLI tool
- [ ]  Generate a tally message

This does not need to be a nice binary with shell scripts, some simple tools in Go will do.
