### ISSUE TITLE
Normalize message names

### ISSUE THREAD

**Issue by husio** [iov-one/weave#774]
As a developer, I want to define a naming pattern for the protobuf declared messages, so that when exported to a global namespace it is obvious which functionality they belong to.

--- 

Protobuf import does not preserve a namespace. When exposing messages, they are all sharing the same namespace. This is confusing when messages are not descriptive. For example ` multisig.CreateContractMsg create_contract_msg = 56;`

When an extension is imported by an extension, the attribute name must be the same as the type. For example `escrow.ReturnEscrowMsg return_escrow_msg = 54;`

## Acceptance criteria
- [x] define and document the naming pattern for the message protobuf declarations
- [x] apply the above rule to all existing declarations, especially [bnsd declarations](https://github.com/iov-one/weave/blob/master/cmd/bnsd/app/codec.proto)
- [x] update `bnsd` to use type name as attribute names (ie `escrow.CreateEscrowMsg create_escrow_msg = 52;`)

**Comment by husio** [comment]
My proposal for the format is set of guidelines:
- keep message names descriptive rather than short,
- do not assume context - avoid short forms `CreateMsg` or `DeleteMsg`. Prefer longer `CreateEscrowMsg` or `DeleteProposalMsg`
- avoid popular names like `Blockchain`, `Token` or `User`

When using message declarations in Go, structure name is prefixed with a package name, for example `escrow.CreateEscrowMsg`. While this looks wrong in Go, it is not the case in other languages like Javascript (or protocol buffer declarations). When declaring messages, ignore the fact that Go supports namespaces.

**Comment by ethanfrey** [comment]
The javascript protobuf definitions are also included in namespaces. And I assume any other language will support this as well

We use eg, `codec.cash.SendMsg`, `codec.escrow.CreateEscrowMsg`. I think avoiding the package name in the message name is good practice.

**Comment by ethanfrey** [comment]
Was not closed by #797, but will be closed by #799
