### ISSUE TITLE
Revisit unhandled error in store/Iterator

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#779]
**Is your feature request related to a problem? Please describe.**
I am not fully aware of the implication of this unhandled error. This issue is for tracking a proper investigation of 
https://github.com/iov-one/weave/pull/770/files#diff-03a1384824f3186c21d06f2ac14a8618R112

**Describe the solution you'd like**
Either doc and ignore the error, handle it or panic. 

**Additional context**
This was discovered during gometa linter run.

**Comment by ruseinov** [comment]
This can now be closed as it's fixed by @ethanfrey's rewrite of the iterator
