### ISSUE TITLE
Enable registering handler/callback for begin block

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#78]
We can register code that is called every begin block.
This will get the block header, along with the list of validators that signed it (https://github.com/confio/weave/pull/76#issuecomment-398703272)

* Allow a way to register a handler on app construction (like normal handler)
* Allow a way to register many of them to be called one after another (like MulitAuth)
* Create a design for cron scheduler handler, an extension that allows executing delayed tasks. (eg. run this at block 50, other tasks at 47, other at 93 and it will make sure the callback is called with the proper data at the proper time)

**Comment by ethanfrey** [comment]
We have a Ticker callback on begin block.

Using it for a cron job system is not done.

@alpe what do you think about this? close it or go forward? maybe it fits with your elections use case #671

**Comment by husio** [comment]
If I understand correctly, we want to implement a cron like mechanism for scheduling message (or transaction?) execution.

Below is a description of a quite naive a straightforward implementation. Let me know if it makes sense. 

1. There is a bucket that can store message. Each key is a block height value containing a list of messages (zero or more). 
2. When a message is scheduled for the future execution, it is stored under the key corresponding to its execution time.
3. A new decorator is created. Before the original transaction is processed, it will check the bucket if there are messages queued for the execution. If yes, it will execute them first.

I think there are two weaknesses in this approach:
1. The execution of a message is bound to a transaction processing. This means that the message scheduling must be block height based and cannot be wall clock based.
2. In point 3 the decorator is responsible for processing scheduled messages. This means that we piggyback on the original transaction and cannot return result for all operations.

I think it would be much easier to have some kind of external source of ticking. With a transaction message "tick", we would register for it the usual handler. Only if there are messages scheduled, `Check` and `Deliver` would process and not return error. Failed processing can return an error as well.
Having an external ticker enables us to implement wall clock dependent cron as well.

**Comment by ethanfrey** [comment]
>     There is a bucket that can store message. Each key is a block height value containing a list of messages (zero or more).
>    When a message is scheduled for the future execution, it is stored under the key corresponding to its execution time.

Yes.

>    A new decorator is created. Before the original transaction is processed, it will check the bucket if there are messages queued for the execution. If yes, it will execute them first.

Not needed. We just have a bucket with no handlers or decorators.

> I think it would be much easier to have some kind of external source of ticking. With a transaction message "tick", we would register for it the usual handler.

Nice that you ask, [app.BaseApp](https://github.com/iov-one/weave/blob/6af594b653fa3711f0e6a5c6371274fe19d719ce/app/base.go#L15)
 does have [weave.Ticker](https://github.com/iov-one/weave/blob/6af594b653fa3711f0e6a5c6371274fe19d719ce/handler.go#L37-L41), which is executed on [BeginBlock](https://github.com/iov-one/weave/blob/6af594b653fa3711f0e6a5c6371274fe19d719ce/app/base.go#L75-L87)

See how amazing weave is :smile:
