### ISSUE TITLE
make deps not working

### ISSUE THREAD

**Issue by shikharfb** [iov-one/weave#780]
## Expected Behavior
After cloning the repository, when I do `make deps`, it returns an error `make: *** No rule to make target 'deps'.  Stop.`

## Actual Behavior
It should build the dependencies as far as I know

## Steps to Reproduce the Problem
```
go get github.com/iov-one/weave
cd $GOPATH/src/github.com/iov-one/weave
make deps
```

Environment, commands

1.  Ubuntu 19.04
2.  Go >= 1.12.5

## Additional info
Am I missing something? I would like to know if I'm doing `go get github.com/iov-one/weave` in the correct directory or not.

**Comment by alpe** [comment]
The README was not updated unfortunately when the project was updated to [Go modules](https://github.com/golang/go/wiki/Modules)
The steps are now:
```bash
# cd into to your workspace that is not in your GOPATH
git clone https://github.com/iov-one/weave.git
cd weave
make install
```

**Comment by shikharfb** [comment]
Doesn't seem to work. 
`mycoind` or `tendermint` commands not found.

This shows when I do make install:

```
for ex in cmd/bcpd cmd/bnsd cmd/bnscli; do cd $ex && make install && cd -; done
make[1]: Entering directory '/home/shikhar/go/src/github.com/weave/cmd/bcpd'
go install -mod=readonly -ldflags "-X github.com/iov-one/weave.Version=manual" .
make[1]: Leaving directory '/home/shikhar/go/src/github.com/weave/cmd/bcpd'
/home/shikhar/go/src/github.com/weave
make[1]: Entering directory '/home/shikhar/go/src/github.com/weave/cmd/bnsd'
go install -mod=readonly -ldflags "-X github.com/iov-one/weave.Version=manual" .
make[1]: Leaving directory '/home/shikhar/go/src/github.com/weave/cmd/bnsd'
/home/shikhar/go/src/github.com/weave
make[1]: Entering directory '/home/shikhar/go/src/github.com/weave/cmd/bnscli'
CGO_ENABLED=0 go install -mod=readonly -ldflags "-X main.gitHash=511dc5dcbe9bdcd4f96335db03f24c8fa605a240 -extldflags \"-static\"" .
make[1]: Leaving directory '/home/shikhar/go/src/github.com/weave/cmd/bnscli'
/home/shikhar/go/src/github.com/weave
```

Do i need to `source` anything?

**Comment by alpe** [comment]
I am very sorry but the doc is outdated about building the example app and was not maintained proper. We do not create a `mycoind` binary nor install `Tendermint` from the project root anymore.
Instead we build two other ABCI compatible apps:
*  `cmd/bnsd` - Blockchain Name Service
* `cmd/bcpd` - Blockchain of value reference implementation
The doc is not reflecting this proper nor do we show good examples how to start them in a local environment. 
As a quick solution, I would ask you to use the [docker setup](https://github.com/iov-one/weave/tree/master/cmd/bnsd#running-manually) . You can find the latest artifacts on [docker hub](https://hub.docker.com/u/iov1/). 

I will revisit this section in the docs. Thanks for bringing this up!

**Comment by alpe** [comment]
Not solved, yet

**Comment by ethanfrey** [comment]
@shikharfb  if `make install` works properly (which it seems so), it will install them in `$GOPATH/bin`, default to `$HOME/go/bin`. Please check there and make sure it is in your `PATH`. You usually want to set that up in `~/.bashrc` or equivalent

**Comment by ethanfrey** [comment]
README with references to old code was updated as part of https://github.com/iov-one/weave/pull/798

If there are still issues following the readme, please re-open
