### ISSUE TITLE
cmd/bnsd/x/username: add support for genesis file

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/weave#794]
**Is your feature request related to a problem? Please describe.**
We want to prevent name squatting starting from block 1.

**Describe the solution you'd like**
We'd like to be able to register names in the genesis file and have them owned by IOV.

**Describe alternatives you've considered**
Submitting txs to register the names would cost us tokens and not guarantee that we get the names.

**Additional context**
We'd like to put the most popular domain names, twitter handles, instagram handles, etc in the genesis file so that their "rightful" owners can claim them.  There could be tens of thousands or more names in the genesis file.

This issue is analogous to #219.

**Comment by kmw101** [comment]
Could we have a definitive list of "popular" names?

**Comment by davepuchyr** [comment]
> Could we have a definitive list of "popular" names?

Yes, in time.

**Comment by davepuchyr** [comment]
> Could we have a definitive list of "popular" names?

Dasha put together [this list](https://docs.google.com/spreadsheets/d/1c_q3L7g89gJJBZb9ajp0Xid1nOoyOa5rZ9KOf3J_zwE/edit#gid=2103889525).  It is a living document until the mainnet genesis file is created.
