### ISSUE TITLE
Test tools for Governance

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#800]
Test tools for Governance
================
!!! Not intended for release on mainnet !!!
----------------------------------------------

While the voting tools are being built in IOV Core and the UI team there is a need for some internal tools to test the following:

- [ ] Create a proposal to add a validator
- [ ] Create a proposal to remove a validator 
- [ ] Vote on validator committee proposals
- [ ] Run a tally on validator voting.
- [ ] Vote on economic committee proposals created by the BNSCLI tool
- [ ] Generate a tally message 

This does not need to be a nice binary with shell scripts, some simple tools in Go will do.

**Comment by ethanfrey** [comment]
There is heavy overlap here and in #772 

Can you please merge them and close one?
In the meantime, I will place them both high on the backlog

**Comment by kmw101** [comment]
Overlap with #800 merged into #772
