### ISSUE TITLE
Rename .sender to .source in escrow.CreateMsg, .Escrow and .UpdatePartiesMsg

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#803]
- [ ] The CreateMsg docs say _If sender is not defined, it defaults to the first signer_ but there is no `sender` field.
- [ ] `Escrow.sender` -> `.source`
- [ ] `UpdatePartiesMsg.sender` -> `.source`

**Comment by ethanfrey** [comment]
Yes, there was some issue a while ago (when Isabella was here) to normalize naming. I think it was `src` and `dest`, not `sender` and `recipient`. Looks like we never completed that job.

`cash.SendMsg` has `src` and `dest` (reference)
`aswap` uses `src` and `recipient`
`paychan` also uses `src` and `recipient`
`escrow` has `sender` and `recipient`
`distribution` uses `recipients` for the list


So... we rename `sender` -> `src` universally.
And we should either standardize on `dest` (used in cash, which received most attention) or `recipient` (used most other places)

**Comment by ruseinov** [comment]
I would prefer these to be `source` and `destination` to make it self-explanatory.

I see no good reason to make these short as they are not part of a longer name like `execute_batch_msg` or something.

**Comment by ethanfrey** [comment]
Do we agree that in all messages and models:

`src` / `sender` -> `source`
`dest` / `recipient` -> `destination`

?

If so, please update the title and description. Seems fine with me unless there are objections
