### ISSUE TITLE
mycoind installation error

### ISSUE THREAD

**Issue by shikharfb** [iov-one/weave#807]
## Expected Behavior
`mycoind init` should work
## Actual Behavior
`mycoind : command not found`

## Steps to Reproduce the Problem
Installed `Tendermint` and built the `weave` application
```
rm -rf ~/.mycoind
tendermint init --home ~/.mycoind

mycoind init CASH bech32:tiov1qrw95py2x7fzjw25euuqlj6dq6t0jahe7rh8wp   <<<ISSUE here
```

## Additional info
Maybe the `mycoind` is not built properly. [Installation instructions](https://weave.readthedocs.io/en/latest/mycoind/installation.html) are insufficient.

**Comment by ethanfrey** [comment]
Ah... know I see where you are getting all these mycoind references.

Sorry, the docs are out of date. It was a work in progress that halted due to focus on MvP release. I will prioritize a review of the docs.

**Comment by shikharfb** [comment]
Well, it keeps me a little lsot. Would you direct me the correct way to work with this?

**Comment by ethanfrey** [comment]
Problem has been that docs have just been my Friday project when I can squeeze in time to do it, and I should spend 4-5 days a week doing other stuff.

Can you let me know what you want to do exactly?

I started pulling out code to help build an app at https://github.com/iov-one/weave-starter-kit which is much more modern than readthedocs, but also a bit rough. Please log any issues there.

We also have a mostly finished tutorial at https://github.com/iov-one/tutorial. If you look at https://github.com/iov-one/tutorial/blob/master/BESTPRACTICES.md and follow the linked PRs in order, it should give you raw info on how to build an app. We want to improve this into proper docs, but I think reading the code and PR comments gives an insight. Feel free to comment on those closes PRs for anything confusing - I can answer and this will make it into the planned docs.

**Comment by kmw101** [comment]
Workaround provided. No further comments and questions. Closing issue.
