### ISSUE TITLE
Link tutorial from readthedocs

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#811]
**Is your feature request related to a problem? Please describe.**

We have an out-dated tutorial in readthedocs, and the code has recently been removed from our repo.

We have a much newer and better tutorial in progress: https://github.com/iov-one/tutorial

**Describe the solution you'd like**

Once we complete documenting the tutorial (https://github.com/iov-one/tutorial/issues/15), we should link to that from the main weave readthedocs page.

**Comment by kmw101** [comment]
documentation is being covered in other issues. closing
