### ISSUE TITLE
Include UpdateConfigurationMsg in `bnsd` tx, write a scenario test to confirm it works.

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#815]
The message and it's handler seem to be implemented, but it's impossible to send the message to bnsd without including it to the transaction.

**Comment by ethanfrey** [comment]
This is about `cash.UpdateConfigurationMsg`, which afaik is the only adjustable config. We should add more later but one demo case is enough to get iov-core support.

The generic handler is in gconf, but we can only register specific instantiations of them.

**Comment by kmw101** [comment]
breaking change. Owner needed for gconf. Execute through governance? or directly?

**Comment by kmw101** [comment]
#710 migration scenario test.

**Comment by webmaster128** [comment]
Can we close this in favour of https://github.com/iov-one/weave/issues/911? UpdateConfigurationMsg exists. Sending it directly makes no sense since the cach configuration is owned by `cond:gov/rule/0000000000000002`, i.e. the fee needs to be updated via governance.

**Comment by webmaster128** [comment]
On mainnet the cash configuration is owned by governance:

```
      "cash": {
        "owner": "cond:gov/rule/0000000000000002",
        "//owner": "owned by economic executors",
        "collector_address": "cond:gov/rule/0000000000000002",
        "//collector_address": "reward fund - cash account",
        "minimal_fee": "0.5 IOV"
      },
```

This means `cash.UpdateConfigurationMsg` should be included in both `bnsd.Tx` and `bnsd.ProposalOptions`.
