### ISSUE TITLE
Change router.Handle notation

### ISSUE THREAD

**Issue by husio** [iov-one/weave#817]
As a developer, I want to change `router.Handle` notation so that handler registration and message declaration is less verbose.

The current [`router.Handle`](https://github.com/iov-one/weave/blob/master/app/router.go#L42) notation is
```go
func (r Router) Handle(path string, h weave.Handler)
```
First argument is the `path`, that is the same as the result of `Msg.Path()` that registered handler handles.

The above notation is correct and it can be improved. The current notation require us to [create a message in place and call `Path()`](https://github.com/iov-one/weave/blob/master/cmd/bnsd/x/username/handlers.go#L21-L23) to get the path value or to [declare the path value as a `const`](https://github.com/iov-one/weave/blob/master/x/paychan/msg.go#L20-L22). Both approaches are valid and can be improved.
Message path is used only by the [`app.Router`](https://github.com/iov-one/weave/blob/master/app/router.go#L26).

## Acceptance criteria

- [x] change the notation to require `weave.Msg` as the first arugment
```go
func (r Router) Handle(m weave.Msg, h weave.Handler)
```
- [x] adjust all handler registrations
- [x] remove all `const` declaration of the message paths. `Msg.Path` method should be the only place where the path is declared and available

**Comment by ethanfrey** [comment]
This does make registration much cleaner.

Nice simple change.
