### ISSUE TITLE
Remove `Path` method from weave.Msg interface

### ISSUE THREAD

**Issue by husio** [iov-one/weave#825]
As a programmer, I want to remove `Path` method from the [`weave.Msg` interface](https://godoc.org/github.com/iov-one/weave#Msg), so that `weave.Msg` is easier to implement.

_This proposal requires https://github.com/iov-one/weave/issues/817 to be implemented._

_There was a [brief discussion on a private channel about the topic](https://internetofvalues.slack.com/archives/GFASTCVPZ/p1561469619043300)._ :secret: 

I understand now where the message path value is used and maybe it is worth getting rid of it completely.

When a transaction is handled, first a message from that transaction is extracted via `GetMsg()` method (plus some special cases). The extracted message is used to determine which handler to use for it. [`app.Router`](https://github.com/iov-one/weave/blob/master/app/router.go#L27) is a mapping of a string to a handler. The string is "some" message type ID.
The router is the only place where the message path is used. Message path is used only internally (it is not exposed outside of the weave application) to route message by its type to a handler.

The same can be achieved using any value of any type. If the handler registration is modified to the form (see https://github.com/iov-one/weave/issues/817):
```go
func (r Router) Handle(m weave.Msg, h weave.Handler)
```
then it absolutely does not matter what value `Path()` method returns as it will never be seen by anyone. The only requirement is to be always the same for each type and unique.

This brings us to the question why do we need `Path` method at all? 
We do not need it. The purpose of the router is to map the message to the right handler. This can be done using the actual [message type](https://golang.org/pkg/reflect/#Type).

The advantage is that we no longer have to implement the `Path` method. It is no longer part of the `weave.Msg` interface. Smaller interfaces equal happy programmers :wink:

**Comment by ruseinov** [comment]
As discussed in that slack topic we need the Path mainly for the code to be easier to understand for someone that hasn't been digging deep in the internals.

While I agree that removing `Path()` makes it easier to write new messages - I think having it both disciplines and also suggests what needs to implemented to any newcomer. Deducing path via reflect makes routing implicit, which is not necessarily good. 

For me as a core weave developer it would of course be nicer if I didn't have to implement an extra method and define a constant, but these types of optimisations eventually lead to systems that are really hard to understand for anyone who is not deeply involved with their development. 

There is one more thing to consider - we are currently using message path for msgfee, so a change like this would lead to problems with refactoring as we'd need to fix the fees as well.

**Comment by husio** [comment]
> There is one more thing to consider - we are currently using message path for msgfee, so a change like this would lead to problems with refactoring as we'd need to fix the fees as well.

This alone makes it not worth removing `Path`.

**Comment by husio** [comment]
`Path` is also needed for funtionality like [action tagger](https://github.com/iov-one/weave/pull/821).
