### ISSUE TITLE
Obfuscation of names and namespaces : Forward look-ups

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#827]
**Is your feature request related to a problem? Please describe.**
As the user and usernames are hashed, there needs to be a way to do a forward lookup of an address.

**Describe the solution you'd like**
As a user I want to send 10 IOV to `alice*iov`, to create the send transaction there is a lookup to return the native IOV address which is then used in the `sendTX` message.

This is done by hashing  `alice*iov` and then the look-up is done using the hashed address.

**Comment by ethanfrey** [comment]
I believe this part just needs documentation on our side. The compatibility layer needs to be done in iov-core.

**Comment by kmw101** [comment]
Needs more analysis work.
