### ISSUE TITLE
Support bip44/slip0010 derivation in bnscli 

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#833]
**Is your feature request related to a problem? Please describe.**
Users should be able to use their derived key for authN.

**Describe the solution you'd like**
`bnscli sign -key my.key -derivation "m/44'/234'/0"`

**Describe alternatives you've considered**
🤔 
**Additional context**
Our genesis test data has mostly derived keys for wallet support.

**Comment by ethanfrey** [comment]
This is closed in favor of #856 

We have opinionated usage and require `m/44'/234'/a'` format, and standard (encrypted) keyfile location

If there is a need to allow slip0010 derivations with other prefixes, please add that to #856 requirements (this is the only aspect dropped between the two issues)
