### ISSUE TITLE
Document weave/bns transaction format

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#840]
As requested by @davepuchyr

Document how to serialize and parse weave transactions, with a special focus on `bnsd` in particular. This is done in iov-core, but we should produce docs, so this can be implemented in many languages without problem.

**Comment by ethanfrey** [comment]
Ignoring Batch and Governance formats, you can start with the main [bnsd tx format](https://github.com/iov-one/weave/blob/v0.18.0/cmd/bnsd/app/codec.proto#L18-L66) as a record of the format.

This is also available for [direct import in other projects](https://github.com/iov-one/weave/blob/v0.18.0/spec/proto/cmd/bnsd/app/codec.proto) with all gogoproto comments stripped out. Actually, the entire `spec/proto` directory can be copied to their app to generate those bindings.

`spec/testvectors` has some examples in binary (protobuf encoded) and json, that can be used as the basis for unit tests in a client library

**Comment by orkunkl** [comment]
For beginning which documentation format should i follow? And where should i keep them?

**Comment by ethanfrey** [comment]
This is a very good question. Maybe we should resolve https://github.com/iov-one/weave/issues/726 first.

If this is for internal docs, please discuss with @husio who has been fighting with our disjoint internal docs and has some ideas how to standardize. (Let's do that before starting yet another format - we can also deprecate readthedocs if we start putting all other knowledge in a good, standard place).

If we are expected to deliver something to external partners with some requirements on what it is (nicely formatted pdf with iov header?), then @davepuchyr must answer that question

**Comment by davepuchyr** [comment]
> If we are expected to deliver something to external partners with some requirements on what it is (nicely formatted pdf with iov header?), then @davepuchyr must answer that question But let's keep the original docs organized in a good place, and generate the pdf from them

Let's keep a single source of truth for the docs by not having various pdfs floating around in the wild.

**Comment by ethanfrey** [comment]
Yes, this is done. I know there is also a link, but when manually closing, can you add a little comment here like "closed by https://github.com/iov-one/docs/pull/5"

(Okay, I did that for this issue, can you do that in the future?).

Ideally, the issues and the prs will be in the same repo (I will create all future docs issues in the new docs repo), and we can just add `Closes #123` on the PR to auto-close and make that reference clear with github.

**Comment by orkunkl** [comment]
Sure got it. Nice tip!
