### ISSUE TITLE
Missing renaming of ReturnSwapMsg

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#847]
In https://github.com/iov-one/weave/blob/master/CHANGELOG.md#0170, `ReturnSwapMsg` is documented to be renamed to `aswap.ReturnMsg`. However, neither in 0.17.0 [nor in current master](https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/1951896/docs/proto/index.html#aswap.ReturnSwapMsg) this renaming was done.

**Comment by husio** [comment]
Done
