### ISSUE TITLE
Username : BlockchainAddress.Address should be string type

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#848]
**Is your feature request related to a problem? Please describe.**
> String indicates that we store printable addresses as the user sees them. Binary indicated that we try to decode string addresses into their binary format. 

Fair point raised by @webmaster128 
https://github.com/iov-one/weave/blob/master/cmd/bnsd/x/username/codec.proto#L39

**Describe the solution you'd like**
Make it protobuf `string` type, again

**Comment by webmaster128** [comment]
@husio can this be closed now?

**Comment by ruseinov** [comment]
@husio this was resolved by merging launch into master, so I assume we're done here.
