### ISSUE TITLE
Consistent Query path

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#849]
**Is your feature request related to a problem? Please describe.**
All abci query path should be consistent. Within the gov-module we have singular and plural names for the route.

**Describe the solution you'd like**
Consistent path declaration over the project + doc.

**Comment by ruseinov** [comment]
I think restful way (e.g.`usernames`) works fine I guess, so we can just go with that.

**Comment by husio** [comment]
As mentioned during our refinement, we did similar [unification for message paths](https://github.com/iov-one/weave/issues/802).

My suggestion for the query path naming rules is:
- [ ] always use popular form of the model name (unless uncountable)
- [ ] use only lower case characters (no underscore `_` or dash `-`)

Few examples for made up models:
- model `User` -> `/users`
- model `Cash` -> `/cash` 
- model `UserProfile` -> `/userprofiles`
- model `RegistrationToken` -> `/registrationtokens`

**Comment by webmaster128** [comment]
Duplicate or huger overlap with https://github.com/iov-one/weave/issues/810. A PR should close both, I think.

**Comment by ruseinov** [comment]
yeah, it should
