### ISSUE TITLE
Close socket on panic()

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#851]
**Is your feature request related to a problem? Please describe.**
When bnsd failed to start due to incorrect genesis file the unix socket file was still existing and required further clean to restart the app.

**Describe the solution you'd like**
Proper house-keeping would close the socket.

**Describe alternatives you've considered**
Document this behaviour

**Additional context**
Example of a panic stacktrace with v0.18.0:
```
panic: invalid escrow at position: 0 : destination: value is empty

goroutine 33 [running]:
github.com/iov-one/weave/app.(*StoreApp).InitChain(0xc0004d6b40, 0xbc87a66, 0xed4ae801f, 0x0, 0xc0000d54e0, 0x11, 0xc000086300, 0xc0004d8150, 0x1, 0x1, ...)
	/home/travis/gopath/src/github.com/iov-one/weave/app/store.go:317 +0x16d
github.com/tendermint/tendermint/abci/server.(*SocketServer).handleRequest(0xc000196be0, 0xc0004d1bf0, 0xc00006df20)
	/home/travis/gopath/pkg/mod/github.com/tendermint/tendermint@v0.31.5/abci/server/socket_server.go:193 +0x81d
github.com/tendermint/tendermint/abci/server.(*SocketServer).handleRequests(0xc000196be0, 0xc00006de00, 0xf8d8a0, 0xc000096040, 0xc00006df20)
	/home/travis/gopath/pkg/mod/github.com/tendermint/tendermint@v0.31.5/abci/server/socket_server.go:163 +0xe4
created by github.com/tendermint/tendermint/abci/server.(*SocketServer).acceptConnectionsRoutine
	/home/travis/gopath/pkg/mod/github.com/tendermint/tendermint@v0.31.5/abci/server/socket_server.go:119 +0x26a
```

**Comment by ruseinov** [comment]
Yes, this reminds me of one issue we opened where we had problems with apps failing once not failing again, because they were simply hung on an already open socket.

Good catch!

**Comment by alpe** [comment]
@ruseinov does this cover/ replace https://github.com/iov-one/weave/issues/273 ?

**Comment by ruseinov** [comment]
I think it does replace it, because the previous ticket was not identified correctly.

**Comment by alpe** [comment]
Reopened the issue as I was not able not confirm that #885 fixes the issue. Although code looked good.

**Comment by ruseinov** [comment]
@alpe @ethanfrey So I have investigated this further, it happens because we are panicking in the ```func (s *StoreApp) InitChain(req abci.RequestInitChain)``` and some other places.

But there is no other way to otherwise kill the app.

Recover does not work, because  in tendermint all this happens in another goroutine `acceptConnectionsRoutine`:
```
func (s *SocketServer) OnStart() error {
	if err := s.BaseService.OnStart(); err != nil {
		return err
	}
	ln, err := net.Listen(s.proto, s.addr)
	if err != nil {
		return err
	}
	s.listener = ln
	go s.acceptConnectionsRoutine()
	return nil
}
```

**Comment by ruseinov** [comment]
I think the only real way we could fix it is ask tendermint to be able to supply the callback and do it on recover in this routine.

**Comment by kmw101** [comment]
Moved this issue back to the backlog pending a resolution from Tendermint. Assigning a `blocked` label

**Comment by ruseinov** [comment]
Tendermint issue here: https://github.com/tendermint/tendermint/issues/3800

**Comment by ruseinov** [comment]
UPD: This change got approved, waiting to be merged to master and backported to 0.31.x tendermint for us to utilise it.

**Comment by ethanfrey** [comment]
Great work :1st_place_medal:

**Comment by ruseinov** [comment]
@husio @alpe unfortunately my lovely fixes got merged a long with some breaking changes and while fixing these changes here: https://github.com/tendermint/tendermint/pull/3858 the PR got too big, so it's not gonna be backported.

Which basically means that we'll need to upgrade when there is a stable version of tendermint we like.

**Comment by alpe** [comment]
I have upgraded weave v0.21.x branch  to tm v0.31.9 which includes the socket fix and changes to the rpc-client. Both are good changes we want in master. I keep this issue open to verify the tendermint upgrade fixes.

**Comment by ruseinov** [comment]
Great!

**Comment by husio** [comment]
This might be fixed by now.
