### ISSUE TITLE
Example code for bnscli

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#853]
To help the governing board a number of code examples and the output expected need to be written.

- [x] Transfer funds from guarantee to reward
- [x] Add a validator
- [x] Add a new member to the tech committee
- [x] Change the quorum for the economic committee

**Comment by ethanfrey** [comment]
We should:

1. Link all `clitest` examples from `bnscli/README.md`
2. Add a separate examples file (in clitest?) for those that involve actually signing, setting fees, and submitting, which cannot be in the shell tests
3. Ensure the above requests are defined in the appropriate place and clearly linked from `bnscli/README.md`

After this, we can hand off dev-level documentation to @orkunkl to integrate into the full iov documentation effort.

**Comment by alpe** [comment]
I did some examples already in the [wiki](https://github.com/iov-one/ops/wiki/gov---bnscli#gov-command-examples). Let's use this as starting point, add the other examples and then move them to `bnscli` folder as suggested.
