### ISSUE TITLE
migration from bnscli to GUI using IOV core

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#856]
As a user I want to be able to migrate from using `bnscli` to a client using IOV Core, so that I can create my credentials (key) using available now `bnscli` and later switch to a GUI when it is available, without the need to reset my credentials.

We must define what is the migration path and what must be implemented today in order to make it possible.

One idea is to derive keys from mnemonics and possibly store these(mnemonics?) in key storage. In this case we’ll have general compatibility with IOV-Core as it can derive keys from mnemonics too.

If we can share the storage - even better.

## Acceptance criteria

- [ ] ~dockerize `bnscli`~
- [ ] ...

**Comment by ethanfrey** [comment]
> It would also be nice to dockerize bnscli to support any platform. And figure out how it's going to play with secure key storage.

This is an interesting idea, but distribution should be discussed as a separate issue: #876

**Comment by ethanfrey** [comment]
IOV core uses slip-0010 to derive keys. This is implemented in https://godoc.org/github.com/stellar/go/exp/crypto/derivation and we can make use of that.

For compatibility with iov-core, we should use `44'/234'/a'` for the iov derivation path: https://github.com/iov-one/iov-core/blob/master/packages/iov-keycontrol/src/hdpaths.ts#L48

a starts at 0 and is incremented by 1 for each account.

This means we need to store a mnemonic and the number of accounts created and from that can recover all private keys. The same mnemonic imported into iov-core or bnscli would produce the same keys.

Sharing storage with iov-core, which a nice idea, would likely be too fragile and hard to do right, best to use mnemonics for manual importing/exporting between different "wallets"

**Comment by kmw101** [comment]
Linked to #855 - duplicate issue
