### ISSUE TITLE
Consistent Username addresses encoding

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#860]
**Is your feature request related to a problem? Please describe.**
We use hex encoding with our weave addresses but current initializer code expectes base64 encoded (json default) addresses. 

**Describe the solution you'd like**
hex encoding

**Describe alternatives you've considered**
Not enforcing a chain address for a username in genesis would actually be better for my case.

**Additional context**
See https://github.com/iov-one/weave/issues/848

**Comment by ethanfrey** [comment]
Ah, this is `cmd/bnsd/x/username/init.go` related?

Yes, they should define this as a string, and everyone is happy. We shouldn't worry what it is. Just accept the data in, store it, and return it to the client. The client is responsible for providing proper data, as we are unable to verify it.

We cannot assume hex or any weave-related encodings. Lisk addresses are eg. `1233455L`, ethereum are `0x1234`, both of which would fail with a generic hex decoder

**Comment by ethanfrey** [comment]
This fix should go into `launch` branch
