### ISSUE TITLE
Sending tokens to myself should not be allowed

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#864]
At the moment it is possible to send tokens to myself. The impact is that I can use it to slow the network down while just paying a low anti-spam fee.

Add a fix to check that if the sender and recipient are the same the transaction is not done and an error message returned.

**Comment by husio** [comment]
Isn't the purpose of anti spam fee to prevent exactly this scenario? Otherwise, you can use any zero impact operation to spam messages. You could use two accounts to send the same amount between them.

**Comment by kmw101** [comment]
Good point, I have asked @davepuchyr to look into this.

**Comment by ethanfrey** [comment]
Where did this issue come from?

If I want to avoid this, I simply make two addresses controlled by me (two different private keys, trivial with iov-core) and send back and forth.

@husio is right, that is exactly what anti-spam fee is for, and if the genesis fee is too low, validators and always increase their subjective fee (which blocks them broadcasting or including in blocks they produce) with a simple command line flag.

Relevant code: `x/msgfee/antispam_fee_decorator.go`:

```go
// AntispamFeeDecorator implements a decorator that for each processed transaction
// asks for a minimal fee. The fee is defined globally in the app.
// If fee is not set (zero value) or is less than the fee already asked for the transaction
// then this decorator is a noop.
type AntispamFeeDecorator struct {
	fee coin.Coin
}
```

And enabled by `-min_fee "1 IOV"`, per https://github.com/iov-one/weave/blob/launch/commands/server/start.go#L37

**Comment by davepuchyr** [comment]
> Isn't the purpose of anti spam fee to prevent exactly this scenario? Otherwise, you can use any zero impact operation to spam messages. You could use two accounts to send the same amount between them.

Yes, right after I raised the self-send issue with Martin I mentioned the ping-pong case as well.  This is quickly leading to us being able to adjust the minimum spam fee on the fly, ie the mutable on-chain parameters milestone.

**Comment by ethanfrey** [comment]
@davepuchyr We addressed this several months ago with the approach used on GoS. No governance procedure will address this fast enough. Look at my answer above.

**Comment by ethanfrey** [comment]
We do need better docs so this is more visible

**Comment by davepuchyr** [comment]
I was thinking a long the lines of monitoring the network load and programatically adjusting the minimum fee.  I don't see the "restart your validator" as a tenable solution.

**Comment by ethanfrey** [comment]
I am closing this issue. 
The title ("sending tokens to myself should not be allowed") is rejected as impractical and with no real utiltiy.

There is another issue in the comments about some complex auto-adjusting fee magic, which can be added as a post-launch request. The manual antispam flags will respond to an emergency at least as well as the cosmos validators can.
