### ISSUE TITLE
Change an election quorum

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#869]
Ability to create a proposal by governing board to change an election quorum.

## Acceptance criteria
- [x] Modify `UpdateElectionRuleMsg` in the `gov` package to allow to change an election quorum.
- [x] Update `bnscli` to include creation of this message.

**Comment by webmaster128** [comment]
Context: Item `AmendCommitteeQuorum` from https://github.com/iov-one/iov-core/issues/1112 cc @willclarktech

**Comment by alpe** [comment]
This can be added as field into [UpdateElectionRuleMsg](https://github.com/iov-one/weave/blob/master/x/gov/codec.proto#L253) which is used for an update via overwrite.
