### ISSUE TITLE
Secure distribution channel for bnscli

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#876]
If bnscli is supposed to be a secure tool for users to run against our blockchain, we need to ensure a secure distribution channel.

First we consider how to post the artifacts:

* One choice is docker hub.
* Another is github releases.
* Another is iov.one website.

Second we control how to validate integrity. We should post sha256 hashes in a secure medium, and ideally gpg signatures for that (but will anyone every check those).

We need to define a process, then use it.

**Comment by kmw101** [comment]
depends on ops#183
