### ISSUE TITLE
Wrong migration package in `revenue` - revisit all packages

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#901]
## Expected Behavior
`revenue` but found `distribution`

## Actual Behavior
See https://github.com/iov-one/weave/blob/master/x/distribution/model.go#L107

## Additional info
This task includes the fix for this package as well as checking all the others to be on the safe side.

**Comment by husio** [comment]
I don't understand what is the problem? Both package and model name seems to be correct.

**Comment by alpe** [comment]
You are right. Sorry for the confusion. I will never get used to it that one is called revenue and the other distribution. Thanks for checkin!
