### ISSUE TITLE
Do not return `minimal_fee` with empty ticker

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#921]
:warning: This issue requires another refinement. Please read https://github.com/iov-one/weave/issues/921#issuecomment-520738666

[`coin.Coin minimal_fee = 4 [(gogoproto.nullable) = false]`](https://github.com/iov-one/weave/blob/master/x/cash/codec.proto#L46) does return an empty ticker when not set in genesis. This can cause confusion with the clients.

## Acceptance criteria
- [ ] change the type of the `minimal_fee` field to a nullable `coin.Coin`

**Comment by husio** [comment]
The configuration for the `x/cash` extension is handled by the `gconf` package. Part of the `gconf` functionality is to provide an update handler that is used in the `x/cash`

https://github.com/iov-one/weave/blob/master/x/cash/handler.go#L79-L82

Provided handler performs a PATCH operation - it takes [the configuration instance embedded by the message](https://github.com/iov-one/weave/blob/master/x/cash/codec.proto#L51) and rewrites only those values for which a non zero value is provided. 

https://github.com/iov-one/weave/blob/master/gconf/handler.go#L95-L98

This means, that if [`minimal_fee`](https://github.com/iov-one/weave/blob/master/x/cash/codec.proto#L46) is changed to a nullable field (can take `nil` value), there is no way to update it to a `nil` value.

I think the current solution (zero coin with no ticker) while might be initially confusing, provides the best  solution. Should I close this issue without changing the implementation or someone has an idea how to do this differently?

**Comment by webmaster128** [comment]
@alpe could you please verify this is the case and there is no easy alternative? Thanks

@husio if that is the case, let's stick with the current solution. We can normalize any 0 quantity fee to unset on client side if we are aware of this limitation.

**Comment by husio** [comment]
The current implementation does not allow to set "no fee" as well. `Coin{0, 0, ""}` is also a zero value and therefore it does not overwrite an existing value.
I think the only easy to explain (how it works) solution is to change the handler implementation to do PUT instead of PATCH. If it always overwrites the configuration state with a given one, any value can be set.

**Comment by alpe** [comment]
@webmaster128 Beside a PUT request a nil value object would be something that may work. But this would also create new problems like how to communicate this to the users.
I would argue that a zero fee scenario is not very realistic for a production network.

**Comment by webmaster128** [comment]
> The current implementation does not allow to set "no fee" as well. `Coin{0, 0, ""}` is also a zero value and therefore it does not overwrite an existing value.

i.e. we cannot change from some fee to no fee either way. I think this is a limitation that everybody can live with. You can start a network with no fee set and then upgrade to some fee. From there you can only change it to something very small.

This also means we can make the field nullable, right? If yes, I'd like to change it.

> create new problems like how to communicate this to the users.

What do you mean? Clients query the min fee from the blockchain (for every new transaction at the moment).

**Comment by husio** [comment]
No update behavior of the current PATCH implementation is true for all [zero values](https://golang.org/ref/spec#The_zero_value). This means that if you have a configuration, none of the attributes can be updated to represent that types zero value (empty string, 0, nil etc).

**Comment by webmaster128** [comment]
Good to know. This is a serious limitation but okay. No issue right now as fas as I can see.

Then let's change `minimal_fee` to nullable as described in the original description. This at least allows us to have clean null values in the genesis and avoids passing around `Coin{0, 0, ""}` structures.

**Comment by husio** [comment]
I am putting this story back to backlog. I think it requires more thoughts.

In my opinion, we can do one of two things:
1. Leave the code as it is because only changing `minimal_fee` to a nullable value does not make it in my opinion any better
2. Update the `gconf` package handler and change PATCH to PUT. After that, update the `minimal_fee` to be a nullable value and prohibit from using a zero value coin.

**Comment by webmaster128** [comment]
I'll create an `isZeroCoin(coin: coin.ICoin)` helper that will be used to translate `Coin{0, 0, ""}` to _unset_  client-side.

**Comment by husio** [comment]
That makes sense. We have the very same function defined in weave:

https://github.com/iov-one/weave/blob/master/coin/coin.go#L206-L209

**Comment by webmaster128** [comment]
In this case, the definition of `Coin.ticker` is unprecise:

> Ticker is 3-4 upper-case letters and all Coins of the same currency can be combined 

https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/master/docs/proto/index.html#coin.Coin
