### ISSUE TITLE
bnscli: additional query support

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#925]
**Is your feature request related to a problem? Please describe.**
Support queries for 
* escrow
* distribution
* multiSig

**Describe the solution you'd like**
Add query path and result decoder to bnscli that support list of all and details of a single entity.

**Describe alternatives you've considered**

**Additional context**
To work and test with the guarantee fond, I want to query it's current address and internal configuration. In order to find the "right" escrow I need some way to fetch a list. Otherwise I can only make assumptions about the correct id.

**Acceptance criteria**
- [x] I can query all escrows and see the list of them containing the ID
- [x] I can query a single escrow by ID and see the expected decoded data
- [x] I can query all distributions and see the list of them containing the ID
- [x] I can query a single distribution and see the expected decoded data
- [x] I can query all multiSig and see the list of them containing the ID
- [x] I can query a single multiSig and see the expected decoded data

**Comment by husio** [comment]
Escrow
```
bnscli query -path '/escrows'
bnscli query -path '/escrows' -data 1
```

Distribution
```
bnscli query -path '/revenues' 
bnscli query -path '/revenues'  -data 1
```

Multisig
```
bnscli query -path '/contracts'
bnscli query -path '/contracts' - data 1
```
