### ISSUE TITLE
Implement BIP-39

### ISSUE THREAD

**Issue by husio** [iov-one/weave#929]
As developer, I want to implement [BIP 39 spec](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) instead of using https://github.com/tyler-smith/go-bip39, so that we do not have to rely on [inconsistent](https://github.com/iov-one/weave/pull/923/commits/0094caee91b76c8fe5d541ed258e2f1527926435#diff-6569bb577f21a71b8e731cb7dc0f2b24R102-R115) and [abandoned software with bugs](https://github.com/tyler-smith/go-bip39/issues).

This issue is a result of [learnings from implementing mnemonic support in `bnscli`](https://github.com/iov-one/weave/pull/923#issuecomment-516830125). Used bip-39 package contains bugs and it is not updated for more than a year. If we have time, we should consider either fork & fix or implementing the spec from scratch.

## Acceptance criteria
- [ ] provide a package that implements mnemonic and seed generation as described in BIP 39 
- [ ] if we work on a fork, send changes upstream to the original repository
- [ ] propose an update to https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#Reference_Implementation and notify other projects that there is a new BIP-39 implementation in town! :cowboy_hat_face:

**Comment by ruseinov** [comment]
To be fair, there are some other go implementations already:
https://github.com/bgadrian/go-mnemonic/tree/master/bip39
https://github.com/islishude/bip39
https://github.com/landonia/crypto

**Comment by kmw101** [comment]
Not required as the bnscli is not going to be launched to mainnet
