### ISSUE TITLE
Potentially weak key generation on certain platforms

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#938]
From the Security Audit

> Regarding ed25519 key generation 
/master/weave_audit/crypto/ed25519.go#L53, per https://golang.org/pkg/crypto/rand/ :
 
> "On Windows systems, Reader uses the CryptGenRandom API."  It would be preferable to use BCryptGenRandom from the newer API, however, this is a Go language issue intended to maintain backwards compatibility.
 
> Suggestion: if platform is Windows, emit a warning, or use a different entropy source directly. E.g. user space instructions like RDRAND or XSTORE.
 
> On Unix like systems, ensure that the host has an entropy source, such as a True Random Number Generaror (TRNG) or Entropy Gathering Daemon (EGD):
"On Linux and FreeBSD, Reader uses getrandom(2) if available, /dev/urandom otherwise. On OpenBSD, Reader uses getentropy(2). On other Unix-like systems, Reader reads from /dev/urandom."
> Properly seeding the entropy pool and regularly adding entropy to the pool will ensure that a broad class of weak key attacks are prevented. See https://factorable.net/paper.html for additional information.

**Comment by kmw101** [comment]
Add a note to Security.MD

**Comment by ruseinov** [comment]
Not relevant, closing
