### ISSUE TITLE
Benchmark for the cache signature

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#940]
Related to issue #16 the first step is to benchmark the performance to establish whether there is a need to optimise with a cache.

> Before implementing the signature verification cache, please provide a benchmark that test the current performance. Once we know how much time the current solution takes, we will decide if we want to optimize it.

## Acceptance criteria
- [ ] ?

**Comment by husio** [comment]
From https://github.com/iov-one/weave/pull/942
```
goos: linux
goarch: amd64
pkg: github.com/iov-one/weave/x/sigs
BenchmarkVerifySignatures/memory_store_small_payload-4                  10000   174463 ns/op
BenchmarkVerifySignatures/memory_store_big_payload-4                     5000   285872 ns/op
BenchmarkVerifySignatures/hard_drive_backed_store_with_small_payload-4  10000   173257 ns/op
BenchmarkVerifySignatures/hard_drive_backed_store_with_bit_payload-4    10000   237035 ns/op
```
