### ISSUE TITLE
Block metric query :  precommit query

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#944]
To provide meaningful data for the calculation of quality score there needs to be the following query:

When a Validator proposes a block, we need to know the number of precommits that were included in the block and the number that were missing.

The output of the query is in a csv format and contains the following columns:

Height | Validator Address | Precommits | Missing Precommits | Missed Precommits Since Last Proposal
-- | -- | -- | -- | --

## Acceptance criteria
- [x] Run described query on `lovenet` network and produce CSV file in the defined format.
- [x] Create a file with an SQL query to compute those results using database created by https://github.com/iov-one/block-metrics application
- [x] Upload the result SQL and CSV files to google drive to `Products > Dev Resources` directory.

**Comment by husio** [comment]
```sql
SELECT
        subq.block_height,
        validator_address,
        precommits,
        missing_precommits,
        (
                SELECT
                        COUNT(*)
                FROM
                        block_participations bp
                WHERE
                        bp.block_id <= subq.block_height
                        AND bp.block_id >= lb.prev_block_proposed
                        AND bp.validator_id = subq.proposer_id
                        AND NOT bp.validated
        ) AS missed_precommits_slp
FROM
        (
                SELECT
                        b.block_height,
                        b.proposer_id,
                        v.address AS validator_address,
                        SUM(CASE WHEN validated = true THEN 1 ELSE 0 END) AS precommits,
                        SUM(CASE WHEN validated = false THEN 1 ELSE 0 END) AS missing_precommits
                FROM
                        blocks b
                        LEFT JOIN validators v ON b.proposer_id = v.id
                        LEFT JOIN block_participations bp ON b.block_height = bp.block_id
                GROUP BY
                        block_height,
                        proposer_id,
                        validator_address
        ) AS subq
        LEFT JOIN (
                SELECT
                        proposer_id,
                        block_height,
                        lag(block_height) OVER (PARTITION BY proposer_id  ORDER BY block_height ASC) AS prev_block_proposed
                FROM
                        blocks
        ) AS lb ON subq.block_height = lb.block_height AND subq.proposer_id = lb.proposer_id
ORDER BY block_height DESC
;
```

**Comment by ruseinov** [comment]
Good stuff!

The query looks good to me. I don't remember which indexes are set up, but I'm pretty sure it's optimised enough to be run once a month.

A couple of non-blocking nits: `subq -> proposer_query`, `lb -> last_block` ?
That's for better readability for anyone who wants to understand what all the subqueries do without thinking too  much.

**Comment by kmw101** [comment]
Is this issue done?

**Comment by husio** [comment]
I think yes. @davepuchyr validated the result as well.

**Comment by husio** [comment]
Done
