### ISSUE TITLE
Block metric query : missed precommits

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#945]
To provide meaningful data for the calculation of quality score there needs to be the following query:

When a validator proposes a block, we need to know the number of that validator’s missed precommits since that validator's last block proposal.

We want the quality score to be not only computed from the number of precommits that validator make but also by the number that validator missed.

Validator can be new in the validator set. This cause no value for period before adding that validator, result is zero.

The output of the query is in a CSV format and contains the following columns:

Height | Validator Address | Precommits | Missing Precommits | Missed Precommits Since Last Proposal
-- | -- | -- | -- | --

## Acceptance criteria
- [x] Run described query on `lovenet` network and produce CSV file in the defined format.
- [x] Create a file with an SQL query to compute those results using database created by https://github.com/iov-one/block-metrics application
- [x] Upload the result files to google drive to `Products > Dev Resources` directory.

**Comment by husio** [comment]
The result is created with the same query as posted in https://github.com/iov-one/weave/issues/944#issuecomment-521235008

**Comment by ruseinov** [comment]
As posted in #944 - looks good to me.

**Comment by husio** [comment]
Done
