### ISSUE TITLE
Update namespace validation rules

### ISSUE THREAD

**Issue by husio** [iov-one/weave#952]
The current username implementation is using a regexp to ensure only certain letters are allowed.

https://github.com/iov-one/weave/blob/master/cmd/bnsd/x/username/username.go#L67-L70

Change those rules to be fulfill new requirements described below.

## Acceptance criteria
- [ ] A username consists of a name and namespace separated by a single `*` character (for example `alice*iov`)
- [ ] A namespace must be `iov`
- [ ] A name must be between 0 and not longer than 64 characters
- [ ] A name must consist of only the following ASCII characters 
  - letters `abcdefghijklmnopqrstuvwxyz`
  - digits  `0123456789`
  - special characters `-._`

**Comment by kmw101** [comment]
I have updated the name length specification in the description. The name length must be between 0 and 64 characters.

**Comment by webmaster128** [comment]
name length of 0 is legal? That feels broken. Or do we want to have length range `[1, 64]`?

**Comment by husio** [comment]
Zero is allowed in the future design that we finalize. This is zero for backward compatyblity.

**Comment by husio** [comment]
First, I would like to make everyone aware that this is incredibly disappointing that the very core of what IOV want to build and yet such trivial decision is not yet made.

After more discussion about the namespaces and how it should work and look, I think it is becoming less clear to me what we are building. To make it better I propose a fresh start of the conversation about **the current implementation** that we want to use for the release. Not the future release, not the release we want to end up with. Release for NOW.

That said, some decisions can be influenced by future functionalities that we would like to see. They are not to be included now. Future functionalities might only be used as guidelines for the current implementation but must not determine it.

Below is my set of rules for the current implementation, that we will release to the public with the first release:
- A username must be `<name>*iov`,
- A namespace labels is always `iov`. We do not allow any other label,
- A `name` must be minimum 3 and maximum 64 characters,
- A `name` must be build using only the following ASCII characters `abcdefghijklmnopqrstuvwxyz0123456789-_.` (last 3 being dot, underscore and dash),
- A username can have any number of references to a blockchain address (no references is allowed),
- A username can be registered by anyone. Anti spam fee must be paid. If a additional fee is set on the message, it must be paid as well.

**Comment by kmw101** [comment]
I have reverted the acceptance criteria back to minimum of 3
