### ISSUE TITLE
Add flag to bcpd to show/hide stack trace on abci errors

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#97]
Ethan thinks there is a todo there in top level result.go. Let's do it

**Comment by ethanfrey** [comment]
Relevant lines for abci messages:

https://github.com/iov-one/weave/blob/master/abci.go#L99-L101
https://github.com/iov-one/weave/blob/master/abci.go#L112-L114

It would be nice to add a `-debug` flag here:
https://github.com/iov-one/weave/blob/master/commands/server/start.go
Default false, only if on is entire stacktrace dumped.
