### ISSUE TITLE
Merge x/username with the new namespaces implementation (spike)

### ISSUE THREAD

**Issue by husio** [iov-one/weave#973]
As a user I want to register a username within an existing namespace (i.e. `*iov`)

In #972 a minimal namespace implementation was provided. This issue is about merging that namespace implementation with an existing `x/username` functionality.

## Acceptance criteria
- [x] the `iov` namespace must be always registered
- [x] update existing `x/username` extension to respect namespace functionality
- [x] a username can be registered only for an existing namespace functionality
- [x] only the namespace owner can register a username within a namespace
- [x] an exception to the previous rule: _anyone_ can register a username within `iov` namespace
- [x] a full username representation is `<name>*<namespace_label>`
- [x] a name must be unique within each namespace. The same name can be used in different namespace (i.e. `bob*iov` and `bob*evilcorp` are different usernames)
- [x] a username name validation must be updated to follow new requirements
  - [x] a name must be at least zero characters long (empty)
  - [x] a name must be at most 64 characters long
  - [x] a name can consist only of the following ASCII characters (no whitespace) `abcdefghijklmnopqrstuvwxyz0123456789-_.`

## Non goals
- username expiration, freezing, unregistration

**Comment by alpe** [comment]
>  a name must be at least zero characters long (empty)

Should we pre-register "<empty>*iov" so that nobody else can claim it? (Acceptance criteria)

**Comment by husio** [comment]
I think this is a very good point and it might be required to provide the right functionality.

This issue is about providing a minimum update to already existing code so that it is a bit closer to requested in namespace spec functionality. I think all additional requirements that do not change the core design should go to separate issues.

**Comment by husio** [comment]
[Specification has changed](https://iov.atlassian.net/wiki/spaces/PRODUCT/pages/786453/Starnames+namespace+product+specification) and new issues are created.
